<!DOCTYPE html>

<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->

<!-- Head BEGIN -->
<head>
  <meta charset="utf-8">
  <title>Shopping cart | Metronic Shop UI</title>

  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <meta content="Metronic Shop UI description" name="description">
  <meta content="Metronic Shop UI keywords" name="keywords">
  <meta content="keenthemes" name="author">

  <meta property="og:site_name" content="-CUSTOMER VALUE-">
  <meta property="og:title" content="-CUSTOMER VALUE-">
  <meta property="og:description" content="-CUSTOMER VALUE-">
  <meta property="og:type" content="website">
  <meta property="og:image" content="-CUSTOMER VALUE-"><!-- link to image for socio -->
  <meta property="og:url" content="-CUSTOMER VALUE-">

  <link rel="shortcut icon" href="favicon.ico">

  <!-- Fonts START -->
  <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700|PT+Sans+Narrow|Source+Sans+Pro:200,300,400,600,700,900&amp;subset=all" rel="stylesheet" type="text/css"> 
  <!-- Fonts END -->

  <!-- Global styles START -->          
  <link href="/shop/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
  <link href="/shop/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <!-- Global styles END --> 
   
  <!-- Page level plugin styles START -->
  <link href="/shop/assets/plugins/fancybox/source/jquery.fancybox.css" rel="stylesheet">
  <link href="/shop/assets/plugins/owl.carousel//shop/assets/owl.carousel.css" rel="stylesheet">
  <link href="/shop/assets/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css">
  <link href="/shop/assets/plugins/themes/smoothness/jquery-ui.css" rel="stylesheet" type="text/css"><!-- for slider-range -->
  <link href="/shop/assets/plugins/rateit/src/rateit.css" rel="stylesheet" type="text/css">
  <!-- Page level plugin styles END -->

  <!-- Theme styles START -->
  <link href="/shop/assets/pages/css/components.css" rel="stylesheet">
  <link href="/shop/assets/corporate/css/style.css" rel="stylesheet">
  <link href="/shop/assets/pages/css/style-shop.css" rel="stylesheet" type="text/css">
  <link href="/shop/assets/corporate/css/style-responsive.css" rel="stylesheet">
  <link href="/shop/assets/corporate/css/themes/red.css" rel="stylesheet" id="style-color">
  <link href="/shop/assets/corporate/css/custom.css" rel="stylesheet">
  <!-- Theme styles END -->
</head>
<!-- Head END -->

<!-- Body BEGIN -->
<body class="ecommerce">
    <!-- BEGIN STYLE CUSTOMIZER -->
    <div class="color-panel hidden-sm">
      <div class="color-mode-icons icon-color"></div>
      <div class="color-mode-icons icon-color-close"></div>
      <div class="color-mode">
        <p>THEME COLOR</p>
        <ul class="inline">
          <li class="color-red current color-default" data-style="red"></li>
          <li class="color-blue" data-style="blue"></li>
          <li class="color-green" data-style="green"></li>
          <li class="color-orange" data-style="orange"></li>
          <li class="color-gray" data-style="gray"></li>
          <li class="color-turquoise" data-style="turquoise"></li>
        </ul>
      </div>
    </div>
    <!-- END BEGIN STYLE CUSTOMIZER --> 

    <!-- BEGIN TOP BAR -->
    <?php echo $this->view->getPartial('layouts/_header') ?>
    <!-- Header END -->

    <div class="main">
      <div class="container">
        <!-- BEGIN SIDEBAR & CONTENT -->
        <div class="row margin-bottom-40">
          <!-- BEGIN CONTENT -->
          <div class="col-md-12 col-sm-12">
            <h1>Shopping cart</h1>
            <div class="goods-page">
              <div class="goods-data clearfix">
                <div class="table-wrapper-responsive">
                <table summary="Shopping cart" id="table-buycar">
                	<thead>
	                	<tr>
	                    <th class="goods-page-image">图片</th>
	                    <th class="goods-page-description">商品名称</th>
	                    <th class="goods-page-color">商品颜色</th>
	                    <th class="goods-page-size">商品尺寸</th>
	                    <th class="goods-page-quantity">数量</th>
	                    <th class="goods-page-price">单价</th>
	                    <th class="goods-page-total" colspan="2">总价</th>
	                  </tr>
                	</thead>
                  <tbody>
                  </tbody>
                </table>
                </div>

                <div class="shopping-total">
                  <ul>
                    <li>
                      <em>商品总价</em>
                      <strong class="price" id="price-1"></strong>
                    </li>
                    <li>
                      <em>运费</em>
                      <strong class="price" id="price-2"></strong>
                    </li>
                    <li class="shopping-total-price">
                      <em>总计</em>
                      <strong class="price" id="price-3"></strong>
                    </li>
                  </ul>
                </div>
              </div>
              <button class="btn btn-default" type="submit">继续购物 <i class="fa fa-shopping-cart"></i></button>
              <button class="btn btn-primary" type="button" id="btn-checkout">去结算 <i class="fa fa-check"></i></button>
            </div>
          </div>
          <!-- END CONTENT -->
        </div>
        <!-- END SIDEBAR & CONTENT -->

        <!-- BEGIN SIMILAR PRODUCTS -->
        <div class="row margin-bottom-40">
          <div class="col-md-12 col-sm-12">
            <h2>Most popular products</h2>
            <div class="owl-carousel owl-carousel4">
              <div>
                <div class="product-item">
                  <div class="pi-img-wrapper">
                    <img src="/shop/assets/pages/img/products/k1.jpg" class="img-responsive" alt="Berry Lace Dress">
                    <div>
                      <a href="/shop/assets/pages/img/products/k1.jpg" class="btn btn-default fancybox-button">Zoom</a>
                      <a href="#product-pop-up" class="btn btn-default fancybox-fast-view">View</a>
                    </div>
                  </div>
                  <h3><a href="shop-item.html">Berry Lace Dress</a></h3>
                  <div class="pi-price">$29.00</div>
                  <a href="javascript:;" class="btn btn-default add2cart">Add to cart</a>
                  <div class="sticker sticker-new"></div>
                </div>
              </div>
              <div>
                <div class="product-item">
                  <div class="pi-img-wrapper">
                    <img src="/shop/assets/pages/img/products/k2.jpg" class="img-responsive" alt="Berry Lace Dress">
                    <div>
                      <a href="/shop/assets/pages/img/products/k2.jpg" class="btn btn-default fancybox-button">Zoom</a>
                      <a href="#product-pop-up" class="btn btn-default fancybox-fast-view">View</a>
                    </div>
                  </div>
                  <h3><a href="shop-item.html">Berry Lace Dress2</a></h3>
                  <div class="pi-price">$29.00</div>
                  <a href="javascript:;" class="btn btn-default add2cart">Add to cart</a>
                </div>
              </div>
              <div>
                <div class="product-item">
                  <div class="pi-img-wrapper">
                    <img src="/shop/assets/pages/img/products/k3.jpg" class="img-responsive" alt="Berry Lace Dress">
                    <div>
                      <a href="/shop/assets/pages/img/products/k3.jpg" class="btn btn-default fancybox-button">Zoom</a>
                      <a href="#product-pop-up" class="btn btn-default fancybox-fast-view">View</a>
                    </div>
                  </div>
                  <h3><a href="shop-item.html">Berry Lace Dress3</a></h3>
                  <div class="pi-price">$29.00</div>
                  <a href="javascript:;" class="btn btn-default add2cart">Add to cart</a>
                </div>
              </div>
              <div>
                <div class="product-item">
                  <div class="pi-img-wrapper">
                    <img src="/shop/assets/pages/img/products/k4.jpg" class="img-responsive" alt="Berry Lace Dress">
                    <div>
                      <a href="/shop/assets/pages/img/products/k4.jpg" class="btn btn-default fancybox-button">Zoom</a>
                      <a href="#product-pop-up" class="btn btn-default fancybox-fast-view">View</a>
                    </div>
                  </div>
                  <h3><a href="shop-item.html">Berry Lace Dress4</a></h3>
                  <div class="pi-price">$29.00</div>
                  <a href="javascript:;" class="btn btn-default add2cart">Add to cart</a>
                  <div class="sticker sticker-sale"></div>
                </div>
              </div>
              <div>
                <div class="product-item">
                  <div class="pi-img-wrapper">
                    <img src="/shop/assets/pages/img/products/k1.jpg" class="img-responsive" alt="Berry Lace Dress">
                    <div>
                      <a href="/shop/assets/pages/img/products/k1.jpg" class="btn btn-default fancybox-button">Zoom</a>
                      <a href="#product-pop-up" class="btn btn-default fancybox-fast-view">View</a>
                    </div>
                  </div>
                  <h3><a href="shop-item.html">Berry Lace Dress5</a></h3>
                  <div class="pi-price">$29.00</div>
                  <a href="javascript:;" class="btn btn-default add2cart">Add to cart</a>
                </div>
              </div>
              <div>
                <div class="product-item">
                  <div class="pi-img-wrapper">
                    <img src="/shop/assets/pages/img/products/k2.jpg" class="img-responsive" alt="Berry Lace Dress">
                    <div>
                      <a href="/shop/assets/pages/img/products/k2.jpg" class="btn btn-default fancybox-button">Zoom</a>
                      <a href="#product-pop-up" class="btn btn-default fancybox-fast-view">View</a>
                    </div>
                  </div>
                  <h3><a href="shop-item.html">Berry Lace Dress6</a></h3>
                  <div class="pi-price">$29.00</div>
                  <a href="javascript:;" class="btn btn-default add2cart">Add to cart</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- END SIMILAR PRODUCTS -->
      </div>
    </div>

    <!-- BEGIN STEPS -->
    <div class="steps-block steps-block-red">
      <div class="container">
        <div class="row">
          <div class="col-md-4 steps-block-col">
            <i class="fa fa-truck"></i>
            <div>
              <h2>Free shipping</h2>
              <em>Express delivery withing 3 days</em>
            </div>
            <span>&nbsp;</span>
          </div>
          <div class="col-md-4 steps-block-col">
            <i class="fa fa-gift"></i>
            <div>
              <h2>Daily Gifts</h2>
              <em>3 Gifts daily for lucky customers</em>
            </div>
            <span>&nbsp;</span>
          </div>
          <div class="col-md-4 steps-block-col">
            <i class="fa fa-phone"></i>
            <div>
              <h2>477 505 8877</h2>
              <em>24/7 customer care available</em>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- END STEPS -->

    <!-- BEGIN PRE-FOOTER -->
    <?php echo $this->view->getPartial('layouts/_footer') ?>
    <!-- END FOOTER -->

    <!-- BEGIN fast view of a product -->
    <div id="product-pop-up" style="display: none; width: 700px;">
            <div class="product-page product-pop-up">
              <div class="row">
                <div class="col-md-6 col-sm-6 col-xs-3">
                  <div class="product-main-image">
                    <img src="/shop/assets/pages/img/products/model7.jpg" alt="Cool green dress with red bell" class="img-responsive">
                  </div>
                  <div class="product-other-images">
                    <a href="javascript:;" class="active"><img alt="Berry Lace Dress" src="/shop/assets/pages/img/products/model3.jpg"></a>
                    <a href="javascript:;"><img alt="Berry Lace Dress" src="/shop/assets/pages/img/products/model4.jpg"></a>
                    <a href="javascript:;"><img alt="Berry Lace Dress" src="/shop/assets/pages/img/products/model5.jpg"></a>
                  </div>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-9">
                  <h1>Cool green dress with red bell</h1>
                  <div class="price-availability-block clearfix">
                    <div class="price">
                      <strong><span>$</span>47.00</strong>
                      <em>$<span>62.00</span></em>
                    </div>
                    <div class="availability">
                      Availability: <strong>In Stock</strong>
                    </div>
                  </div>
                  <div class="description">
                    <p>Lorem ipsum dolor ut sit ame dolore  adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat 
Nostrud duis molestie at dolore.</p>
                  </div>
                  <div class="product-page-options">
                    <div class="pull-left">
                      <label class="control-label">Size:</label>
                      <select class="form-control input-sm">
                        <option>L</option>
                        <option>M</option>
                        <option>XL</option>
                      </select>
                    </div>
                    <div class="pull-left">
                      <label class="control-label">Color:</label>
                      <select class="form-control input-sm">
                        <option>Red</option>
                        <option>Blue</option>
                        <option>Black</option>
                      </select>
                    </div>
                  </div>
                  <div class="product-page-cart">
                    <div class="product-quantity">
                        <input id="product-quantity3" type="text" value="1" readonly class="form-control input-sm">
                    </div>
                    <button class="btn btn-primary" type="submit">Add to cart</button>
                    <a href="shop-item.html" class="btn btn-default">More details</a>
                  </div>
                </div>

                <div class="sticker sticker-sale"></div>
              </div>
            </div>
    </div>
    <!-- END fast view of a product -->

    <!-- Load javascripts at bottom, this will reduce page load time -->
    <!-- BEGIN CORE PLUGINS (REQUIRED FOR ALL PAGES) -->
    <!--[if lt IE 9]>
    <script src="/shop/assets/plugins/respond.min.js"></script>
    <![endif]-->  
    <script src="/shop/assets/plugins/jquery.min.js" type="text/javascript"></script>
    <script src="/shop/assets/plugins/jquery-migrate.min.js" type="text/javascript"></script>
    <script src="/shop/assets/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="/shop/assets/corporate/scripts/back-to-top.js" type="text/javascript"></script>
    <script src="/shop/assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <!-- END CORE PLUGINS -->

    <!-- BEGIN PAGE LEVEL JAVASCRIPTS (REQUIRED ONLY FOR CURRENT PAGE) -->
    <script src="/shop/assets/plugins/fancybox/source/jquery.fancybox.pack.js" type="text/javascript"></script><!-- pop up -->
    <script src="/shop/assets/plugins/owl.carousel/owl.carousel.min.js" type="text/javascript"></script><!-- slider for products -->
    <script src='/shop/assets/plugins/zoom/jquery.zoom.min.js' type="text/javascript"></script><!-- product zoom -->
    <script src="/shop/assets/plugins/bootstrap-touchspin/bootstrap.touchspin.js" type="text/javascript"></script><!-- Quantity -->
    <script src="/shop/assets/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
    <script src="/shop/assets/plugins/rateit/src/jquery.rateit.js" type="text/javascript"></script>
    <script src="/shop/assets/plugins/jquery-ui.js" type="text/javascript"></script><!-- for slider-range -->

    <script src="/shop/assets/corporate/scripts/layout.js" type="text/javascript"></script>
    <script type="text/javascript">
 				var postData = [];
 				var data_common = [];
 				var data_product = [];
 				var total_price = 0;
        jQuery(document).ready(function() {
        	$.ajax({
	        		type:"post",
	        		url:"/buycar/getList",
	        		async:true,
	        		dataType:'json',
	        		data:{
	        			'aaa': '1'
	        		},
	        		success:function(result){
	        			console.log(result.auth)
	        			$("#table-buycar tbody").html('');
	        			var htmls = '';
	        			for(var i in result.auth){
	        				htmls += 
	        					'<tr>'+
		        					'<td class="goods-page-image">'+
	                      '<a href="javascript:;"><img src="/shop/assets/pages/img/products/model3.jpg" alt="Berry Lace Dress"></a>'+
	                    '</td>'+
	                    '<td class="goods-page-description">'+
	                      '<h3><a href="javascript:;">'+result.auth[i].product_name+''+
//	                      '<p><strong>Item 1</strong> - Color: Green; Size: S</p>'+
//	                      '<em>More info is here</em>'+
	                    '</td>'+
	                    '<td class="goods-page-color">'+
	                      result.auth[i].color_name+
	                    '</td>'+
	                    '<td class="goods-page-size">'+
	                      result.auth[i].size_name+
	                    '</td>'+
	                    '<td class="goods-page-quantity">'+
	                      '<div class="product-quantity">'+
	                          '<input id="product-quantity" type="text" value="'+result.auth[i].number+'" readonly class="form-control input-sm">'+
	                      '</div>'+
	                    '</td>'+
	                    '<td class="goods-page-price">'+
	                      '<strong><span>$</span>'+result.auth[i].price+'</strong>'+
	                    '</td>'+
	                    '<td class="goods-page-total">'+
	                      '<strong><span>$</span>'+result.auth[0].total_price+'</strong>'+
	                    '</td>'+
	                    '<td class="del-goods-col">'+
	                      '<a class="del-goods" href="javascript:;">&nbsp;</a>'+
	                    '</td>'+
	                  '</tr>'
	                  
	                  var temp_data = {};
	                  temp_data['product_id'] = result.auth[i].product_id;
	                  temp_data['product_name'] = result.auth[i].product_name;
	                  temp_data['picture'] =  result.auth[i].picture;
	                  temp_data['color_id'] =  result.auth[i].color_id;
	                  temp_data['color_name'] =  result.auth[i].color_name;
	                  temp_data['size_id'] =  result.auth[i].size_id;
	                  temp_data['size_name'] =  result.auth[i].size_name;
	                  temp_data['number'] =  result.auth[i].number;
	                  temp_data['price'] =  result.auth[i].price;
	                  temp_data['total_price'] =  result.auth[i].total_price;
	                  postData.push(temp_data);
	                  total_price = result.auth[0].totalprice;
	                  
	        			}
	        			postData[0]['total_price'] = total_price;
	        			postData[0]['final_price'] = total_price;
	        			
	        			$("#table-buycar tbody").html(htmls);
	        			$("#price-1").html('<span>$</span>'+total_price);
	        			$("#price-2").html('<span>$</span>'+Number(0).toFixed(2));
	        			$("#price-3").html('<span>$</span>'+total_price);
	        		}
        	});
        		Layout.init();    
            Layout.initOWL();
//          Layout.initTwitter();
            Layout.initImageZoom();
            Layout.initTouchspin();
        });
     	$("#btn-checkout").click(function(){
     		$.ajax({
	        		type:"post",
	        		url:"/order/addOrder",
	        		async:true,
	        		dataType:'json',
	        		data:{
	        			'data':postData
	        		},
	        		success:function(result){
	        			if(result.auth){
	        				location.href = "/order/index"
	        			}else{
	        				
	        			}
	        		}
	       });
	       
     	})
    </script>
    <!-- END PAGE LEVEL JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>