<script src="/js/asa.js"></script>
<div id="ell">
<simple-admin-page v-bind="props" ref="page"></simple-admin-page>
</div>

<script>
$(document).ready(function(){
    var props = {
        data: <?=json_encode($result)?>,
        columns:[
            {name:"name", label:"姓名", is_create:true, is_update:true, is_show:true, width:400},
            {name:"code", label:"地址", is_create:true, is_update:true, is_show:true, width:400},
            {name:"date", label:"生日", is_create:true, is_update:true, is_show:true},
            {name:"brandid", label:"品牌", is_create:false, is_update:false, is_show:false, is_hidden:true}
        ],
        buttons:{
            "create":{
                label:"创建"    
            },
            "save":{
                label:"保存"    
            },
            "remove":{
                label:"删除"    
            },
            "edit":{
                label:"编辑"    
            } 
        },
        labels:{
            formTitleCreate:"添加信息",
            formTitleUpdate:"编辑信息",
            action:"操作"    
        },
        options:{
            dialogWidth:"35%",
            parent_id:"brandid",
            parent_id_value:10
        },
        controller:"aliases"
    }
    
    new Vue({
        el:"#ell",
        data() {
            return {
                props:props   
            }
        },
        methods: {
        }
    })
})
</script>
<style>
</style>

