<div id="ell">
<multiple-admin-page v-bind="props" ref="page"></multiple-admin-page>
</div>

<script>
$(document).ready(function(){
    var props = {
        columns:[
            {name:"content", label:"<?=$system_language['caizhibeizhu']?>", is_multiple:true, is_focus:true}
        ],
        controller:"materialnote",
        key_column:"content"
    }
    
    new Vue({
        el:"#ell",
        data() {
            return {
                props:props   
            }
        }
    })
})
</script>
<style>
</style>

