<!-- BEGIN FOOTER -->
<div class="footer">
    <div class="container">
        <div class="row">
            <!-- BEGIN COPYRIGHT -->
            <div class="col-md-12 col-sm-12 text-center">
                2019 © ASA ALL Rights Reserved
            </div>
            <!-- END COPYRIGHT -->
        </div>
    </div>
</div>
<!-- END FOOTER -->

<!-- Load javascripts at bottom, this will reduce page load time -->
<!-- BEGIN CORE PLUGINS(REQUIRED FOR ALL PAGES) -->
<!--[if lt IE 9]>
<script src="/shop/assets/plugins/respond.min.js"></script>
<![endif]-->
<script src="/shop/assets/plugins/jquery.min.js" type="text/javascript"></script>
<script src="/shop/assets/plugins/jquery-migrate.min.js" type="text/javascript"></script>
<script src="/shop/assets/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/shop/assets/corporate/scripts/back-to-top.js" type="text/javascript"></script>
<script src="/shop/assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<!-- END CORE PLUGINS -->

<!-- BEGIN PAGE LEVEL JAVASCRIPTS (REQUIRED ONLY FOR CURRENT PAGE) -->
<script src="/shop/assets/plugins/fancybox/source/jquery.fancybox.pack.js" type="text/javascript"></script><!-- pop up -->
<script src="/shop/assets/plugins/owl.carousel/owl.carousel.min.js" type="text/javascript"></script><!-- slider for products -->
<script src='/shop/assets/plugins/zoom/jquery.zoom.min.js' type="text/javascript"></script><!-- product zoom -->
<script src="/shop/assets/plugins/bootstrap-touchspin/bootstrap.touchspin.js" type="text/javascript"></script><!-- Quantity -->
<script src="/shop/assets/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
<script src="/shop/assets/plugins/rateit/src/jquery.rateit.js" type="text/javascript"></script>

<script src="/shop/assets/corporate/scripts/layout.js" type="text/javascript"></script>
<script src="/shop/assets/script.js" type="text/javascript" ></script>
<!-- END PAGE LEVEL JAVASCRIPTS -->


