<!-- BEGIN TOP BAR -->
<div class="pre-header">
    <div class="container">
        <div class="row">
            <!-- BEGIN TOP BAR LEFT PART -->
            <div class="col-md-6 col-sm-6 additional-shop-info">
                <ul class="list-unstyled list-inline">
                    <li><i class="fa fa-phone"></i><span><?php if ($this->session->get('member')) {
                                echo $this->session->get('member')['phoneno'];
                            } ?></span></li>
                    <!-- BEGIN LANGS -->
                    <!--                    <li class="langs-block">-->
                    <!--                        <a href="javascript:void(0);" class="current">English </a>-->
                    <!--                        <div class="langs-block-others-wrapper">-->
                    <!--                            <div class="langs-block-others">-->
                    <!--                                <a href="javascript:void(0);">French</a>-->
                    <!--                                <a href="javascript:void(0);">Germany</a>-->
                    <!--                                <a href="javascript:void(0);">Turkish</a>-->
                    <!--                            </div>-->
                    <!--                        </div>-->
                    <!--                    </li>-->
                    <!-- END LANGS -->
                </ul>
            </div>
            <!-- END TOP BAR LEFT PART -->
            <!-- BEGIN TOP BAR MENU -->
            <div class="col-md-6 col-sm-6 additional-nav">
                <ul class="list-unstyled list-inline pull-right">
                    <li><?php if ($this->session->get('member')) {
                            echo $this->obj->getValidateMessage('welcome') . ' ' . $this->session->get('member')['name'];
                        } ?></li>
                    <li><a href="/member"><?php echo $this->obj->getValidateMessage('jibenziliao'); ?></a></li>

                    <li><a href="/buycar"><?php echo $this->obj->getValidateMessage('buycar'); ?></a></li>
                    <li><a href="/order/list"><?php echo $this->obj->getValidateMessage('my-order'); ?></a></li>

                    <li <?php if ($this->session->get('member')) {
                        echo "style='display:none;'";
                    } ?>><a href="/login/index"><?php echo $this->obj->getValidateMessage('denglu'); ?></a></li>
                    <li <?php if (!$this->session->get('member')) {
                        echo "style='display:none;'";
                    } ?>><a href="/login/logout"><?php echo $this->obj->getValidateMessage('tuichu'); ?></a></li>
                </ul>
            </div>
            <!-- END TOP BAR MENU -->
        </div>
    </div>
</div>
<!-- END TOP BAR -->

<!-- BEGIN HEADER -->
<div class="header">
    <div class="container">
        <!--<a class="site-logo" href="shop-index.html"><img src="/shop/assets/corporate/img/logos/logo-shop-red.png" alt="Metronic Shop UI"></a>-->
        <a class="site-logo" href="/">ASA</a>

        <a href="javascript:void(0);" class="mobi-toggler"><i class="fa fa-bars"></i></a>

        <!-- BEGIN CART -->
        <div class="top-cart-block">
            <div class="top-cart-info">
                <a href="javascript:void(0);"
                   class="top-cart-info-count"><?php echo $this->buycar['total']['totalnum']; ?></a>
                <a href="javascript:void(0);"
                   class="top-cart-info-value"><?php if ($this->buycar['total']['totalnum'] && $this->buycar['total']['totalprice']) echo '| $' . $this->buycar['total']['totalprice']; ?></a>
            </div>
            <i class="fa fa-shopping-cart"></i>

            <div class="top-cart-content-wrapper">
                <div class="top-cart-content">
                    <ul class="scroller" style="height: 250px;">
                        <?php if ($this->buycar) { ?>
                            <?php foreach ($this->buycar['items'] as $k => $v) { ?>
                                <li class="buycar-list">
                                    <a href="/"><img src="<?php echo $this->file_prex . $v['product']['picture']; ?>"
                                                     alt="<?php echo $v['product_name'] ?>" width="37" height="34"></a>
                                    <span class="cart-content-count">x <?php echo $v['number']; ?></span>
                                    <strong><a href="/"><?php echo $v['product']['productname']; ?></a></strong>
                                    <em>$<?php echo sprintf('%.2f', $v['price']); ?></em>
                                    <a onclick="delheadergoods(this, <?php echo $v['id']; ?>);"
                                       class="del-goods">&nbsp;</a>
                                </li>
                            <?php } ?>
                        <?php } else { ?>
                            <li><?php echo $this->obj->getValidateMessage('buycar-empty'); ?></li>
                        <?php } ?>
                    </ul>
                    <div class="text-right">
                        <a href="/buycar"
                           class="btn btn-primary"><?php echo $this->obj->getValidateMessage('view-buycar'); ?></a>
                    </div>
                </div>
            </div>
        </div>
        <!--END CART -->

        <!-- BEGIN NAVIGATION -->
        <div class="header-navigation">

            <ul class="menu">

                <li class="dropdown">
                    <a href="javascript:void(0);"
                       class="text-muted dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                       aria-expanded="false"><?php echo $this->language['list']['gender']['1']; ?></a>


                    <ul class="dropdown-menu">
                        <li>
                            <div class="header-navigation-content">
                                <div class="row">
                                    <div class="col-md-12 header-navigation-col">
                                        <h4><?php echo $this->obj->getValidateMessage('pinlei'); ?></h4>
                                        <ul>
                                            <?php foreach ($this->girlbrandgroups as $cate) { ?>
                                                <li>
                                                    <a href="/brandgroup/detail/<?php echo $cate['id']; ?>"><?php echo $cate['name']; ?></a>
                                                </li>
                                            <?php } ?>
                                        </ul>
                                    </div>
                                    <div class="col-md-12 nav-brands">
                                        <h4><?php echo $this->obj->getValidateMessage('pinpai'); ?></h4>
                                        <ul>
                                            <?php foreach ($this->girlbrands as $brand) { ?>
                                                <li>
                                                    <a href="/brand/detail/<?php echo $brand['id']; ?>"><?php echo $brand['name']; ?></a>
                                                </li>
                                            <?php } ?>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>


                </li>


                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" data-target="#"
                       href="javascript:;"><?php echo $this->language['list']['gender']['2']; ?></a>

                    <ul class="dropdown-menu">
                        <li>
                            <div class="header-navigation-content">
                                <div class="row">
                                    <div class="col-md-12 header-navigation-col">
                                        <h4><?php echo $this->obj->getValidateMessage('pinlei'); ?></h4>
                                        <ul>
                                            <?php foreach ($this->boybrandgroups as $cate) { ?>
                                                <li>
                                                    <a href="/brandgroup/detail/<?php echo $cate['id']; ?>"><?php echo $cate['name']; ?></a>
                                                </li>
                                            <?php } ?>
                                        </ul>
                                    </div>
                                    <div class="col-md-12 nav-brands">
                                        <h4><?php echo $this->obj->getValidateMessage('pinpai'); ?></h4>
                                        <ul>
                                            <?php foreach ($this->boybrands as $brand) { ?>
                                                <li>
                                                    <a href="/brand/detail/<?php echo $brand['id']; ?>"><?php echo $brand['name']; ?></a>
                                                </li>
                                            <?php } ?>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>

                </li>


                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" data-target="#"
                       href="javascript:;"><?php echo $this->language['list']['gender']['6']; ?></a>


                    <ul class="dropdown-menu">
                        <li>
                            <div class="header-navigation-content">
                                <div class="row">
                                    <div class="col-md-12 header-navigation-col">
                                        <h4><?php echo $this->obj->getValidateMessage('pinlei'); ?></h4>
                                        <ul>
                                            <?php foreach ($this->childbrandgroups as $cate) { ?>
                                                <li>
                                                    <a href="/brandgroup/detail/<?php echo $cate['id']; ?>"><?php echo $cate['name']; ?></a>
                                                </li>
                                            <?php } ?>
                                        </ul>
                                    </div>
                                    <div class="col-md-12 nav-brands">
                                        <h4><?php echo $this->obj->getValidateMessage('pinpai'); ?></h4>
                                        <ul>
                                            <?php foreach ($this->childbrands as $brand) { ?>
                                                <li>
                                                    <a href="/brand/detail/<?php echo $brand['id']; ?>"><?php echo $brand['name']; ?></a>
                                                </li>
                                            <?php } ?>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>


                </li>

                <!-- BEGIN TOP SEARCH -->
                <li class="menu-search" style="float: right;">
                    <span class="sep"></span>
                    <i class="fa fa-search search-btn"></i>
                    <div class="search-box">
                        <form action="/index/search">
                            <div class="input-group">
                                <input type="text" placeholder="<?php echo $this->obj->getValidateMessage('search'); ?>"
                                       class="form-control" name="keyword">
                                <span class="input-group-btn">
                                <button class="btn btn-primary"
                                        type="submit"><?php echo $this->obj->getValidateMessage('search'); ?></button>
                            </span>
                            </div>
                        </form>
                    </div>
                </li>
                <!-- END TOP SEARCH -->
            </ul>

        </div>

    </div>
    <!-- END NAVIGATION -->
</div>
<!-- Header END -->

