<meta content="width=device-width, initial-scale=1.0" name="viewport">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

<meta content="Metronic Shop UI description" name="description">
<meta content="Metronic Shop UI keywords" name="keywords">
<meta content="keenthemes" name="author">

<link rel="shortcut icon" href="favicon.ico">

<!-- START PAGE LEVEL CSS -->
<link href="/shop/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
<?php $this->assets->outputCss("header"); ?>
<!-- END PAGE LEVEL CSS -->
