<meta content="width=device-width, initial-scale=1.0" name="viewport">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

<meta content="Metronic Shop UI description" name="description">
<meta content="Metronic Shop UI keywords" name="keywords">
<meta content="keenthemes" name="author">

<link rel="shortcut icon" href="favicon.ico">

<!-- Global styles START -->
<link href="/shop/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
<link href="/shop/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<!-- Global styles END -->

<!-- Page level plugin styles START -->
<link href="/shop/assets/pages/css/animate.css" rel="stylesheet">
<link href="/shop/assets/plugins/fancybox/source/jquery.fancybox.css" rel="stylesheet">
<link href="/shop/assets/plugins/owl.carousel/assets/owl.carousel.css" rel="stylesheet">
<!-- Page level plugin styles END -->

<!-- Theme styles START -->
<link href="/shop/assets/pages/css/components.css" rel="stylesheet">
<link href="/shop/assets/pages/css/slider.css" rel="stylesheet">
<link href="/shop/assets/pages/css/style-shop.css" rel="stylesheet" type="text/css">
<link href="/shop/assets/corporate/css/style.css" rel="stylesheet">
<link href="/shop/assets/corporate/css/style-responsive.css" rel="stylesheet">
<link href="/shop/assets/corporate/css/themes/red.css" rel="stylesheet" id="style-color">
<link rel="stylesheet" href="/shop/assets/static/css/bootstrap-submenu.css">
<link href="/shop/assets/corporate/css/custom.css" rel="stylesheet">
<!-- Theme styles END -->
