<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="icon" href="/favicon.ico">
    <title>后台模板</title>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>

    <!-- 引入样式 -->
    <link rel="stylesheet" href="https://unpkg.com/element-ui/lib/theme-chalk/index.css">
    <!-- 引入组件库 -->
    <script src="https://unpkg.com/element-ui/lib/index.js"></script>
    <script src="/js/jquery.min.js"></script>
  </head>

  <style>
  .el-row {
    margin-bottom: 20px;
    &:last-child {
      margin-bottom: 0;
    }
  }

  .bg-purple-dark {
    background: #99a9bf;
  }
  .bg-purple {
    background: #d3dce6;
  }
  .bg-purple-light {
    background: #e5e9f2;
  }
  .grid-content {
    border-radius: 4px;
    min-height: 36px;
  }
  .row-bg {
    padding: 10px 0;
    background-color: #f9fafc;
  }
  
  .el-menu-item a {
    color:white;
    text-decoration : none  
  }
  
  #ell{margin:5px;}
</style>
  <body>
  <div id="app">
    <section class="el-container is-vertical" style="height: auto; border: 1px solid rgb(238, 238, 238);">
        <header class="el-header" style="height: 60px; text-align: left; font-size: 24px;">ERP管理系统</header>
        <div id="top-menu">
            <el-menu class="el-menu-demo" mode="horizontal" background-color="#545c64" text-color="#fff" active-text-color="#ffd04b">
              <el-submenu index="1">
                <template #title><?=$system_language['menu-1']?></template>
                <el-menu-item index="1-1">员工信息</el-menu-item>
                <el-menu-item index="1-2">组信息</el-menu-item>
                <el-menu-item index="1-3">职能信息</el-menu-item>
                <el-submenu index="2-4">
                  <template #title>部门信息</template>
                  <el-menu-item index="2-4-1">选项1</el-menu-item>
                  <el-menu-item index="2-4-2">选项2</el-menu-item>
                  <el-menu-item index="2-4-3">选项3</el-menu-item>
                </el-submenu>
              </el-submenu>
              <el-submenu index="2">
                <template #title>基础数据</template>
                <el-submenu index="2-1">
                  <template #title>商品相关</template>
                  <el-menu-item index="2-1-1">品牌维护</el-menu-item>
                 <el-menu-item index="2-1-2">品类维护</el-menu-item>
                 <el-menu-item index="2-1-3">款式年代</el-menu-item>
                 <el-menu-item index="2-1-4">颜色模板</el-menu-item>
                 <el-menu-item index="2-1-5">商品尺码</el-menu-item>
                 <el-menu-item index="2-1-6">材质管理</el-menu-item>
                 <el-menu-item index="2-1-7">商品尺寸</el-menu-item>
                 <el-menu-item index="2-1-8">商品别名</el-menu-item>
                 <el-menu-item index="2-1-9">内部结构</el-menu-item>
                 <el-menu-item index="2-1-10">附带配件</el-menu-item>
                 <el-menu-item index="2-1-11">场合风格</el-menu-item>
                 <el-menu-item index="2-1-12">闭合方式</el-menu-item>
                 <el-menu-item index="2-1-13">执行标准</el-menu-item>
                 <el-menu-item index="2-1-14">安全类别</el-menu-item>
                 <el-menu-item index="2-1-15">洗涤说明</el-menu-item>
                 <el-menu-item index="2-1-16">防寒指数</el-menu-item>
                </el-submenu>
                
                <el-submenu index="2-2">
                  <template #title>价格相关</template>
                  <el-menu-item index="2-2-1">商品价格管理</el-menu-item>
                  <el-menu-item index="2-2-2">成本计算管理</el-menu-item>
                </el-submenu>
                
                <el-submenu index="2-3">
                  <template #title>其他</template>
                  <el-menu-item index="2-3-1">仓库管理</el-menu-item>
                  <el-menu-item index="2-3-2">销售端口管理</el-menu-item>
                  <el-menu-item index="2-3-3">国际及地区信息维护</el-menu-item>
                  <el-menu-item index="2-3-4">费用名称</el-menu-item>
                  <el-menu-item index="2-3-5">运输方式</el-menu-item>
                  <el-menu-item index="2-3-6">销售性质</el-menu-item>
                  <el-menu-item index="2-3-7">业务类型</el-menu-item>
                  <el-menu-item index="2-3-8">打印机设置</el-menu-item>
                  <el-menu-item index="2-3-9">快递单样式</el-menu-item>
                  <el-menu-item index="2-3-10">图片工具</el-menu-item>
                  <el-menu-item index="2-3-11">价格来源</el-menu-item>
                  <el-menu-item index="2-3-12">报表模板</el-menu-item>
                  <el-menu-item index="2-3-13">接口代码对照</el-menu-item>
                </el-submenu>                
              </el-submenu>
              
              <el-submenu index="3">
                <template #title>商品管理</template>
                <el-menu-item index="3-1">商品信息</el-menu-item>
                <el-menu-item index="3-2">图片管理</el-menu-item>
                <el-menu-item index="3-3">图片上传</el-menu-item>
              </el-submenu>
              
              <el-submenu index="4">
                <template #title>客户管理</template>
                <el-menu-item index="4-1">关系单位信息</el-menu-item>
                <el-menu-item index="4-2">供货商报价</el-menu-item>
                <el-menu-item index="4-3">供货商级别</el-menu-item>
              </el-submenu>
              
              <el-submenu index="5">
                <template #title>供应链管理</template>
                <el-submenu index="5-1">
                  <template #title>订单管理</template>
                  <el-menu-item index="5-1-1">订单管理</el-menu-item>
                  <el-menu-item index="5-1-2">订单状态查询</el-menu-item>
                  <el-menu-item index="5-1-3">订单导出</el-menu-item>
                </el-submenu>
                <el-menu-item index="5-2">发货单管理</el-menu-item>
                
                <el-submenu index="5-3">
                  <template #title>到货入库</template>
                  <el-menu-item index="5-3-1">到货入库</el-menu-item>
                  <el-menu-item index="5-3-2">入库单查询</el-menu-item>
                </el-submenu>
              </el-submenu>
              
              <el-submenu index="6">
                <template #title>库存管理</template>
                <el-menu-item index="2-1">选项1</el-menu-item>
                <el-menu-item index="2-2">选项2</el-menu-item>
                <el-menu-item index="2-3">选项3</el-menu-item>
                <el-submenu index="2-4">
                  <template #title>选项4</template>
                  <el-menu-item index="2-4-1">选项1</el-menu-item>
                  <el-menu-item index="2-4-2">选项2</el-menu-item>
                  <el-menu-item index="2-4-3">选项3</el-menu-item>
                </el-submenu>
              </el-submenu>
              
              <el-submenu index="7">
                <template #title>销售管理</template>
                <el-menu-item index="2-1">选项1</el-menu-item>
                <el-menu-item index="2-2">选项2</el-menu-item>
                <el-menu-item index="2-3">选项3</el-menu-item>
                <el-submenu index="2-4">
                  <template #title>选项4</template>
                  <el-menu-item index="2-4-1">选项1</el-menu-item>
                  <el-menu-item index="2-4-2">选项2</el-menu-item>
                  <el-menu-item index="2-4-3">选项3</el-menu-item>
                </el-submenu>
              </el-submenu>
              
              <el-submenu index="8">
                <template #title>会员管理</template>
                <el-menu-item index="2-1">选项1</el-menu-item>
                <el-menu-item index="2-2">选项2</el-menu-item>
                <el-menu-item index="2-3">选项3</el-menu-item>
                <el-submenu index="2-4">
                  <template #title>选项4</template>
                  <el-menu-item index="2-4-1">选项1</el-menu-item>
                  <el-menu-item index="2-4-2">选项2</el-menu-item>
                  <el-menu-item index="2-4-3">选项3</el-menu-item>
                </el-submenu>
              </el-submenu>
              
              <el-submenu index="9">
                <template #title>费用管理</template>
                <el-menu-item index="2-1">选项1</el-menu-item>
                <el-menu-item index="2-2">选项2</el-menu-item>
                <el-menu-item index="2-3">选项3</el-menu-item>
                <el-submenu index="2-4">
                  <template #title>选项4</template>
                  <el-menu-item index="2-4-1">选项1</el-menu-item>
                  <el-menu-item index="2-4-2">选项2</el-menu-item>
                  <el-menu-item index="2-4-3">选项3</el-menu-item>
                </el-submenu>
              </el-submenu>
              
              <el-submenu index="10">
                <template #title>财务管理</template>
                <el-menu-item index="2-1">选项1</el-menu-item>
                <el-menu-item index="2-2">选项2</el-menu-item>
                <el-menu-item index="2-3">选项3</el-menu-item>
                <el-submenu index="2-4">
                  <template #title>选项4</template>
                  <el-menu-item index="2-4-1">选项1</el-menu-item>
                  <el-menu-item index="2-4-2">选项2</el-menu-item>
                  <el-menu-item index="2-4-3">选项3</el-menu-item>
                </el-submenu>
              </el-submenu>              
              
              <el-submenu index="11">
                <template #title>系统</template>
                <el-menu-item index="11-1">系统帮助</el-menu-item>
                <!--<el-menu-item index="11-2">联系客服</el-menu-item>-->
                <el-menu-item index="11-3"><a href="/user/modifypassowrd">修改密码</a></el-menu-item>
                <el-menu-item index="11-4">退出</el-menu-item>                
              </el-submenu>
            </el-menu>
        </div>
        <section class="el-container">
            <?php echo $this->getContent(); ?>
        </section>
        
        <div id="footer">
        <el-footer class="el-footer"></el-footer>
        </div>
    </section>
  </div>
<style>
  .el-header {
    background-color: #B3C0D1;
    color: #333;
    line-height: 60px;
  }
  
  .el-footer{
    clear: both;
    display: block;
    text-align: center;    
    margin: 0px auto;
    bottom: 100px;
  }

  .el-aside {
    color: #333;
  }
</style>
<script>
$(document).ready(function(){
    new Vue({
        el:"#top-menu",
        data() {
            return {

            }
        }
    })
    
    new Vue({
        el:"#footer",
        data() {
            return {

            }
        }
    })
})
</script>
  </body>
</html>
