<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="icon" href="/favicon.ico">
    <title>后台模板</title>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>

    <!-- 引入样式 -->
    <link rel="stylesheet" href="https://unpkg.com/element-ui/lib/theme-chalk/index.css">
    <!-- 引入组件库 -->
    <script src="https://unpkg.com/element-ui/lib/index.js"></script>
    <script src="/js/jquery.min.js"></script>
  </head>

  <style>
  .el-row {
    margin-bottom: 20px;
    &:last-child {
      margin-bottom: 0;
    }
  }

  .bg-purple-dark {
    background: #99a9bf;
  }
  .bg-purple {
    background: #d3dce6;
  }
  .bg-purple-light {
    background: #e5e9f2;
  }
  .grid-content {
    border-radius: 4px;
    min-height: 36px;
  }
  .row-bg {
    padding: 10px 0;
    background-color: #f9fafc;
  }
  
  .el-menu-item a {
    color:white;
    text-decoration : none  
  }
  
  #ell{margin:5px;}
</style>
  <body>
  <div id="app">
    <section class="el-container is-vertical" style="height: auto; border: 1px solid rgb(238, 238, 238);">
        <header class="el-header" style="height: 60px; text-align: left; font-size: 24px;"><?=$system_language['system_name']?></header>
        <div id="top-menu">
            <el-menu class="el-menu-demo" mode="horizontal" background-color="#545c64" text-color="#fff" active-text-color="#ffd04b">
              <el-submenu index="1">
                <template #title><?=$system_language['menu-1']?></template>
                <el-menu-item index="1-1"><?=$system_language["menu-1-1"]?></el-menu-item>
                <el-menu-item index="1-2"><?=$system_language["menu-1-2"]?></el-menu-item>
                <el-menu-item index="1-3"><?=$system_language["menu-1-3"]?></el-menu-item>
                <el-menu-item index="1-4"><a href="/depart"><?=$system_language["menu-1-4"]?></a></el-menu-item>
              </el-submenu>
              <el-submenu index="2">
                <template #title><?=$system_language["menu-2"]?></template>
                <el-submenu index="2-1">
                  <template #title><?=$system_language["menu-2-1"]?></template>
                  <el-menu-item index="2-1-1"><?=$system_language["menu-2-1-1"]?></el-menu-item>
                  <el-menu-item index="2-1-2"><?=$system_language["menu-2-1-2"]?></el-menu-item>
                  <el-menu-item index="2-1-3"><?=$system_language["menu-2-1-3"]?></el-menu-item>
                  <el-menu-item index="2-1-4"><?=$system_language["menu-2-1-4"]?></el-menu-item>
                  <el-menu-item index="2-1-5"><?=$system_language["menu-2-1-5"]?></el-menu-item>
                  <el-menu-item index="2-1-6"><?=$system_language["menu-2-1-6"]?></el-menu-item>
                  <el-menu-item index="2-1-7"><?=$system_language["menu-2-1-7"]?></el-menu-item>
                  <el-menu-item index="2-1-8"><?=$system_language["menu-2-1-8"]?></el-menu-item>
                  <el-menu-item index="2-1-9"><?=$system_language["menu-2-1-9"]?></el-menu-item>
                  <el-menu-item index="2-1-10"><?=$system_language["menu-2-1-10"]?></el-menu-item>
                  <el-menu-item index="2-1-11"><?=$system_language["menu-2-1-11"]?></el-menu-item>
                  <el-menu-item index="2-1-12"><?=$system_language["menu-2-1-12"]?></el-menu-item>
                  <el-menu-item index="2-1-13"><?=$system_language["menu-2-1-13"]?></el-menu-item>
                  <el-menu-item index="2-1-14"><?=$system_language["menu-2-1-14"]?></el-menu-item>
                  <el-menu-item index="2-1-15"><?=$system_language["menu-2-1-15"]?></el-menu-item>
                  <el-menu-item index="2-1-16"><?=$system_language["menu-2-1-16"]?></el-menu-item>
                </el-submenu>
                
                <el-submenu index="2-2">
                  <template #title><?=$system_language["menu-2-2"]?></template>
                  <el-menu-item index="2-2-1"><?=$system_language["menu-2-2-1"]?></el-menu-item>
                  <el-menu-item index="2-2-2"><?=$system_language["menu-2-2-2"]?></el-menu-item>
                </el-submenu>
                
                <el-submenu index="2-3">
                  <template #title><?=$system_language["menu-2-3"]?></template>
                  <el-menu-item index="2-3-1"><?=$system_language["menu-2-3-1"]?></el-menu-item>
                  <el-menu-item index="2-3-2"><?=$system_language["menu-2-3-2"]?></el-menu-item>
                  <el-menu-item index="2-3-3"><?=$system_language["menu-2-3-3"]?></el-menu-item>
                  <el-menu-item index="2-3-4"><?=$system_language["menu-2-3-4"]?></el-menu-item>
                  <el-menu-item index="2-3-5"><?=$system_language["menu-2-3-5"]?></el-menu-item>
                  <el-menu-item index="2-3-6"><?=$system_language["menu-2-3-6"]?></el-menu-item>
                  <el-menu-item index="2-3-7"><?=$system_language["menu-2-3-7"]?></el-menu-item>
                  <el-menu-item index="2-3-8"><?=$system_language["menu-2-3-8"]?></el-menu-item>
                  <el-menu-item index="2-3-9"><?=$system_language["menu-2-3-9"]?></el-menu-item>
                  <el-menu-item index="2-3-10"><?=$system_language["menu-2-3-10"]?></el-menu-item>
                  <el-menu-item index="2-3-11"><?=$system_language["menu-2-3-11"]?></el-menu-item>
                  <el-menu-item index="2-3-12"><?=$system_language["menu-2-3-12"]?></el-menu-item>
                  <el-menu-item index="2-3-13"><?=$system_language["menu-2-3-13"]?></el-menu-item>
                </el-submenu>                
              </el-submenu>
              
              <el-submenu index="3">
                <template #title><?=$system_language["menu-3"]?></template>
                <el-menu-item index="3-1"><?=$system_language["menu-3-1"]?></el-menu-item>
                <el-menu-item index="3-2"><?=$system_language["menu-3-2"]?></el-menu-item>
                <el-menu-item index="3-3"><?=$system_language["menu-3-3"]?></el-menu-item>
              </el-submenu>
              
              <el-submenu index="4">
                <template #title><?=$system_language["menu-4"]?></template>
                <el-menu-item index="4-1"><?=$system_language["menu-4-1"]?></el-menu-item>
                <el-menu-item index="4-2"><?=$system_language["menu-4-2"]?></el-menu-item>
                <el-menu-item index="4-3"><?=$system_language["menu-4-3"]?></el-menu-item>
              </el-submenu>
              
              <el-submenu index="5">
                <template #title><?=$system_language["menu-5"]?></template>
                <el-submenu index="5-1">
                  <template #title><?=$system_language["menu-5-1"]?></template>
                  <el-menu-item index="5-1-1"><?=$system_language["menu-5-1-1"]?></el-menu-item>
                  <el-menu-item index="5-1-2"><?=$system_language["menu-5-1-2"]?></el-menu-item>
                  <el-menu-item index="5-1-3"><?=$system_language["menu-5-1-3"]?></el-menu-item>
                </el-submenu>
                <el-menu-item index="5-2"><?=$system_language["menu-5-2"]?></el-menu-item>
                
                <el-submenu index="5-3">
                  <template #title><?=$system_language["menu-5-3"]?></template>
                  <el-menu-item index="5-3-1"><?=$system_language["menu-5-3-1"]?></el-menu-item>
                  <el-menu-item index="5-3-2"><?=$system_language["menu-5-3-2"]?></el-menu-item>
                </el-submenu>
              </el-submenu>
              
              <el-submenu index="6">
                <template #title><?=$system_language["menu-6"]?></template>
                <el-submenu index="6-1">
                  <template #title><?=$system_language["menu-6-1"]?></template>
                  <el-menu-item index="6-1-1"><?=$system_language["menu-6-1-1"]?></el-menu-item>
                  <el-menu-item index="6-1-2"><?=$system_language["menu-6-1-2"]?></el-menu-item>
                  <el-menu-item index="6-1-3"><?=$system_language["menu-6-1-3"]?></el-menu-item>
                </el-submenu>
                <el-submenu index="6-2">
                  <template #title><?=$system_language["menu-6-2"]?></template>
                  <el-menu-item index="6-2-1"><?=$system_language["menu-6-2-1"]?></el-menu-item>
                  <el-menu-item index="6-2-2"><?=$system_language["menu-6-2-2"]?></el-menu-item>
                </el-submenu>
                <el-menu-item index="6-3"><?=$system_language["menu-6-3"]?></el-menu-item>
                <el-menu-item index="6-4"><?=$system_language["menu-6-4"]?></el-menu-item>
              </el-submenu>
              
              <el-submenu index="7">
                <template #title><?=$system_language["menu-7"]?></template>
                <el-menu-item index="7-1"><?=$system_language["menu-7-1"]?></el-menu-item>
                <el-menu-item index="7-2"><?=$system_language["menu-7-2"]?></el-menu-item>
                <el-menu-item index="7-3"><?=$system_language["menu-7-3"]?></el-menu-item>
                <el-submenu index="7-4">
                  <template #title><?=$system_language["menu-7-4"]?></template>
                  <el-menu-item index="7-4-1"><?=$system_language["menu-7-4-1"]?></el-menu-item>
                  <el-menu-item index="7-4-2"><?=$system_language["menu-7-4-2"]?></el-menu-item>
                </el-submenu>
                <el-menu-item index="7-5"><?=$system_language["menu-7-5"]?></el-menu-item>
              </el-submenu>
              
              <el-submenu index="8">
                <template #title><?=$system_language["menu-8"]?></template>
                <el-menu-item index="8-1"><?=$system_language["menu-8-1"]?></el-menu-item>
                <el-menu-item index="8-2"><?=$system_language["menu-8-2"]?></el-menu-item>
              </el-submenu>
              
              <el-submenu index="9">
                <template #title><?=$system_language["menu-9"]?></template>
                <el-menu-item index="9-1"><?=$system_language["menu-9-1"]?></el-menu-item>
                <el-menu-item index="9-2"><?=$system_language["menu-9-2"]?></el-menu-item>
                <el-menu-item index="9-3"><?=$system_language["menu-9-3"]?></el-menu-item>
                <el-menu-item index="9-3"><?=$system_language["menu-9-3"]?></el-menu-item>
              </el-submenu>
              
              <el-submenu index="10">
                <template #title><?=$system_language["menu-10"]?></template>
                <el-menu-item index="10-1"><?=$system_language["menu-10-1"]?></el-menu-item>
              </el-submenu>              
              
              <el-submenu index="11">
                <template #title><?=$system_language["menu-11"]?></template>
                <el-menu-item index="11-1"><?=$system_language["menu-11-1"]?></el-menu-item>
                <el-menu-item index="11-2"><a href="/user/modifypassowrd"><?=$system_language["menu-11-2"]?></a></el-menu-item>
                <el-menu-item index="11-3"><?=$system_language["menu-11-3"]?></el-menu-item>                
              </el-submenu>
            </el-menu>
        </div>
        <section class="el-container">
            <?php echo $this->getContent(); ?>
        </section>
        
        <div id="footer">
        <el-footer class="el-footer"></el-footer>
        </div>
    </section>
  </div>
<style>
  .el-header {
    background-color: #B3C0D1;
    color: #333;
    line-height: 60px;
  }
  
  .el-footer{
    clear: both;
    display: block;
    text-align: center;    
    margin: 0px auto;
    bottom: 100px;
  }

  .el-aside {
    color: #333;
  }
</style>
<script>
$(document).ready(function(){
    new Vue({
        el:"#top-menu",
        data() {
            return {

            }
        }
    })
    
    new Vue({
        el:"#footer",
        data() {
            return {

            }
        }
    })
})
</script>
  </body>
</html>
