<!DOCTYPE html>
<!-- 
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.2.0
Version: 3.3.0
Author: KeenThemes
Website: http://www.keenthemes.com/
Contact: support@keenthemes.com
Follow: www.twitter.com/keenthemes
Like: www.facebook.com/keenthemes
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
License: You must have a valid license purchased only from themeforest (the above link) in order to legally use the theme for your project.
-->
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->

<!-- Head BEGIN -->
<head>
  <meta charset="utf-8">
  <title>登录页</title>

  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <meta content="Metronic Shop UI description" name="description">
  <meta content="Metronic Shop UI keywords" name="keywords">
  <meta content="keenthemes" name="author">

  <meta property="og:site_name" content="-CUSTOMER VALUE-">
  <meta property="og:title" content="-CUSTOMER VALUE-">
  <meta property="og:description" content="-CUSTOMER VALUE-">
  <meta property="og:type" content="website">
  <meta property="og:image" content="-CUSTOMER VALUE-"><!-- link to image for socio -->
  <meta property="og:url" content="-CUSTOMER VALUE-">

  <link rel="shortcut icon" href="favicon.ico">

  <!-- Global styles START -->          
  <link href="/shop/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
  <link href="/shop/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <!-- Global styles END --> 
   
  <!-- Page level plugin styles START -->
  <link href="/shop/assets/plugins/fancybox/source/jquery.fancybox.css" rel="stylesheet">
  <link href="/shop/assets/plugins/owl.carousel//shop/assets/owl.carousel.css" rel="stylesheet">
  <link href="/shop/assets/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css">
  <link href="/shop/assets/plugins/themes/smoothness/jquery-ui.css" rel="stylesheet" type="text/css"><!-- for slider-range -->
  <link href="/shop/assets/plugins/rateit/src/rateit.css" rel="stylesheet" type="text/css">
  <!-- Page level plugin styles END -->

  <!-- Theme styles START -->
  <link href="/shop/assets/pages/css/components.css" rel="stylesheet">
  <link href="/shop/assets/corporate/css/style.css" rel="stylesheet">
  <link href="/shop/assets/pages/css/style-shop.css" rel="stylesheet" type="text/css">
  <link href="/shop/assets/corporate/css/style-responsive.css" rel="stylesheet">
  <link href="/shop/assets/corporate/css/themes/red.css" rel="stylesheet" id="style-color">
  <link href="/shop/assets/corporate/css/custom.css" rel="stylesheet">

  <!-- Theme styles END -->
</head>
<!-- Head END -->

<!-- Body BEGIN -->
<body class="corporate">
    <!-- BEGIN STYLE CUSTOMIZER -->
    <div class="color-panel hidden-sm">
      <div class="color-mode-icons icon-color"></div>
      <div class="color-mode-icons icon-color-close"></div>
      <div class="color-mode">
        <p>THEME COLOR</p>
        <ul class="inline">
          <li class="color-red current color-default" data-style="red"></li>
          <li class="color-blue" data-style="blue"></li>
          <li class="color-green" data-style="green"></li>
          <li class="color-orange" data-style="orange"></li>
          <li class="color-gray" data-style="gray"></li>
          <li class="color-turquoise" data-style="turquoise"></li>
        </ul>
      </div>
    </div>
    <!-- END BEGIN STYLE CUSTOMIZER --> 
    
    <!-- BEGIN TOP BAR -->
    <?php echo $this->view->getPartial('layouts/_header') ?>
    <!-- END TOP BAR -->
    <!-- BEGIN HEADER -->
    <!-- Header END -->

    <div class="main">
      <div class="container">
        <?php echo $this->view->getPartial('layouts/_sidebar') ?>
        <!-- BEGIN SIDEBAR & CONTENT -->
        
          <!-- END SIDEBAR -->

          <!-- BEGIN CONTENT -->
          <div class="col-md-9 col-sm-9">
            <h1>Login</h1>
            <div class="content-form-page">
              <div class="row">
                <div class="col-md-7 col-sm-7">
                  <form class="form-horizontal form-without-legend" role="form" action="" method="post">
                    <div class="form-group">
                      <label for="email" class="col-lg-4 control-label">用户名 <span class="require">*</span></label>
                      <div class="col-lg-8">
                        <input type="text" class="form-control" id="login_name" name="login_name">
                      </div>
                    </div>
                    <div class="form-group">
                      <label for="password" class="col-lg-4 control-label">密码 <span class="require">*</span></label>
                      <div class="col-lg-8">
                        <input type="password" class="form-control" id="password" name ="password">
                      </div>
                    </div>
<!--                    <div class="row">-->
<!--                      <div class="col-lg-8 col-md-offset-4 padding-left-0">-->
<!--                        <a href="page-forgotton-password.html">Forget Password?</a>-->
<!--                      </div>-->
<!--                    </div>-->
                    <div class="row">
                      <div class="col-lg-8 col-md-offset-4 padding-left-0 padding-top-20">
                        <button type="button" class="btn btn-primary" id="btn-login">登录</button>
                      </div>
                    </div>
<!--                    <div class="row">-->
<!--                      <div class="col-lg-8 col-md-offset-4 padding-left-0 padding-top-10 padding-right-30">-->
<!--                        <hr>-->
<!--                        <div class="login-socio">-->
<!--                            <p class="text-muted">or login using:</p>-->
<!--                            <ul class="social-icons">-->
<!--                                <li><a href="#" data-original-title="facebook" class="facebook" title="facebook"></a></li>-->
<!--                                <li><a href="#" data-original-title="Twitter" class="twitter" title="Twitter"></a></li>-->
<!--                                <li><a href="#" data-original-title="Google Plus" class="googleplus" title="Google Plus"></a></li>-->
<!--                                <li><a href="#" data-original-title="Linkedin" class="linkedin" title="LinkedIn"></a></li>-->
<!--                            </ul>-->
<!--                        </div>-->
<!--                      </div>-->
                    </div>
                  </form>
                </div>
<!--                <div class="col-md-4 col-sm-4 pull-right">-->
<!--                  <div class="form-info">-->
<!--                    <h2><em>Important</em> Information</h2>-->
<!--                    <p>Duis autem vel eum iriure at dolor vulputate velit esse vel molestie at dolore.</p>-->
<!---->
<!--                    <button type="submit" class="btn btn-default">More details</button>-->
<!--                  </div>-->
<!--                </div>-->
              </div>
            </div>
          </div>
          <!-- END CONTENT -->
        </div>
        <!-- END SIDEBAR & CONTENT -->
      </div>
    </div>

    <!-- BEGIN PRE-FOOTER -->
    <!-- END PRE-FOOTER -->
	
    <!-- BEGIN FOOTER -->
    <?php echo $this->view->getPartial('layouts/_footer'); ?>
    <!-- END FOOTER -->

    <!-- 加入layer实现简易弹窗 -->
    <script src="/shop/assets/static/js/layer_mobile/layer.js"></script>
    <script type="text/javascript">
        $("#btn-login").click(function(){
        	$.ajax({
        		type:"post",
        		url:"/login/login",
        		async:true,
        		dataType:'json',
        		data:{
        			'login_name' : $("#login_name").val(),
        			'password' : $("#password").val(),
        		},
        		success:function(result) {
        		    // 判断是否有错误
                    if(result.messages.length > 0) {
                        layer.open({
                            content: result.messages[0],
                            btn: '我知道了'
                        });
                    } else {
                        //提示
                        layer.open({
                            content: '登录成功',
                            skin: 'msg',
                            time: 2, //2秒后自动关闭
                        });
                        // 3秒后跳转
                        setTimeout(function() {
                            window.location.href = '/';
                        }, 3000);
                    }
        		}
        	});
            // 禁止自动跳转
            return false;
        });
    </script>
    <!-- END PAGE LEVEL JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>