<!DOCTYPE html>
<!--
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.2.0
Version: 3.3.0
Author: KeenThemes
Website: http://www.keenthemes.com/
Contact: support@keenthemes.com
Follow: www.twitter.com/keenthemes
Like: www.facebook.com/keenthemes
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
License: You must have a valid license purchased only from themeforest (the above link) in order to legally use the theme for your project.
-->
<!--[if IE 8]>
<html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]>
<html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->

<!-- Head BEGIN -->
<head>
    <meta charset="utf-8">
    <title><?php echo $this->obj->getValidateMessage('denglu'); ?>页</title>

    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <meta content="Metronic Shop UI description" name="description">
    <meta content="Metronic Shop UI keywords" name="keywords">
    <meta content="keenthemes" name="author">

    <link rel="shortcut icon" href="favicon.ico">

    <!-- Global styles START -->
    <link href="/shop/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="/shop/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Global styles END -->

    <!-- Page level plugin styles START -->
    <link href="/shop/assets/plugins/fancybox/source/jquery.fancybox.css" rel="stylesheet">
    <link href="/shop/assets/plugins/owl.carousel//shop/assets/owl.carousel.css" rel="stylesheet">
    <link href="/shop/assets/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css">
    <link href="/shop/assets/plugins/themes/smoothness/jquery-ui.css" rel="stylesheet" type="text/css">
    <!-- for slider-range -->
    <link href="/shop/assets/plugins/rateit/src/rateit.css" rel="stylesheet" type="text/css">
    <!-- Page level plugin styles END -->

    <!-- Theme styles START -->
    <link href="/shop/assets/pages/css/components.css" rel="stylesheet">
    <link href="/shop/assets/corporate/css/style.css" rel="stylesheet">
    <link href="/shop/assets/pages/css/style-shop.css" rel="stylesheet" type="text/css">
    <link href="/shop/assets/corporate/css/style-responsive.css" rel="stylesheet">
    <link href="/shop/assets/corporate/css/themes/red.css" rel="stylesheet" id="style-color">
    <link rel="stylesheet" href="/shop/assets/static/css/bootstrap-submenu.css">
    <link href="/shop/assets/corporate/css/custom.css" rel="stylesheet">

    <!-- Theme styles END -->
</head>
<!-- Head END -->

<!-- Body BEGIN -->
<body class="corporate">

<!-- BEGIN TOP BAR -->
<?php echo $this->view->getPartial('layouts/_header') ?>
<!-- END TOP BAR -->
<!-- BEGIN HEADER -->
<!-- Header END -->

<div class="main">
    <div class="container">
        <?php echo $this->view->getPartial('layouts/_sidebar') ?>
        <!-- BEGIN SIDEBAR & CONTENT -->

        <!-- END SIDEBAR -->

        <!-- BEGIN CONTENT -->
        <div class="col-md-9 col-sm-9">
            <h1><?php echo $this->obj->getValidateMessage('denglu'); ?></h1>
            <div class="content-form-page">
                <div class="row">
                    <div class="col-md-7 col-sm-7">
                        <form class="form-horizontal form-without-legend" role="form" action="" method="post">
                            <div class="form-group">
                                <label for="login_name"
                                       class="col-lg-4 control-label"><?php echo $this->obj->getValidateMessage('yonghuming'); ?>
                                    <span
                                            class="require">*</span></label>
                                <div class="col-lg-8">
                                    <input type="text" class="form-control" id="login_name" name="login_name">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="password"
                                       class="col-lg-4 control-label"><?php echo $this->obj->getValidateMessage('password'); ?>
                                    <span
                                            class="require">*</span></label>
                                <div class="col-lg-8">
                                    <input type="password" class="form-control" id="password" name="password">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="language"
                                       class="col-lg-4 control-label"><?php echo $this->obj->getValidateMessage('yuyan'); ?>
                                    <span
                                            class="require">*</span></label>
                                <div class="col-lg-8">
                                    <select name="language" id="language" class="form-control">
                                        <option value="cn" selected>简体中文</option>
                                        <!--                                        <option value="en">English</option>-->
                                    </select>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-lg-8 col-md-offset-4 padding-left-0 padding-top-20">
                                    <button type="button" class="btn btn-primary"
                                            id="btn-login"><?php echo $this->obj->getValidateMessage('denglu'); ?></button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- END CONTENT -->
</div>
<!-- END SIDEBAR & CONTENT -->

<!-- BEGIN FOOTER -->
<?php echo $this->view->getPartial('layouts/_footer'); ?>
<!-- END FOOTER -->

</body>
<!-- END BODY -->
</html>