<!DOCTYPE html>

<!--[if IE 8]>
<html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]>
<html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->

<!-- Head BEGIN -->
<head>
    <meta charset="utf-8">
    <title>订单结算</title>

    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <meta content="Metronic Shop UI description" name="description">
    <meta content="Metronic Shop UI keywords" name="keywords">
    <meta content="keenthemes" name="author">

    <link rel="shortcut icon" href="favicon.ico">

    <!-- Global styles START -->
    <link href="/shop/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="/shop/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Global styles END -->

    <!-- Page level plugin styles START -->
    <link href="/shop/assets/pages/css/animate.css" rel="stylesheet">
    <link href="/shop/assets/plugins/fancybox/source/jquery.fancybox.css" rel="stylesheet">
    <link href="/shop/assets/plugins/owl.carousel/assets/owl.carousel.css" rel="stylesheet">
    <!-- Page level plugin styles END -->

    <!-- Theme styles START -->
    <link href="/shop/assets/pages/css/components.css" rel="stylesheet">
    <link href="/shop/assets/pages/css/slider.css" rel="stylesheet">
    <link href="/shop/assets/pages/css/style-shop.css" rel="stylesheet" type="text/css">
    <link href="/shop/assets/corporate/css/style.css" rel="stylesheet">
    <link href="/shop/assets/corporate/css/style-responsive.css" rel="stylesheet">
    <link href="/shop/assets/corporate/css/themes/red.css" rel="stylesheet" id="style-color">
    <link href="/shop/assets/corporate/css/custom.css" rel="stylesheet">
    <!-- Theme styles END -->
</head>
<!-- Head END -->

<!-- Body BEGIN -->
<body class="ecommerce">

<?php echo $this->view->getPartial('layouts/_header') ?>

<div class="main">
    <div class="container">
        <ul class="breadcrumb">
            <li><a href="/">首页</a></li>
            <li class="active">订单结算</li>
        </ul>
        <!-- BEGIN SIDEBAR & CONTENT -->
        <div class="row margin-bottom-40">
            <!-- BEGIN CONTENT -->
            <div class="col-md-12 col-sm-12">
                <!--<h1>结算</h1>-->
                <!-- BEGIN CHECKOUT PAGE -->
                <div class="panel-group checkout-page accordion scrollable" id="checkout-page">

                    <?php
                    if (count($data['product']) > 0) {
                        if ($data['common']['order_status'] == '1') {
                            ?>
                            <!-- BEGIN CHECKOUT -->
                            <div id="checkout" class="panel panel-default">
                                <div class="panel-heading">
                                    <h2 class="panel-title">
                                        <a data-toggle="collapse" data-parent="#checkout-page" href="#checkout-content"
                                           class="accordion-toggle">
                                            Step 1: 填写您的收货信息
                                        </a>
                                    </h2>
                                </div>
                                <div id="checkout-content" class="panel-collapse collapse in">
                                    <div class="panel-body row">
                                        <div class="col-md-12 col-sm-6">

                                            <?php
                                            if (count($data['addresses']) == '0') {
                                                ?>
                                                <div class="form-group">
                                                    <label for="reciver_name">收件人姓名 <span
                                                                class="require">*</span></label>
                                                    <input type="text" id="reciver_name" class="form-control">
                                                </div>
                                                <div class="form-group">
                                                    <label for="reciver_phone">收件人电话 <span
                                                                class="require">*</span></label>
                                                    <input type="text" id="reciver_phone" class="form-control">
                                                </div>
                                                <div class="form-group">
                                                    <label for="reciver_address">收件人地址 <span
                                                                class="require">*</span></label>
                                                    <input type="text" id="reciver_address" class="form-control">
                                                </div>
                                                <?php
                                            } else {
                                                foreach ($data['addresses'] as $address) {
                                                    ?>
                                                    <label for="address_id-<?php echo $address['id'] ?>"
                                                           class="label-address"><input
                                                                id="address_id-<?php echo $address['id'] ?>"
                                                                name="address_id" type="radio"
                                                                value="<?php echo $address['id'] ?>"<?php if ($address['is_default']) {
                                                            echo 'checked="checked"';
                                                        } ?>> <?php echo $address['name'] . ' ' . $address['tel'] . ' ' . $address['address']; ?><?php if ($address['is_default']) {
                                                            echo ' [默认地址]';
                                                        } ?></label>
                                                    <br>
                                                    <?php
                                                }
                                            }
                                            ?>

                                            <button class="btn btn-primary pull-right" type="submit"
                                                    data-toggle="collapse" data-parent="#checkout-page"
                                                    data-target="#payment-address-content" id="button-payment-address">
                                                继续
                                            </button>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- END CHECKOUT -->

                            <!-- BEGIN PAYMENT ADDRESS -->
                            <div id="payment-address" class="panel panel-default">
                                <div class="panel-heading">
                                    <h2 class="panel-title">
                                        <a data-toggle="collapse" data-parent="#checkout-page"
                                           href="#payment-address-content" class="accordion-toggle">
                                            Step 2: 选择支付方式
                                        </a>
                                    </h2>
                                </div>
                                <div id="payment-address-content" class="panel-collapse collapse">
                                    <div class="panel-body row">
                                        <div class="col-md-12 col-sm-6">
                                            <div class="form-group paymethod">
                                                <label for="paymethod1"><input type="radio" id="paymethod1" class=""
                                                                               name="pay_style" value="1"
                                                                               checked="checked"> 微信</label>

                                                <label for="paymethod2"><input type="radio" id="paymethod2" class=""
                                                                               name="pay_style" value="2"> 支付宝</label>

                                                <button class="btn btn-primary  pull-right" type="submit"
                                                        data-toggle="collapse" data-parent="#checkout-page"
                                                        data-target="#confirm-content" id="button-payment-address">继续
                                                </button>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- END PAYMENT ADDRESS -->
                        <?php } ?>

                        <!-- BEGIN CONFIRM -->
                        <div id="confirm" class="panel panel-default">

                            <?php if ($data['common']['order_status'] == '1') { ?>
                                <div class="panel-heading">
                                    <h2 class="panel-title">
                                        <a data-toggle="collapse" data-parent="#checkout-page" href="#confirm-content"
                                           class="accordion-toggle">
                                            Step 3: 结算
                                        </a>
                                    </h2>
                                </div>
                            <?php } ?>

                            <div id="confirm-content"
                                 class="panel-collapse collapse<?php if ($data['common']['order_status'] != '1') { ?> in<?php } ?>">
                                <div class="panel-body row">
                                    <div class="col-md-12 clearfix">
                                        <div class="table-wrapper-responsive">
                                            <table>
                                                <tr>
                                                    <th class="checkout-image">图片</th>
                                                    <th class="checkout-description">商品名称</th>
                                                    <th class="checkout-model">颜色</th>
                                                    <th class="checkout-model">尺寸</th>
                                                    <th class="checkout-quantity">价格</th>
                                                    <th class="checkout-price">数量</th>
                                                    <th class="checkout-price">总价</th>
                                                </tr>
                                                <?php foreach ($data['product'] as $k => $v) { ?>
                                                    <tr>
                                                        <td class="checkout-image">
                                                            <a href="/product/detail/<?php echo $v['product_detail_id']; ?>"><img
                                                                        src="<?php echo $v['picture']; ?>"
                                                                        alt="<?php echo $v['product_name']; ?>"></a>
                                                        </td>
                                                        <td class="checkout-description">
                                                            <h3>
                                                                <a href="/product/detail/<?php echo $v['product_detail_id']; ?>"><?php echo $v['product_name']; ?></a>
                                                            </h3>
                                                        </td>
                                                        <td class="checkout-model"><?php echo $v['color_name']; ?></td>
                                                        <td class="checkout-model"><?php echo $v['size_name']; ?></td>
                                                        <td class="checkout-quantity"><?php echo $this->currency . $v['price']; ?></td>
                                                        <td class="checkout-price">
                                                            <strong><?php echo $v['number']; ?></strong></td>
                                                        <td class="checkout-total">
                                                            <strong><span><?php echo $this->currency; ?></span><?php echo $v['total_price']; ?>
                                                            </strong></td>
                                                    </tr>
                                                <?php } ?>

                                            </table>
                                        </div>
                                        <div class="checkout-total-block">
                                            <ul>
                                                <li>
                                                    <em>商品总计</em>
                                                    <strong class="price"><span><?php echo $this->currency; ?></span><?php echo $data['common']['total_price']; ?>
                                                    </strong>
                                                </li>
                                                <li>
                                                    <em>运费</em>
                                                    <strong class="price"><span><?php echo $this->currency; ?></span><?php echo $data['common']['send_price']; ?>
                                                    </strong>
                                                </li>
                                                <li class="checkout-total-price">
                                                    <em>成交价</em>
                                                    <strong class="price"><span><?php echo $this->currency; ?></span><?php echo $data['common']['final_price']; ?>
                                                    </strong>
                                                </li>
                                            </ul>
                                        </div>
                                        <div class="clearfix"></div>
                                        <?php if ($data['common']['order_status'] == '2') { ?>
                                            <span class="pull-right">订单已支付未完成</span>
                                        <?php } else if ($data['common']['order_status'] == '3') { ?>
                                            <span class="pull-right">订单已完成</span>
                                        <?php } else if ($data['common']['order_status'] == '4') { ?>
                                            <span class="pull-right">订单已取消</span>
                                        <?php } else if ($data['common']['order_status'] == '5') { ?>
                                            <span class="pull-right">订单退款中</span>
                                        <?php } else if ($data['common']['order_status'] == '6') { ?>
                                            <span class="pull-right">订单已退款</span>
                                        <?php } else { ?>
                                            <button class="btn btn-primary pull-right" type="button" id="button-confirm"
                                                    onclick="payment_order(<?php echo $data['common']['id']; ?>);return false;">
                                                支付
                                            </button>
                                            <button type="button" class="btn btn-default pull-right margin-right-20"
                                                    id="button-cancle"
                                                    onclick="cancle_order(<?php echo $data['common']['id']; ?>);return false;">
                                                取消
                                            </button>
                                        <?php } ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- END CONFIRM -->
                    <?php } else { ?>
                        <p>订单不存在</p>
                    <?php } ?>

                </div>
                <!-- END CHECKOUT PAGE -->
            </div>
            <!-- END CONTENT -->
        </div>
        <!-- END SIDEBAR & CONTENT -->
    </div>
</div>

<?php echo $this->view->getPartial('layouts/_footer'); ?>

<script>
    // 订单支付逻辑
    function payment_order(id) {
        // ajax提交
        $.ajax({
            type: "post",
            url: "/order/confirm/" + id,
            async: true,
            dataType: 'json',
            data: {
                'reciver_name': $('#reciver_name').val(),
                'reciver_phone': $('#reciver_phone').val(),
                // 'reciver_no':$('#reciver_no').val(),
                'reciver_address': $('#reciver_address').val(),
                'address_id': $("input[name='address_id']:checked").val(),
                'pay_style': $("input[name='pay_style']:checked").val(),
            },
            beforeSend: function () {
                // 禁用按钮防止重复提交
                $("#button-confirm").attr({disabled: "disabled"});
            },
            success: function (response) {
                // 判断是否有错误
                if (response.messages.length > 0) {
                    layer.open({
                        content: response.messages[0],
                        btn: '我知道了'
                    });
                } else {
                    //提示
                    layer.open({
                        content: '付款成功',
                        btn: '3秒后自动跳转',
                        time: 3, // 3秒后自动跳转
                    });
                    // 3秒后跳转
                    setTimeout(function () {
                        window.location.href = '/order/list';
                    }, 1000);
                }
            },
            complete: function () {
                $("#button-confirm").removeAttr("disabled");
            },
        });
        // 禁止自动跳转
        return false;
    }
</script>
<!-- END PAGE LEVEL JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>