<!DOCTYPE html>

<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->

<!-- Head BEGIN -->
<head>
  <meta charset="utf-8">
  <title>Checkout | Metronic Shop UI</title>

  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <meta content="Metronic Shop UI description" name="description">
  <meta content="Metronic Shop UI keywords" name="keywords">
  <meta content="keenthemes" name="author">

  <meta property="og:site_name" content="-CUSTOMER VALUE-">
  <meta property="og:title" content="-CUSTOMER VALUE-">
  <meta property="og:description" content="-CUSTOMER VALUE-">
  <meta property="og:type" content="website">
  <meta property="og:image" content="-CUSTOMER VALUE-"><!-- link to image for socio -->
  <meta property="og:url" content="-CUSTOMER VALUE-">

  <link rel="shortcut icon" href="favicon.ico">

  <!-- Global styles START -->          
  <link href="/shop/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
  <link href="/shop/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <!-- Global styles END --> 
   
  <!-- Page level plugin styles START -->
  <link href="/shop/assets/plugins/fancybox/source/jquery.fancybox.css" rel="stylesheet">
  <link href="/shop/assets/plugins/owl.carousel/assets/owl.carousel.css" rel="stylesheet">
  <link href="/shop/assets/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css">
  <!-- Page level plugin styles END -->

  <!-- Theme styles START -->
  <link href="/shop/assets/pages/css/components.css" rel="stylesheet">
  <link href="/shop/assets/corporate/css/style.css" rel="stylesheet">
  <link href="/shop/assets/pages/css/style-shop.css" rel="stylesheet" type="text/css">
  <link href="/shop/assets/corporate/css/style-responsive.css" rel="stylesheet">
  <link href="/shop/assets/corporate/css/themes/red.css" rel="stylesheet" id="style-color">
  <link href="/shop/assets/corporate/css/custom.css" rel="stylesheet">
  <!-- Theme styles END -->
</head>
<!-- Head END -->

<!-- Body BEGIN -->
<body class="ecommerce">
    <!-- BEGIN STYLE CUSTOMIZER -->
    <div class="color-panel hidden-sm">
      <div class="color-mode-icons icon-color"></div>
      <div class="color-mode-icons icon-color-close"></div>
      <div class="color-mode">
        <p>THEME COLOR</p>
        <ul class="inline">
          <li class="color-red" data-style="red"></li>
          <li class="color-turquoise" data-style="turquoise"></li>
        </ul>
      </div>
    </div>
    <!-- END BEGIN STYLE CUSTOMIZER --> 

    <!-- BEGIN TOP BAR -->
    <?php echo $this->view->getPartial('layouts/_header') ?>
    <!-- Header END -->

    <div class="main">
      <div class="container">
        <!--<ul class="breadcrumb">
            <li><a href="index.html">Home</a></li>
            <li><a href="">Store</a></li>
            <li class="active">Checkout</li>
        </ul>-->
        <!-- BEGIN SIDEBAR & CONTENT -->
        <div class="row margin-bottom-40">
          <!-- BEGIN CONTENT -->
          <div class="col-md-12 col-sm-12">
            <h1>结算</h1>
            <!-- BEGIN CHECKOUT PAGE -->
            <div class="panel-group checkout-page accordion scrollable" id="checkout-page">

              <!-- BEGIN CHECKOUT -->
              <!-- END CHECKOUT -->

              <!-- BEGIN PAYMENT ADDRESS -->
              <div id="payment-address" class="panel panel-default">
                <div class="panel-heading">
                  <h2 class="panel-title">
                    <a data-toggle="collapse" data-parent="#checkout-page" href="#payment-address-content" class="accordion-toggle">
                      Step 1: 填写您的收货信息
                    </a>
                  </h2>
                </div>
                <div id="payment-address-content" class="panel-collapse collapse in">
                  <div class="panel-body row">
                    <div class="col-md-12 col-sm-6">
                      <div class="form-group">
                        <label for="reciver_name">收件人姓名 <span class="require">*</span></label>
                        <input type="text" id="reciver_name" class="form-control">
                      </div>
                      <div class="form-group">
                        <label for="reciver_phone">收件人电话 <span class="require">*</span></label>
                        <input type="text" id="reciver_phone" class="form-control">
                      </div>
                      <div class="form-group">
                        <label for="reciver_no">收件人身份证 <span class="require">*</span></label>
                        <input type="text" id="reciver_no" class="form-control">
                      </div>
                      <div class="form-group">
                        <label for="reciver_address">收件人地址 <span class="require">*</span></label>
                        <input type="text" id="reciver_address" class="form-control">
                      </div>
                    </div>
                    <!--<hr>
                    <div class="col-md-12">                      
                      <button class="btn btn-primary  pull-right" type="submit" data-toggle="collapse" data-parent="#checkout-page" data-target="#shipping-address-content" id="button-payment-address">去结算</button>
                    </div>-->
                  </div>
                </div>
              </div>
              
              <div id="payment-address" class="panel panel-default">
                <div class="panel-heading">
                  <h2 class="panel-title">
                    <a data-toggle="collapse" data-parent="#checkout-page" href="#payment-pay-content" class="accordion-toggle">
                      Step 2: 选择支付方式
                    </a>
                  </h2>
                </div>
                <div id="payment-pay-content" class="panel-collapse collapse">
                  <div class="panel-body row">
                    <div class="col-md-12 col-sm-6">
                      <div class="form-group">
                        <input type="radio" id="firstname1" class="" name="pay_style" value="1" checked="checked">
                        <label for="firstname1">微信 <span class="require">*</span></label>
                        <input type="radio" id="firstname2" class="" name="pay_style" value="2">
                        <label for="firstname2">支付宝 <span class="require">*</span></label>
                      </div>
                      <div class="form-group">
                      </div>
                    </div>
                    <!--<hr>
                    <div class="col-md-12">                      
                      <button class="btn btn-primary  pull-right" type="submit" data-toggle="collapse" data-parent="#checkout-page" data-target="#shipping-address-content" id="button-payment-address">去结算</button>
                    </div>-->
                  </div>
                </div>
              </div>
              <!-- END PAYMENT ADDRESS -->

              <!-- BEGIN SHIPPING ADDRESS -->
              <!-- END SHIPPING ADDRESS -->

              <!-- BEGIN SHIPPING METHOD -->
              <!-- END PAYMENT METHOD -->

              <!-- BEGIN CONFIRM -->
              <div id="confirm" class="panel panel-default">
                <div class="panel-heading">
                  <h2 class="panel-title">
                    <a data-toggle="collapse" data-parent="#checkout-page" href="#confirm-content" class="accordion-toggle">
                      Step 3: 结算
                    </a>
                  </h2>
                </div>
                <div id="confirm-content" class="panel-collapse collapse">
                  <div class="panel-body row">
                    <div class="col-md-12 clearfix">
                      <div class="table-wrapper-responsive">
                      <table>
                        <tr>
                          <th class="checkout-image">图片</th>
                          <th class="checkout-description">商品名称</th>
                          <th class="checkout-model">颜色</th>
                          <th class="checkout-model">尺寸</th>
                          <th class="checkout-quantity">价格</th>
                          <th class="checkout-price">数量</th>
                          <th class="checkout-price">总价</th>
                        </tr>
                        <?php foreach($data['product'] as $k=>$v){ ?>
                          	<tr>
	                          	<td class="checkout-image">
	                            	<a href="javascript:;"><img src="assets/pages/img/products/model3.jpg" alt="Berry Lace Dress"></a>
	                          	</td>
	                          	<td class="checkout-description">
	                            <h3><a href="javascript:;"><?php echo $v['product_name']; ?></a></h3>
	                            </td>
	                            <td class="checkout-model"><?php echo $v['color_name']; ?></td>
	                            <td class="checkout-model"><?php echo $v['size_name']; ?></td>
	                         	<td class="checkout-quantity"><?php echo $v['price']; ?></td>
	                            <td class="checkout-price"><strong><span>$</span><?php echo $v['number']; ?></strong></td>
	                            <td class="checkout-total"><strong><span>$</span><?php echo $v['total_price']; ?></strong></td>
	                        </tr>
                        <?php } ?>
                          
                      </table>
                      </div>
                      <div class="checkout-total-block">
                        <ul>
                          <li>
                            <em>商品总计</em>
                            <strong class="price"><span>$</span><?php echo $data['common']['total_price']; ?></strong>
                          </li>
                          <li>
                            <em>运费</em>
                            <strong class="price"><span>$</span><?php echo $data['common']['send_price']; ?></strong>
                          </li>
                          <li class="checkout-total-price">
                            <em>成交价</em>
                            <strong class="price"><span>$</span><?php echo $data['common']['final_price']; ?></strong>
                          </li>
                        </ul>
                      </div>
                      <div class="clearfix"></div>
                      <button class="btn btn-primary pull-right" type="button" id="button-confirm">支付</button>
                      <button type="button" class="btn btn-default pull-right margin-right-20">取消</button>
                    </div>
                  </div>
                </div>
              </div>
              <!-- END CONFIRM -->
            </div>
            <!-- END CHECKOUT PAGE -->
          </div>
          <!-- END CONTENT -->
        </div>
        <!-- END SIDEBAR & CONTENT -->
      </div>
    </div>

    <!-- BEGIN STEPS -->
    <!-- END STEPS -->

    <?php echo $this->view->getPartial('layouts/_footer') ?>

    <!-- Load javascripts at bottom, this will reduce page load time -->
    <!-- BEGIN CORE PLUGINS(REQUIRED FOR ALL PAGES) -->
    <!--[if lt IE 9]>
    <script src="/shop/assets/plugins/respond.min.js"></script>
    <![endif]-->
    <script src="/shop/assets/plugins/jquery.min.js" type="text/javascript"></script>
    <script src="/shop/assets/plugins/jquery-migrate.min.js" type="text/javascript"></script>
    <script src="/shop/assets/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="/shop/assets/corporate/scripts/back-to-top.js" type="text/javascript"></script>
    <script src="/shop/assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <!-- END CORE PLUGINS -->

    <!-- BEGIN PAGE LEVEL JAVASCRIPTS (REQUIRED ONLY FOR CURRENT PAGE) -->
    <script src="/shop/assets/plugins/fancybox/source/jquery.fancybox.pack.js" type="text/javascript"></script><!-- pop up -->
    <script src="/shop/assets/plugins/owl.carousel/owl.carousel.min.js" type="text/javascript"></script><!-- slider for products -->
    <script src='/shop/assets/plugins/zoom/jquery.zoom.min.js' type="text/javascript"></script><!-- product zoom -->
    <script src="/shop/assets/plugins/bootstrap-touchspin/bootstrap.touchspin.js" type="text/javascript"></script><!-- Quantity -->
    <script src="/shop/assets/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>

    <script src="/shop/assets/corporate/scripts/layout.js" type="text/javascript"></script>
    <script src="/shop/assets/pages/scripts/checkout.js" type="text/javascript"></script>
    <script type="text/javascript">
        jQuery(document).ready(function() {
            Layout.init();    
            Layout.initOWL();
//          Layout.initTwitter();
            Layout.initImageZoom();
            Layout.initTouchspin();
            Layout.initUniform();
            Checkout.init();
        });
        
        $("#button-confirm").click(function(){
        	$.ajax({
        		type:"post",
        		url:"/order/submit",
        		async:true,
        		dataType:'json',
        		data:{
        			'reciver_name': $("#reciver_name").val(),
        			'reciver_phone': $("#reciver_phone").val(),
        			'reciver_no': $("#reciver_no").val(),
        			'reciver_address': $("#reciver_address").val(),
        			'pay_style': $("input[name='pay_style']").val()
        		},
        		success:function(result){
        			if(result.auth){
        				alert('支付成功');
        				window.setInterval(function(){
    					}, 2000);
						location.href = "index/index";
        			}else{
        				alert('支付成功');
        			}
        		}
	        });
        })
        
    </script>
    <!-- END PAGE LEVEL JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>