<!DOCTYPE html>

<!--[if IE 8]>
<html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]>
<html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->

<!-- Head BEGIN -->
<head>
    <meta charset="utf-8">
    <title><?php echo $this->obj->getValidateMessage('dingdanjiesuan'); ?></title>
    <?php echo $this->view->getPartial('layouts/_meta') ?>
</head>
<!-- Head END -->

<!-- Body BEGIN -->
<body class="ecommerce">

<?php echo $this->obj->view->getPartial('layouts/_header') ?>

<div class="main">
    <div class="container">
        <ul class="breadcrumb">
            <li><a href="/"><?php echo $this->obj->getValidateMessage('shouye'); ?></a></li>
            <li class="active"><?php echo $this->obj->getValidateMessage('dingdanjiesuan'); ?></li>
        </ul>
        <!-- BEGIN SIDEBAR & CONTENT -->
        <div class="row margin-bottom-40">
            <!-- BEGIN CONTENT -->
            <div class="col-md-12 col-sm-12">
                <!--<h1>结算</h1>-->
                <!-- BEGIN CHECKOUT PAGE -->
                <div class="panel-group checkout-page accordion scrollable" id="checkout-page">

                    <!-- BEGIN CONFIRM -->
                    <div id="confirm" class="panel panel-default">
                        <div id="confirm-content"
                             class="panel-collapse collapse in">
                            <div class="panel-body row">
                                <div class="col-md-12 clearfix">
                                    <div class="table-wrapper-responsive">
                                        <table>
                                            <tr>
                                                <th class="checkout-image"><?php echo $this->obj->getValidateMessage('tupian'); ?></th>
                                                <th class="checkout-description"><?php echo $this->obj->getValidateMessage('shangpinmingcheng'); ?></th>
                                                <th class="checkout-model"><?php echo $this->obj->getValidateMessage('yanse'); ?></th>
                                                <th class="checkout-model"><?php echo $this->obj->getValidateMessage('menu-2-1-7'); ?></th>
                                                <th class="checkout-quantity"><?php echo $this->obj->getValidateMessage('jiage'); ?></th>
                                                <th class="checkout-price"><?php echo $this->obj->getValidateMessage('shuliang'); ?></th>
                                                <th class="checkout-price"><?php echo $this->obj->getValidateMessage('zongjia'); ?></th>
                                            </tr>
                                            <?php foreach ($data['product'] as $k => $v) { ?>
                                                <tr>
                                                    <td class="checkout-image">
                                                        <a href="/product/detail/<?php echo $v['product_detail_id']; ?>"><img
                                                                    src="<?php echo $v['picture']; ?>"
                                                                    alt="<?php echo $v['product_name']; ?>"></a>
                                                    </td>
                                                    <td class="checkout-description">
                                                        <h3>
                                                            <a href="/product/detail/<?php echo $v['product_detail_id']; ?>"><?php echo $v['product_name']; ?></a>
                                                        </h3>
                                                    </td>
                                                    <td class="checkout-model"><?php echo $v['color_name']; ?></td>
                                                    <td class="checkout-model"><?php echo $v['size_name']; ?></td>
                                                    <td class="checkout-quantity"><?php echo $this->obj->currency . $v['price']; ?></td>
                                                    <td class="checkout-price">
                                                        <strong><?php echo $v['number']; ?></strong></td>
                                                    <td class="checkout-total">
                                                        <strong><span><?php echo $this->obj->currency; ?></span><?php echo $v['total_price']; ?>
                                                        </strong></td>
                                                </tr>
                                            <?php } ?>

                                        </table>
                                    </div>
                                    <div class="checkout-total-block">
                                        <ul>
                                            <li>
                                                <em><?php echo $this->obj->getValidateMessage('zongjia'); ?></em>
                                                <strong class="price"><span><?php echo $this->obj->currency; ?></span><?php echo $data['common']['total_price']; ?>
                                                </strong>
                                            </li>
                                            <li>
                                                <em><?php echo $this->obj->getValidateMessage('freight'); ?></em>
                                                <strong class="price"><span><?php echo $this->obj->currency; ?></span><?php echo $data['common']['send_price']; ?>
                                                </strong>
                                            </li>
                                            <li class="checkout-total-price">
                                                <em><?php echo $this->obj->getValidateMessage('chengjiaozongjia'); ?></em>
                                                <strong class="price"><span><?php echo $this->obj->currency; ?></span><?php echo $data['common']['final_price']; ?>
                                                </strong>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="clearfix"></div>

                                    <div class="pull-right">
                                        <?php if ($data['isAllowPaymentOrder']) { ?>
                                            <!-- 微信功能按钮 Start -->
                                            <button class="btn btn-success" type="button"
                                                    id="button-confirm"
                                                    onclick="return paymentByWechat(<?php echo $data['common']['id']; ?>);">
                                                <?php echo $this->obj->getValidateMessage('wechat-method'); ?>
                                            </button>
                                            <!-- 微信功能按钮 End -->

                                            <!-- 支付宝功能按钮 Start -->
                                            <button class="btn btn-info" type="button"
                                                    id="button-confirm"
                                                    onclick="return paymentByAliapy(<?php echo $data['common']['id']; ?>);">
                                                <?php echo $this->obj->getValidateMessage('alipay-method'); ?>
                                            </button>
                                            <!-- 支付宝功能按钮 End -->
                                        <?php } else { ?>
                                            <p><?php echo $data['order_status']['pay_status']; ?></p>
                                        <?php } ?>

                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- END CONFIRM -->

                </div>
                <!-- END CHECKOUT PAGE -->
            </div>
            <!-- END CONTENT -->
        </div>
        <!-- END SIDEBAR & CONTENT -->
    </div>
</div>

<script src="/shop/assets/custom/arealist.js"></script>
<script src="/shop/assets/custom/addressparse.js"></script>
<?php echo $this->obj->view->getPartial('layouts/_footer'); ?>

<script>
    // 定义一个弹出层
    var index = null;

    /**
     * 支付宝支付
     * @param order_id 订单id
     * @returns {boolean}
     */
    function paymentByAliapy(order_id) {
        // 跳转支付
        window.open('/alipay/pay/' + order_id);
    }

    /**
     * 微信支付
     * @param order_id 订单id
     * @returns {boolean}
     */
    function paymentByWechat(order_id) {
        // 动态添加付款二维码
        ajax('/wechatpay/pay/' + order_id, {}, null, paymentByWechatCallback);
    }

    /**
     * 回调函数：生成微信付款二维码
     * @param response
     */
    function paymentByWechatCallback(response) {
        // 逻辑
        let img = '<div><p><?php echo $this->obj->getValidateMessage('scan-code-to-pay'); ?>：</p><img alt="二维码" src="' + response.data + '"></div>';
        // 弹出一张二维码图片
        index = layer.open({
            content: img,
            btn: "<?php echo $this->obj->getValidateMessage('iknow'); ?>"
        });
    }
</script>
<!-- END PAGE LEVEL JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>
