<div id="ell">
<el-row>
  <el-col :span="24">
  <el-button type="primary" @click="showForm('create')"><?=$system_language["button-create"]?></el-button>
  </el-col>
</el-row>

<el-row :gutter="20">
  <el-col :span="24">
    <el-table :data="tableData" stripe border style="width: 100%;">
      <el-table-column prop="id" label="ID" align="center" width="180">
      </el-table-column>

      <el-table-column prop="code" label="<?=$system_language["guojiadaima"]?>" align="center" width="180">
      </el-table-column>

      <el-table-column prop="name" label="<?=$system_language["guojiamingcheng"]?>" width="180" align="center">
      </el-table-column>
      
      <el-table-column prop="LocalCurrency" label="<?=$system_language["bizhong"]?>" width="180" align="center">
        <template v-slot="scope">
          {{currency[scope.row.LocalCurrency]}}
        </template>
      </el-table-column>
      
      <el-table-column prop="lang_code" label="<?=$system_language["yuzhong"]?>" width="180" align="center">
         <template v-slot="scope">
          {{languages[scope.row.lang_code]}}
        </template>
      </el-table-column>

      <el-table-column label="<?=$system_language["caozuo"]?>" width="150" align="center">
        <template v-slot="scope">
          <el-button size="mini" @click="handleEdit(scope.$index, scope.row)"><?=$system_language["bianji"]?></el-button>
          <el-button size="mini" type="danger" @click="handleDelete(scope.$index, scope.row)"><?=$system_language["shanchu"]?></el-button>
        </template>
      </el-table-column>
    </el-table>
  </el-col>
</el-row>

<el-dialog class="user-form" :title="labels[action_type][0]" :visible.sync="dialogVisible" :center="true" width="40%">
    <el-tabs type="border-card" @tab-click="onTabClick">
    <el-tab-pane label="<?=$system_language["jibenziliao"]?>"> 
      <el-form ref="form" :model="form" label-width="80px">
  <el-form-item label="<?=$system_language["guojiadaima"]?>">
    <el-input v-model="form.code"></el-input>
  </el-form-item>
  
  <el-form-item label="<?=$system_language["guojiamingcheng"]?>">
    <el-input v-model="form.name"></el-input>
  </el-form-item>
      
  <el-form-item label="<?=$system_language["bizhong"]?>">
    <el-select v-model="form.LocalCurrency" placeholder="<?=$system_language["qingxuanze"]?>">
      <el-option v-for="(item, key) in currency" :label="item" :value="key">
        <span style="float: left">{{ key }}</span>
        <span style="float: right; color: #8492a6; font-size: 13px">{{ item }}</span>  
      </el-option>
    </el-select>
  </el-form-item>
  
  <el-form-item label="<?=$system_language["yuzhong"]?>">
    <el-select v-model="form.lang_code" placeholder="<?=$system_language["qingxuanze"]?>">
      <el-option v-for="(item, key) in languages" :label="item" :value="key">
      </el-option>
    </el-select>
  </el-form-item>
  
  <el-form-item>
    <el-button type="primary" @click="onSubmit">{{labels[action_type][1]}}</el-button>
  </el-form-item>
</el-form>
    </el-tab-pane>
    <el-tab-pane label="<?=$system_language["dianshangduizhaobiao"]?>">定时任务补偿</el-tab-pane>
  </el-tabs>  
</el-dialog>
</div>

<script>
$(document).ready(function(){
    new Vue({
        el:"#ell",
        data() {
            return {
                tableData: <?=json_encode($result)?>,
                dialogVisible:false,
                form: {
                    name: '',
                    code: '',
                    LocalCurrency:'',
                    lang_code:'',
                    id:''
                },
                currency:[],
                action_type:"create",
                labels:{
                    create:['<?=$system_language["xinjianxinxi"]?>','<?=$system_language["button-save"]?>'],
                    update:['<?=$system_language["xiugaixinxi"]?>','<?=$system_language["button-save"]?>']       
                },
                languages:[],
                rowIndex:""
            }
        },
        methods: {
            onSubmit() {
                var self = this;
                if(this.form.id=="") {
                    $ASA.submit.call(this, "/country/add", this.form, function(){
                        
                        self.tableData.push($ASA.clone(self.form) )   
                    })
                }
                else {
                    $ASA.submit.call(this, "/country/edit", this.form, function(){
                        //self.tableData[self.rowIndex].lang_code = self.form.lang_code 
                        $ASA.copyTo(self.form, self.tableData[self.rowIndex])
                    }) 
                }
            },
            onTabClick(tab){
                console.log(tab)
            },
            showForm(action) {
                this.dialogVisible = true;
                this.action_type = action;
            },
            handleEdit(rowIndex, row){
               $ASA.copyTo(row, this.form)
               
               this.rowIndex = rowIndex;
               
               this.action_type = 'update';
               this.dialogVisible = true;
            },
            handleDelete(rowIndex, row) {
                var self = this
                $ASA.remove.call(this, "/country/delete?id="+row.id, function() {
                    self.$delete(self.tableData,rowIndex)   
                })
            },
            loadCurrency:function(language) {
                var self = this;
                $.post("/common/currency", {language:language}, function(res){
                    console.log(res.currency)
                     self.form.lang_code = res.language;
                     self.currency = res.currency;
                },"json")
            },
            loadLanguage:function(language) {
                var self = this;
                $.post("/common/language", {}, function(res){
                     self.languages = res;
                },"json")
            }
        },
        computed:{
            langName(code) {
                console.log(code)
                return this.languages[this.form.lang_code]   
            }    
        },
        mounted:function(){
            this.loadCurrency();        
            this.loadLanguage();     
        }
    })
})
</script>
<style>
    
    </style>

