<div id="ell">
<multiple-admin-page v-bind="props" ref="page"></multiple-admin-page>

</div>

<script>
$(document).ready(function(){
    $.post("/common/currency", {}, function(res){
        console.log(res.currency)
        var props = {
            columns:[
                {name:"code", label:"<?=$system_language['guojiadaima']?>", is_create:true, is_update:true, is_show:true, width:200, disable_change:true, is_focus:true},
                {name:"name", label:"<?=$system_language['guojiamingcheng']?>", is_create:true, is_update:true, is_show:true, width:200, is_focus:true},
                {name:"localcurrency", label:"<?=$system_language['bizhong']?>", is_create:true, is_update:true, is_show:true, width:200, disable_change:true, type:'select', data_source:{
                    hashtable:res.currency
                }}
            ],
            options:{
                dialogWidth:"35%"
            },
            default_language:'zh-cn',
            controller:"country",
            currency:res.currency
        }
        
        new Vue({
            el:"#ell",
            data() {
                return {
                    props:props   
                }
            }
        })
    },"json");
})
</script>
<style>
</style>

