<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>图片导出测试</title>
</head>
<body>
<form action="">
    <table class="table table-bordered table-hover table-responsive">
        <tr>
            <th>选择</th>
            <th>序号</th>
            <th>图片预览</th>
            <th>图片地址</th>
        </tr>
        <tr>
            <td><input type="checkbox" name="ids[]" value="1"></td>
            <td>1</td>
            <td><img src="/upload/product/91a791ff46592e73f3b37a5e293a0033.jpg" alt=""></td>
            <td></td>
        </tr>
        <tr>
            <td><input type="checkbox" name="ids[]" value="2"></td>
            <td>2</td>
            <td><img src="/upload/product/0820505ecba45bc993739ba4152aeecf.jpg" alt=""></td>
            <td></td>
        </tr>
        <tr>
            <td><input type="checkbox" name="ids[]" value="3"></td>
            <td>3</td>
            <td><img src="/upload/product/ae8deb1ae3139a6e603475441d75680f.jpg" alt=""></td>
            <td></td>
        </tr>
        <tr>
            <td><input type="checkbox" name="ids[]" value="4"></td>
            <td>4</td>
            <td><img src="/upload/product/d237442d5a8662c9a997666a652d5693.jpg" alt=""></td>
            <td></td>
        </tr>
        <tr>
            <td><input type="checkbox" name="ids[]" value="5"></td>
            <td>5</td>
            <td><img src="/upload/product/model4.jpg" alt=""></td>
            <td></td>
        </tr>
        <tr>
            <td rowspan="4"><input type="checkbox" name="checkAll"></td>
        </tr>
    </table>
</form>
</body>
</html>