<div id="ell">
  <multiple-admin-page v-bind="props" ref="page"></multiple-admin-page>
</div>

<script>
$(document).ready(function(){
    var props = {
        columns:[
            {name:"name", label:"姓名", is_create:true, is_update:true, is_show:true, width:400},
            {name:"code", label:"地址", is_create:true, is_update:true, is_show:true, width:400},
            {name:"brandid", label:"品牌", is_create:false, is_update:false, is_show:false, is_edit_hide:true}
        ],
        controller:"aliases",
        languages:{"zh-cn":{"code":"zh-cn","name":"\u7b80\u4f53\u4e2d\u6587","shortName":"\u7b80"},"zh-hk":{"code":"zh-hk","name":"\u7e41\u4f53\u4e2d\u6587","shortName":"\u7e41"},"en-us":{"code":"en-us","name":"\u82f1\u6587","shortName":"\u82f1"}},
        'controller':'aliases',
        key_column:"name"
    }
    
    new Vue({
        el:"#ell",
        data() {
            return {
                props:props   
            }
        },
        methods: {
        }        
    })
})
</script>
