<!DOCTYPE html>
<!--[if IE 8]>
<html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]>
<html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->

<!-- Head BEGIN -->
<head>
    <meta charset="utf-8">
    <title><?php echo $this->obj->getValidateMessage('invitation-registration-list'); ?></title>
    <?php echo $this->view->getPartial('layouts/_meta') ?>
</head>
<!-- Head END -->

<!-- Body BEGIN -->
<body class="corporate">

<?php echo $this->view->getPartial('layouts/_header') ?>

<div class="main">
    <div class="container">
        <ul class="breadcrumb">
            <li><a href="/"><?php echo $this->obj->getValidateMessage('shouye'); ?></a></li>
            <li class="active"><?php echo $this->obj->getValidateMessage('invitation-registration-list'); ?></li>
        </ul>
        <!-- BEGIN SIDEBAR & CONTENT -->
        <div class="row margin-bottom-40">

            <?php echo $this->view->getPartial('layouts/_member_sidebar') ?>

            <!-- BEGIN CONTENT -->
            <div class="col-md-9 col-sm-9">
                <h1 class="h1-title"><span class="pull-right"><a
                                href="/member/invite"><?php echo $this->obj->getValidateMessage('invitation-registration'); ?></a></span><?php echo $this->obj->getValidateMessage('invitation-registration-list'); ?>
                </h1>
                <div class="content-form-page">
                    <div class="row">
                        <div class="col-md-12">
                            <table id="table-address" class="table table-bordered table-hover" style="width:100%">
                                <tr>
                                    <th><?php echo $this->obj->getValidateMessage('yonghuming'); ?></th>
                                    <th><?php echo $this->obj->getValidateMessage('email'); ?></th>
                                    <th><?php echo $this->obj->getValidateMessage('company'); ?></th>
                                </tr>
                                <?php
                                if (isset($result) && count($result) > 0) {
                                    foreach ($result as $data) {
                                        ?>
                                        <tr>
                                            <td><?php echo $data['login_name']; ?></td>
                                            <td><?php echo $data['email']; ?></td>
                                            <td><?php echo $data['companyname']; ?></td>
                                        </tr>
                                    <?php } ?>
                                <?php } else { ?>
                                    <tr>
                                        <td colspan="5"><?php echo $this->obj->getValidateMessage('no-data'); ?></td>
                                    </tr>
                                <?php } ?>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END CONTENT -->
        </div>
        <!-- END SIDEBAR & CONTENT -->
    </div>
</div>

<?php echo $this->view->getPartial('layouts/_footer'); ?>

</body>
<!-- END BODY -->
</html>