<!DOCTYPE html>
<!--[if IE 8]>
<html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]>
<html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->

<!-- Head BEGIN -->
<head>
    <meta charset="utf-8">
    <title><?php echo $this->obj->getValidateMessage('reset-password'); ?></title>
    <?php echo $this->view->getPartial('layouts/_meta') ?>
</head>
<!-- Head END -->

<!-- Body BEGIN -->
<body class="corporate">

<?php echo $this->view->getPartial('layouts/_header') ?>

<div class="main">
    <div class="container">
        <ul class="breadcrumb">
            <li><a href="/"><?php echo $this->obj->getValidateMessage('shouye'); ?></a></li>
            <li class="active"><?php echo $this->obj->getValidateMessage('reset-password'); ?></li>
        </ul>
        <!-- BEGIN SIDEBAR & CONTENT -->
        <div class="row margin-bottom-40">

            <?php echo $this->view->getPartial('layouts/_member_sidebar') ?>

            <!-- BEGIN CONTENT -->
            <div class="col-md-9 col-sm-9">
                <h1 class="h1-title"><?php echo $this->obj->getValidateMessage('reset-password'); ?></h1>
                <div class="content-form-page">
                    <div class="row">
                        <div class="col-md-7 col-sm-7">
                            <form class="form-horizontal form-without-legend" role="form">

                                <div class="form-group">
                                    <label for="old-password"
                                           class="col-lg-4 control-label"><?php echo $this->obj->getValidateMessage('old-password'); ?>
                                        <span class="require">*</span></label>
                                    <div class="col-lg-8">
                                        <input type="password" class="form-control" id="old-password">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="new-password"
                                           class="col-lg-4 control-label"><?php echo $this->obj->getValidateMessage('new-password'); ?>
                                        <span
                                                class="require">*</span></label>
                                    <div class="col-lg-8">
                                        <input type="password" class="form-control" id="new-password">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="repeat-password"
                                           class="col-lg-4 control-label"><?php echo $this->obj->getValidateMessage('repeat-password'); ?>
                                        <span
                                                class="require">*</span></label>
                                    <div class="col-lg-8">
                                        <input type="password" class="form-control" id="repeat-password">
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-lg-8 col-md-offset-4 padding-left-0 padding-top-20">
                                        <button type="submit" class="btn btn-primary" id="button-reset-password"
                                                onclick="reset_password();return false;"><?php echo $this->obj->getValidateMessage('queren'); ?>
                                        </button>
                                    </div>
                                </div>

                            </form>
                        </div>

                    </div>
                </div>
            </div>
            <!-- END CONTENT -->
        </div>
        <!-- END SIDEBAR & CONTENT -->
    </div>
</div>

<?php echo $this->view->getPartial('layouts/_footer'); ?>

</body>
<!-- END BODY -->
</html>