<!DOCTYPE html>

<!--[if IE 8]>
<html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]>
<html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->

<!-- Head BEGIN -->
<head>
    <meta charset="utf-8">
    <title><?php echo $title . ' - ' . $this->host['webtitle']; ?></title>

    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <meta content="Metronic Shop UI description" name="description">
    <meta content="Metronic Shop UI keywords" name="keywords">
    <meta content="keenthemes" name="author">

    <!-- Global styles START -->
    <link href="/shop/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="/shop/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Global styles END -->

    <!-- Page level plugin styles START -->
    <link href="/shop/assets/plugins/fancybox/source/jquery.fancybox.css" rel="stylesheet">
    <link href="/shop/assets/plugins/owl.carousel/assets/owl.carousel.css" rel="stylesheet">
    <link href="/shop/assets/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css">
    <link href="/shop/assets/plugins/jquery-ui/jquery-ui.css" rel="stylesheet" type="text/css"><!-- for slider-range -->
    <link href="/shop/assets/plugins/rateit/src/rateit.css" rel="stylesheet" type="text/css">
    <!-- Page level plugin styles END -->

    <!-- Theme styles START -->
    <link href="/shop/assets/pages/css/components.css" rel="stylesheet">
    <link href="/shop/assets/corporate/css/style.css" rel="stylesheet">
    <link href="/shop/assets/pages/css/style-shop.css" rel="stylesheet" type="text/css">
    <link href="/shop/assets/corporate/css/style-responsive.css" rel="stylesheet">
    <link href="/shop/assets/corporate/css/themes/red.css" rel="stylesheet" id="style-color">
    <link href="/shop/assets/corporate/css/custom.css" rel="stylesheet">
    <!-- Theme styles END -->
</head>
<!-- Head END -->

<!-- Body BEGIN -->
<body class="ecommerce">

<?php echo $this->view->getPartial('layouts/_header') ?>

<div class="main">
    <div class="container">
        <ul class="breadcrumb">
            <?php echo $breadcrumb; ?>
        </ul>

        <!-- BEGIN SIDEBAR & CONTENT -->
        <div class="row margin-bottom-40">

            <!-- BEGIN CONTENT -->
            <div class="col-md-12 col-sm-12 col-xs-12">

                <!-- BEGIN PRODUCT LIST -->
                <div class="child_product_list row product-list">

                    <?php if (count($page->items) > 0) { ?>
                        <!-- PRODUCT ITEM START -->
                        <div class="col-col-md-12 col-sm-12 col-xs-12">
                            <table class="table table-responsive table-hover table-bordered table-order">
                                <tr>
                                    <th>主图</th>
                                    <th>附图</th>
                                    <th>名称</th>
                                    <th>国际码</th>
                                    <th>价格</th>
                                    <th colspan="<?php echo $max_sum_sizecontents + 1; ?>">库存详情</th>
                                    <th>操作</th>
                                </tr>

                                <?php foreach ($page->items as $item) { ?>

                                    <tr>
                                        <input type="hidden" name="id" value="<?php echo $item['id'] ?>">
                                        <td rowspan="3"><a
                                                    href="/product/detail/<?php echo $item['productid']; ?>"><img
                                                        class="w80"
                                                        src="<?php echo $this->file_prex . $item['picture']; ?>"
                                                        alt="<?php echo $item['productname']; ?>"></a>
                                        </td>
                                        <td rowspan="3"><a
                                                    href="/product/detail/<?php echo $item['productid']; ?>"><img
                                                        class="w80"
                                                        src="<?php echo $this->file_prex . $item['picture2']; ?>"
                                                        alt="<?php echo $item['productname']; ?>"></a>
                                        </td>
                                        <td rowspan="3"><a
                                                    href="/product/detail/<?php echo $item['productid']; ?>"><?php echo $item['productname']; ?></a>
                                        </td>
                                        <td rowspan="3"><?php echo $item['wordcode']; ?></td>
                                        <td rowspan="3">
                                            <?php echo $this->currency; ?><?php echo $item['realprice']; ?>
                                        </td>
                                        <td>尺码组：</td>
                                        <?php if ($item['sum_sizecontents'] > 0) { ?>
                                            <?php foreach ($item['sizecontents'] as $sizecontent) { ?>
                                                <td><?php echo $sizecontent['sizecontentname']; ?></td>
                                            <?php } ?>
                                        <?php } else { ?>
                                            <?php for ($i = 0; $i < $max_sum_sizecontents; $i++) { ?>
                                                <td>&nbsp;</td>
                                            <?php } ?>
                                        <?php } ?>
                                        <td rowspan="3">
                                            <?php if ($item['sum_sizecontents'] > 0) { ?>
                                                <button class="btn btn-primary" type="submit"
                                                        onclick="addbuycar(this, <?php echo $item['id'] ?>);return false;">
                                                    加入购物车
                                                </button>
                                            <?php } else { ?>
                                                <span class="red">不可操作</span>
                                            <?php } ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>库存数：</td>
                                        <?php if ($item['sum_sizecontents'] > 0) { ?>
                                            <?php foreach ($item['sizecontents'] as $sizecontent) { ?>
                                                <td><?php echo $sizecontent['sumatory']; ?></td>
                                            <?php } ?>
                                        <?php } else { ?>
                                            <?php for ($i = 0; $i < $max_sum_sizecontents; $i++) { ?>
                                                <td>&nbsp;</td>
                                            <?php } ?>
                                        <?php } ?>

                                    </tr>
                                    <tr>
                                        <td>订购数：</td>
                                        <?php if ($item['sum_sizecontents'] > 0) { ?>
                                            <?php foreach ($item['sizecontents'] as $sizecontent) { ?>
                                                <td><input class="table-w30"
                                                           data-id="<?php echo $sizecontent['sizecontentid']; ?>"
                                                           type="text"/>
                                                </td>
                                            <?php } ?>
                                        <?php } else { ?>
                                            <?php for ($i = 0; $i < $max_sum_sizecontents; $i++) { ?>
                                                <td>&nbsp;</td>
                                            <?php } ?>
                                        <?php } ?>
                                    </tr>


                                <?php } ?>

                            </table>
                        </div>
                        <!-- PRODUCT ITEM END -->


                    <?php } else { ?>
                        <div class="col-md-12 col-sm-12 col-xs-12">当前分类暂无商品</div>
                    <?php } ?>

                </div>
                <!-- END PRODUCT LIST -->

                <!-- BEGIN PAGINATOR -->
                <?php if ($page->total_pages > 1) { ?>
                    <div class="page_margin pull-right">
                        <ul class="pagination ">
                            <li class="<?php echo $page->current <= 1 ? 'disabled' : ''; ?>"><a
                                        href="<?php echo $this->url->get('childproductgroup/detail/' . $id, ['page' => $page->before]); ?>">&laquo;</a>
                            </li>
                            <?php for ($i = 1; $i <= $page->total_pages; $i++) { ?>
                                <li class="<?php echo $page->current == $i ? 'active' : ''; ?>"><a
                                            href="<?php echo $this->url->get('childproductgroup/detail/' . $id, ['page' => $i]); ?>"><?php echo $i; ?></a>
                                </li>
                            <?php } ?>
                            <li class="<?php echo $page->current >= $page->total_pages ? 'disabled' : ''; ?>"><a
                                        href="<?php echo $this->url->get('childproductgroup/detail/' . $id, ['page' => $page->next]); ?>">&raquo;</a>
                            </li>
                        </ul>
                    </div>
                <?php } ?>
                <!-- END PAGINATOR -->

            </div>
            <!-- END CONTENT -->

        </div>
        <!-- END SIDEBAR & CONTENT -->


    </div>
</div>

<?php echo $this->view->getPartial('layouts/_footer'); ?>

</body>
<!-- END BODY -->
</html>