<div id="ell">
<el-row>
  <el-col :span="24">
  <el-button type="primary" @click="showFormToCreate()"><?=$system_language["button-create"]?></el-button>
  </el-col>
</el-row>

<el-row :gutter="20">
  <el-col :span="24">
    <simple-admin-tablelist ref="tablelist" v-bind="props" :onclickupdate="showFormToEdit"></simple-admin-tablelist>
  </el-col>
</el-row>

<el-dialog :title="labels[action_type][0]" :visible.sync="dialogVisible" :center="true" width="80%">
  <el-tabs type="border-card" @tab-click="onTabClick">
    <el-tab-pane label="<?=$system_language["user-setting"]?>">      
      
        <el-row>
          <el-col :span="5">
            <simple-avatar v-model="form.picture"></simple-avatar>
          </el-col>
          
          <el-col :span="5">
            <simple-avatar v-model="form.picture2"></simple-avatar>
          </el-col>
          
          <el-col :span="14">
          <el-form ref="form" :model="form" label-width="80px">
  <el-form-item label="<?=$system_language["shangpinmingcheng"]?>">
    <el-input v-model="form.name"></el-input>
  </el-form-item>
  <el-form-item label="<?=$system_language["shangpinhuohao"]?>">
    <el-input v-model="form.name"></el-input>
  </el-form-item>

  
</el-form>
          </el-col>
        </el-row>
        <el-form  class="user-form" :model="form" label-width="85px" :inline="true" style="width:100%;" size="mini">
        <el-row :gutter="0">
            <el-col :span="8">
              
                <el-form-item label="<?=$system_language["pinpai"]?>">
                  <simple-select v-model="form.brand" source="brand" :lang="lang">
                  </simple-select>
                </el-form-item>
                
                <el-form-item label="<?=$system_language["pinlei"]?>">
                  <simple-select v-model="form.brandtype" source="brandgroup" :lang="lang">
                  </simple-select>
                </el-form-item>
                
                <el-form-item label="<?=$system_language["zipinlei"]?>">
                  <simple-select v-model="form.childbrand" source="childproductgroup" :lang="lang">
                  </simple-select>
                </el-form-item>
                
                <el-form-item label="<?=$system_language["chandi"]?>">
                  <select-dialog v-model="form.origin" source="country" :lang="lang">
                  </select-dialog>
                </el-form-item>
        
                <el-form-item label="<?=$system_language["pinpaiseban"]?>">
                  <select-dialog v-model="form.brandcolor" source="colortemplate" :lang="lang">
                  </select-dialog>
                </el-form-item>
                
                <el-form-item label="<?=$system_language["caizhizhuangtai"]?>">
                  <select-dialog v-model="form.materialstatus" source="materialstatus" :lang="lang">
                  </select-dialog>
                </el-form-item>
                
                <el-form-item label="<?=$system_language["changhefengge"]?>">
                  <select-dialog v-model="form.occasion" source="occasionsstyle" style="width:150" :lang="lang">
                  </select-dialog>
                </el-form-item>
        
                
                <el-form-item label="<?=$system_language["shangpinchicun"]?>">
                  <simple-select v-model="form.ulnarinch" source="ulnarinch" style="width:150" :lang="lang">
                  </simple-select>
                </el-form-item>
                
                <el-form-item label="<?=$system_language["shangpinmiaoshu"]?>">
                  <select-dialog v-model="form.occasion" source="occasionsstyle" style="width:150" :lang="lang">
                  </select-dialog>
                </el-form-item>
                
                <el-form-item label="<?=$system_language["bihefangshi"]?>">
                  <select-dialog v-model="form.closeway" source="occasionsstyle" style="width:150" :lang="lang">
                  </select-dialog>
                </el-form-item>
              
                           
            </el-col>
            
            <el-col :span="8">
                <el-form-item label="<?=$system_language["niandai"]?>">
                  <select-dialog v-model="form.ageseason" source="ageseason" style="width:150" :lang="lang">
                  </select-dialog>
                </el-form-item>
                
                <el-form-item label="<?=$system_language["shangpinbieming"]?>">
                  <select-dialog v-model="form.aliases" source="aliases" style="width:150" :lang="lang">
                  </select-dialog>
                </el-form-item>   
                
                <el-form-item label="<?=$system_language["shangpinxilie"]?>">
                  <select-dialog v-model="form.series_id" source="aliases" style="width:150" :lang="lang">
                  </select-dialog>
                </el-form-item>
                
                <el-form-item label="<?=$system_language["shangpinzixilie"]?>">
                  <select-dialog v-model="form.series_id2" source="aliases" style="width:150" :lang="lang">
                  </select-dialog>
                </el-form-item>
                
                <el-form-item label="<?=$system_language["fanghanzhishu"]?>">
                  <simple-select v-model="form.winterproofing" source="winterproofing" style="width:150" :lang="lang">
                  </simple-select>
                </el-form-item>
                
                <el-form-item label="<?=$system_language["chengjiaojiage"]?>">
                  <el-input placeholder="" v-model="form.realprice" class="input-with-select">
                    <select-currency v-model="form.retailpricecurrency" slot="prepend">
                    </select-currency>
                  </el-input>
                </el-form-item>
        
                <el-form-item label="<?=$system_language["chuchangjia"]?>">
                  <el-input placeholder="" v-model="form.factoryprice" class="input-with-select">
                    <select-currency v-model="form.factorypricecurrency" slot="prepend">
                    </select-currency>
                  </el-input>
                </el-form-item>
                
                <el-form-item label="<?=$system_language["guojilingshoujia"]?>">
                  <el-input placeholder="" v-model="form.wordprice" class="input-with-select">
                    <select-currency v-model="form.wordpricecurrency" slot="prepend">
                    </select-currency>
                  </el-input>
                </el-form-item>
                
                <el-form-item label="<?=$system_language["guoneilingshoujia"]?>">
                  <el-input v-model="form.nationalprice"></el-input>
                </el-form-item>
        
                
                <el-form-item label="<?=$system_language["chicunbeizhu"]?>">
                  <el-input v-model="form.ulnarinch_memo"></el-input>
                </el-form-item>
            </el-col>
            <el-col :span="8">
                <el-form-item label="<?=$system_language["xingbie"]?>">
                  <select-dialog v-model="form.gender" source="gender" style="width:150" :lang="lang">
                  </select-dialog>
                </el-form-item>

                <el-form-item label="<?=$system_language["jijie"]?>">
                  <select-dialog v-model="form.season" source="season" style="width:150" :lang="lang">
                  </select-dialog>
                </el-form-item>
              
                <el-form-item label="<?=$system_language["chima"]?>">
                  <simple-select v-model="form.ulnarinch" source="sizetop" :lang="lang">
                  </simple-select>
                </el-form-item>
                
                <el-form-item label="<?=$system_language["chimaguige"]?>">
                  <simple-select v-model="form.ulnarinch" source="sizetop" :lang="lang">
                  </simple-select>
                </el-form-item>
                
             <el-form-item label="<?=$system_language["zhixingbiaozhun"]?>">
              <simple-select v-model="form.ulnarinch" source="sizetop" :lang="lang">
              </simple-select>
            </el-form-item>
            
            <el-form-item label="<?=$system_language["anquanleibie"]?>">
              <simple-select v-model="form.ulnarinch" source="sizetop" :lang="lang">
              </simple-select>
            </el-form-item>
            
            <el-form-item label="<?=$system_language["guigexinghao"]?>">
              <el-input v-model="form.password"></el-input>
            </el-form-item>
            
            <el-form-item label="<?=$system_language["zuihouruku"]?>">
              <el-input v-model="form.password"></el-input>
            </el-form-item>
            
            <el-form-item label="<?=$system_language["jiandangshijian"]?>">
              <el-input v-model="form.sys_create_date" disabled></el-input>
            </el-form-item>
            
            <el-form-item label="<?=$system_language["jiandangren"]?>">
              <el-input v-model="form.password" disabled></el-input>
            </el-form-item>
    
            
          </el-col>
        </el-row>
      </el-form>
    </el-tab-pane>
  
    <el-tab-pane label="<?=$system_language["sale-port"]?>">
      <el-checkbox-group v-model="form.sale_port">
        <el-checkbox v-for="item in sale_port_list" :label="item.value">{{item.label}}</el-checkbox>
      </el-checkbox-group>    
    </el-tab-pane>
  <el-tab-pane label="<?=$system_language["jiesuandanwei"]?>">定时任务补偿</el-tab-pane>
    <el-tab-pane label="<?=$system_language["cangku"]?>">
      <el-checkbox-group v-model="form.cangku">
        <el-checkbox v-for="item in cangku_list" :label="item.value">{{item.label}}</el-checkbox>
      </el-checkbox-group> 
    </el-tab-pane>
    
    <el-tab-pane label="<?=$system_language["jiagedan"]?>">
      <el-checkbox-group v-model="form.jiagedan">
        <el-checkbox v-for="item in jiagedan_list" :label="item.value">{{item.label}}</el-checkbox>
      </el-checkbox-group> 
    </el-tab-pane>
  <el-tab-pane label="<?=$system_language["gerenshezhi"]?>">定时任务补偿</el-tab-pane>
  </el-tabs>
  
  <span slot="footer" class="dialog-footer">
    <el-button type="primary" @click="onSubmit">{{labels[action_type][1]}}</el-button>
  </span>
</el-dialog>
</div>

<script>
$(document).ready(function(){
    var props = {
        columns:[
            {
                name:"login_name", 
                label:$ASAL.dengluming, 
                is_create:true, 
                is_update:true, 
                is_show:true, 
                is_focus:true,
                width:200
            },
            {
                name:"real_name", 
                label:$ASAL.xingming, 
                is_create:true, 
                is_update:true, 
                is_show:true, 
                width:200, 
                is_focus:true
            }
        ],
        controller:"product"
    }
    
    new Vue({
        el:"#ell",
        data() {
            return {
                dialogVisible:false,
                lang:$ASAL.lang,
                form: {
                    id:'',
                    decade:"",
                    brand:'',
                    brandtype:"",
                    childbrand:"",
                    productsize:"",
                    origin:"",
                    brandcolor:"",
                    security:"",
                    execution:"",
                    material:"",
                    productparst:"",
                    occasion:"",
                    producttemplate:"",
                    materialstatus:"",
                    spring:"",
                    picture:"",
                    picture2:"",
                    summer:"",
                    autumn:"",
                    winter:"",
                    oldasacode:"",
                    officialwebsite:"",
                    oldbarcode:"",
                    laststoragedate:"",
                    aliases_1:"",
                    aliases_2:"",
                    aliases:"",
                    series_id:"",
                    series2_id:"",
                    ulnarinch:"",
                    vat:"",
                    tariff:"",
                    basecurrency:"",
                    baseprice:"",
                    entrymonth:"",
                    factoryprice:"",
                    factorypricecurrency:"",
                    realprice:"",
                    retailpricecurrency:"",
                    dutyparagraph:"",
                    orderprice:"",
                    orderpricecurrency:"",
                    retailprice:"",
                    groupid:"",
                    iskj:"",
                    bxzs:"",
                    hbzs:"",
                    rrzs:"",
                    tlzs:"",
                    salemethodid:"",
                    nationalprice:"",
                    taxrate:"",
                    isjh:"",
                    inlenth:"",
                    jdname:"",
                    winterproofing:"",
                    isfj:"",
                    discount:"",
                    ulnarinch_memo:"",
                    wordprice:"",
                    wordpricecurrency:"",
                    sys_create_stuff:"",
                    sys_create_date:"",
                    gender:"",
                    season:""
                },
                props:props,
                departs:[],
                country_list:[],
                bu_list:[],
                action_type:"create",
                labels:{
                    create:['<?=$system_language["xinjianyonghu"]?>','<?=$system_language["button-save"]?>'],
                    update:['<?=$system_language["yuangongxinxi"]?>','<?=$system_language["button-save"]?>']       
                },
                group_list:[{value:1,"label":"测试一"},{value:2,"label":"测试2"}],//分组信息
                sale_port_list:[{value:1,"label":"销售端口测试一"},{value:2,"label":"销售端口测试2"},{value:3,"label":"销售端口测试3"}],//销售端口信息
                cangku_list:[{value:1,"label":"仓库测试一"},{value:2,"label":"仓库测试2"},{value:3,"label":"仓库测试3"}],//仓库信息
                jiagedan_list:[{value:1,"label":"价格单测试一"},{value:2,"label":"价格单测试2"},{value:3,"label":"价格单测试3"}],//价格单信息
            }
        },
        methods: {
            onSubmit() {
                var self = this;
                if(self.form.id=="") {
                    $ASA.submit.call(self, "/"+props.controller+"/add", self.form, function(){
                        self.$refs.tablelist.appendRow($ASA.clone(self.form))
                        //self.dialogVisible = false
                    })
                }
                else {
                    $ASA.submit.call(self, "/"+props.controller+"/edit", self.form, function(){
                        $ASA.copyTo(self.form, self.row)
                        //self.dialogVisible = false
                    })
                }
            },
            onTabClick(tab){
                console.log(tab)
            },
            showFormToEdit(rowIndex, row){
                var self = this
                self.rowIndex = rowIndex;
                self.row = row;
                $ASA.copyTo(row, this.form)
                self.form.factoryprice = $ASA.round(self.form.factoryprice,2)
                self.form.realprice = $ASA.round(self.form.realprice,2)
                self.form.wordprice = $ASA.round(self.form.wordprice,2)
                self.form.nationalprice = $ASA.round(self.form.nationalprice,2)
    
                this.formTitle = $ASAL.xiugaixinxi;
                self.showDialog();
            },
            showDialog() {
                var self = this;
                 self.dialogVisible = true;
            },
            showFormToCreate() {
                var self = this;
                $ASA.empty(self.form)    
    
                self.formTitle = $ASAL.tianjiaxinxi;
                self.activeName = "info"
                self.showDialog();
            },
            handleEdit(rowIndex, row){
               window.location = "/user/edit?id="+row.id;
            },
            handleDelete(rowIndex, row) {
                var self = this;

                self.$confirm('此操作将永久删除该记录, 是否继续?', '提示', {
                    confirmButtonText: '确定',
                    cancelButtonText: '取消',
                    type: 'warning'
                }).then(() => {
                    $.get("/user/delete?id="+row.id, function(res){
                        if(res.messages.length>0) {
                            const h = self.$createElement;
                            var message = h("ul", null, res.messages.map(function(v){
                                return h("li",null,v)
                            }))

                            self.$alert(message, '错误提示', {
                                confirmButtonText: '确定'
                            });
                        }
                        else {
                            self.$delete(self.tableData,rowIndex)
                            self.$message({
                                message: '删除成功',
                                type: 'success'
                            });
                        }
                    },"json")
                });
            }
        }
    })
})
</script>
<style>
    .user-form .el-input__inner {
        width:200px;
    }
    
    .user-form .el-input-group {
        width:200px;
    }
    
    .user-form .el-input-group .el-input__inner {
        width:155px;
    }
    .user-form .el-input-group--prepend .el-input__inner {
        width:99px;
    }
    
    .user-form .el-form-item__content {
        width:200px;
    }
    
    .user-form .el-date-editor.el-input, .el-date-editor.el-input__inner {
        width:150px
    }
    
    .el-form-item--mini.el-form-item, .el-form-item--small.el-form-item {
        margin-bottom: 5px;
    }
    
    .user-form .el-checkbox {
        margin-right:12px;    
    }
    
    .user-form .el-checkbox__label {
        padding-left:4px;    
    }
    
</style>

