<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar Menu -->
        <ul class="sidebar-menu" data-widget="tree">
            <!-- Optionally, you can add icons to the links -->

            <?php if ($this->request->get('_url') == '/manager/set') { ?>
                <li class="active"><a href="/manager/set"><i class="fa fa-circle-o"></i> 一键初始化</a></li>
            <?php } else { ?>
                <li><a href="/manager/set"><i class="fa fa-circle-o"></i> 一键初始化</a></li>
            <?php } ?>

            <?php if ($this->request->get('_url') == '/manager/statis') { ?>
                <li class="active"><a href="/manager/statis"><i class="fa fa-circle-o"></i> 一键统计</a></li>
            <?php } else { ?>
                <li><a href="/manager/statis"><i class="fa fa-circle-o"></i> 一键统计</a></li>
            <?php } ?>

            <!--            <li class="treeview">-->
            <!--                <a href="#">-->
            <!--                    <i class="fa fa-dashboard"></i>-->
            <!--                    <span>新公司初始化</span>-->
            <!--                    <span class="pull-right-container">-->
            <!--                        <i class="fa fa-angle-left pull-right"></i>-->
            <!--                    </span>-->
            <!--                </a>-->
            <!--                <ul class="treeview-menu">-->
            <!--                    --><?php //if ($this->request->get('_url') == '/manager/set') { ?>
            <!--                        <li class="active"><a href="/manager/set"><i class="fa fa-circle-o"></i> 一键初始化</a></li>-->
            <!--                    --><?php //} else { ?>
            <!--                        <li><a href="/manager/set"><i class="fa fa-circle-o"></i> 一键初始化</a></li>-->
            <!--                    --><?php //} ?>
            <!--                </ul>-->
            <!--            </li>-->

            <!--            <li class="treeview">-->
            <!--                <a href="#">-->
            <!--                    <i class="fa fa-dashboard"></i>-->
            <!--                    <span>统计</span>-->
            <!--                    <span class="pull-right-container">-->
            <!--                        <i class="fa fa-angle-left pull-right"></i>-->
            <!--                    </span>-->
            <!--                </a>-->
            <!--                <ul class="treeview-menu">-->
            <!--                    --><?php //if ($this->request->get('_url') == '/manager/statis') { ?>
            <!--                        <li class="active"><a href="/manager/statis"><i class="fa fa-circle-o"></i> 一键统计</a></li>-->
            <!--                    --><?php //} else { ?>
            <!--                        <li><a href="/manager/statis"><i class="fa fa-circle-o"></i> 一键统计</a></li>-->
            <!--                    --><?php //} ?>
            <!--                </ul>-->
            <!--            </li>-->

        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>
<!-- Left side column End. contains the logo and sidebar -->