<div id="ell">
  <simple-admin-page v-bind="props" ref="page"></simple-admin-page>
</div>

<div id="ell2">
  <el-dialog class="user-form" :title="title" :visible.sync="dialogVisible" :center="true" width="80%">
    <multiple-admin-page v-bind="props" ref="page2"></multiple-admin-page>
  </el-dialog>
</div>
<script>
$(document).ready(function(){
    var props = {
        columns:[
            {name:"name", label:"<?=$system_language['huiyuanming']?>", class:"width2"},
            {name:"gender", label:"<?=$system_language['xingbie']?>", class:"width2", type:"select", source:"gender2"},
            
            {name:"phoneno", label:"<?=$system_language['shouji']?>", class:"width2", is_hide:true},     
            {name:"birthday", label:"<?=$system_language['shengri']?>", class:"width2", type:"date"},       
            {name:"zipcode", label:"<?=$system_language['youbian']?>", class:"width2", is_hide:true},
            {name:"qq", label:"<?=$system_language['qq']?>", class:"width2", is_hide:true},
            {name:"wechat", label:"<?=$system_language['weixin']?>", class:"width2", is_hide:true},
            {name:"microblog", label:"<?=$system_language['weibo']?>", class:"width2", is_hide:true},
            {name:"address", label:"<?=$system_language['dizhi']?>", class:"width1", is_hide:true},            
            {name:"email", label:"<?=$system_language['email']?>", class:"width1", is_hide:true},         
        ],
        options:{
            dialogWidth:'700px',
            formSize:'small',
            inline:true
        },
        controller:"member"
    }
        
    var options = {
        props:{
            columns:[            
                {name:"name", label:"<?=$system_language["zileimingcheng"]?>", is_multiple:true, is_focus:true},
                {name:"childcode", label:"<?=$system_language["zileibianma"]?>"},
                {name:"producttemplateid", label:"<?=$system_language["chimamoban"]?>", type:'select', source:"sizetop"},
                {name:"weight", label:"<?=$system_language["maozhong"]?>"},
            ],
            controller:"childproductgroup",
            key_column:"name",
            base:{
                productgroupid:""    
            }
        },
        dialogVisible:false,
        title:""
    }
    
    new Vue({
        el:"#ell",
        data() {
            return {
                props:props,
                props2:options.props
            }
        }
    })
    
    var childgroup = new Vue({
        el:"#ell2",
        data() {
            return options
        }
    })
})
</script>

