<div id="ell">
<multiple-admin-page v-bind="props" ref="page"></multiple-admin-page>
</div>

<script>
$(document).ready(function(){
    var props = {
        columns:[
            {name:"code", label:"<?=$system_language['caizhidaima']?>", is_focus:true},
            {name:"name", label:"<?=$system_language['caizhimingcheng']?>", is_multiple:true, is_focus:true},
            {name:"englishname", label:"<?=$system_language['yingwenmingcheng']?>"}
        ],
        controller:"material",
        key_column:"name"
    }
    
    new Vue({
        el:"#ell",
        data() {
            return {
                props:props   
            }
        }
    })
})
</script>
