<div id="ell">
<multiple-admin-page v-bind="props" ref="page"></multiple-admin-page>
</div>

<script>
$(document).ready(function(){
    var props = {
        columns:[
            {name:"executionname", label:"<?=$system_language['mingcheng']?>", is_create:true, is_update:true, is_show:true, width:200, is_focus:true},
            {name:"executionmatter", label:"<?=$system_language['shixiang']?>", is_create:true, is_update:true, is_show:true, width:200, type:"textarea"},
            {name:"note", label:"<?=$system_language['beizhu']?>", is_create:true, is_update:true, is_show:true, width:200, type:"textarea"}
        ],
        options:{
            dialogWidth:"35%"
        },
        default_language:'<?=$__default_language?>',
        controller:"executioncategory"
    }
    
    new Vue({
        el:"#ell",
        data() {
            return {
                props:props   
            }
        }
    })
})
</script>
<style>
</style>

