<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="icon" href="/favicon.ico">
    <title><?=isset($__title)?$__title:"ERP"?> - ASA</title>
    <script src="/js/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/ramda/0.25.0/ramda.min.js"></script>
    <script src="/common/systemlanguage?<?=$__sytem_time?>"></script>
    <script src="/js/erp.js?<?=$__sytem_time?>"></script>
    <script src="/js/shop.js?<?=$__sytem_time?>"></script>
  </head>


</style>
<body>


<script>
$(document).ready(function(){
    ASAP.getLabel("user","cn","1,2",function(text){
        console.log(text)
    })
})
</script>
  </body>
</html>
