<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="icon" href="/favicon.ico">
    <title><?=isset($__title)?$__title:"ERP"?> - ASA</title>
    <script src="https://unpkg.com/vue@2.6.9/dist/vue.js"></script>
    <script src="https://unpkg.com/vuex@3.1.0/dist/vuex.js"></script>
    <script src="https://unpkg.com/vue-router@2.0.0/dist/vue-router.js"></script>
    

    <!-- 引入样式 -->
    <link rel="stylesheet" href="https://unpkg.com/element-ui/lib/theme-chalk/index.css">
    <!-- 引入组件库 -->
    <script src="https://unpkg.com/element-ui/lib/index.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/ramda/0.25.0/ramda.min.js"></script>
    <script src="/js/jquery.min.js"></script>
    <script src="/common/systemlanguage?<?=$__sytem_time?>"></script>
    <script src="/js/erp.js?<?=$__sytem_time?>"></script>
    <script src="/js/asa.js?<?=$__sytem_time?>"></script>
    <script src="/js/props.js?<?=$__sytem_time?>"></script>
  </head>

  <style>
  .el-header {
    background-color: #B3C0D1;
    color: #333;
    line-height: 60px;
  }
  
  .el-footer{
    clear: both;
    display: block;
    text-align: center;    
    margin: 0px auto;
    bottom: 100px;
  }

  .el-aside {
    color: #333;
  }  
  .el-row {
    margin-bottom: 20px;
    &:last-child {
      margin-bottom: 0;
    }
  }

  .bg-purple-dark {
    background: #99a9bf;
  }
  .bg-purple {
    background: #d3dce6;
  }
  .bg-purple-light {
    background: #e5e9f2;
  }
  .grid-content {
    border-radius: 4px;
    min-height: 36px;
  }
  .row-bg {
    padding: 10px 0;
    background-color: #f9fafc;
  }
  
  .el-menu-item a {
    color:white;
    text-decoration : none  
  }
  
  #ell{margin:5px;}


    .user-form .width2 .el-input__inner {
        width:200px;
    }

    .user-form  .width2 .el-input-group {
        width:200px;
    }
    
    .user-form .width1 .el-input__inner {
        width:510px;
    }
    
    .user-form .width1 .el-textarea__inner {
        width:510px;
    }
    
    .user-form .width2 .el-date-editor.el-input, .el-date-editor.el-input__inner {
        width:150px
    }

    .user-form .width2 .el-input-group .el-input__inner {
        width:155px;
    }
    .user-form .width2 .el-input-group--prepend .el-input__inner {
        width:99px;
    }

    .user-form /width2 .el-form-item__content {
        width:200px;
    }

    .el-form-item--mini.el-form-item, .el-form-item--small.el-form-item {
        margin-bottom: 5px;
    }

    .user-form .el-checkbox {
        margin-right:12px;
    }

    .user-form .el-checkbox__label {
        padding-left:4px;
    }

    .order-form .el-input__inner {
        width:200px;
    }

    .order-form .el-input-group {
        width:200px;
    }

    .order-form .el-input-group .el-input__inner {
        width:155px;
    }
    .order-form .el-input-group--prepend .el-input__inner {
        width:99px;
    }

    .order-form .el-form-item__content {
        width:200px;
    }

    .order-form .el-date-editor.el-input, .el-date-editor.el-input__inner {
        width:150px
    }

    .el-form-item--mini.el-form-item, .el-form-item--small.el-form-item {
        margin-bottom: 5px;
    }

    .order-form .font12 label{
        font-size:12px;
    }

    .order-form .el-checkbox {
        margin-right:12px;
    }

    .order-form .el-checkbox__label {
        padding-left:4px;
    }

    .login-container {
    /*box-shadow: 0 0px 8px 0 rgba(0, 0, 0, 0.06), 0 1px 0px 0 rgba(0, 0, 0, 0.02);*/
    -webkit-border-radius: 5px;
    border-radius: 5px;
    -moz-border-radius: 5px;
    background-clip: padding-box;
    margin: 180px auto;
    width: 350px;
    padding: 35px 35px 15px 35px;
    background: #fff;
    border: 1px solid #eaeaea;
    box-shadow: 0 0 25px #cac6c6;
    .title {
      margin: 0px auto 40px auto;
      text-align: center;
      color: #505458;
    }
    .remember {
      margin: 0px 0px 35px 0px;
    }
  }

  .avatar-uploader .el-upload {
    border: 1px dashed #d9d9d9;
    border-radius: 6px;
    cursor: pointer;
    position: relative;
    overflow: hidden;
  }
  .avatar-uploader .el-upload:hover {
    border-color: #409EFF;
  }
  .avatar-uploader-icon {
    font-size: 28px;
    color: #8c939d;
    width: 148px;
    height: 148px;
    line-height: 148px;
    text-align: center;
  }
  .avatar {
    width: 148px;
    height: 148px;
    display: block;
  }

  .el-table .warning-row {
    background: oldlace;
  }

  .el-table .el-table__body .success-row {
    color: red !important;
    background: rgba(103,194,58,.2) !important;
  }

</style>
<body>

  <div id="ell" style="width:100%">
<el-row :gutter="20">
  <el-col :span="24">
    <el-form ref="form" :model="form" label-width="80px">
      <el-form-item label="表明">
        <el-input v-model="form.name"></el-input>
      </el-form-item>

      <el-form-item label="说明">
        <el-input v-model="form.description"></el-input>
      </el-form-item>
      
      <el-form-item label="Controller基类">
        <el-select v-model="form.base_controller" placeholder="请选择">
          <el-option v-for="item in options" :key="item.value" :label="item.label" :value="item.value"></el-option>
        </el-select>
      </el-form-item>
      
      

      <el-form-item label="去掉前缀">
        <el-checkbox v-model="form.trim_prex">Controller去掉前缀</el-checkbox>
      </el-form-item>

      <el-form-item label="Controller">
        <textarea style="width:100%;height:200px;" :form="form" id="model">
{{'<'}}?php
namespace Asa\Erp;
use Phalcon\Validation;
use Phalcon\Validation\Validator\Between;
use Phalcon\Validation\Validator\Uniqueness;

/**
 * {{form.description}}
 */
class {{form.model}} extends BaseModel
{
    public function initialize()
    {
        parent::initialize();
        $this->setSource('{{form.name}}');
    }

    public function validation() {
        $validator = new Validation();

//        $validator->add(
//            "age",
//            new Between(
//                [
//                    "minimum" => 18,
//                    "maximum" => 60,
//                    "message" => "年龄必须是18~60岁",
//                ]
//            )
//        );
//
//        $validator->add(
//            'name',
//            new Uniqueness(
//                [
//                    'message' => '姓名不能重复',
//                ]
//            )
//        );

        return $this->validate($validator);
    }
}
</textarea>
      </el-form-item>

      <el-form-item label="Controller">
        <textarea style="width:100%;height:200px;" :form="form" id="controller">
{{'<'}}?php
namespace Multiple\Home\Controllers;

use Phalcon\Mvc\Controller;
use Phalcon\Mvc\View;
use Asa\Erp\{{form.model}};

/**
 * {{form.description}}
 */
class {{form.controller}} extends {{form.base_controller}} {
    public function initialize() {
        parent::initialize();

        $this->setModelName('Asa\\Erp\\{{form.model}}');
    }
}
</textarea>
      </el-form-item>


      <el-form-item>
        <el-button type="primary" @click="onSubmit">生成代码</el-button>
        <el-button type="primary" @click="onSave">保存代码</el-button>
      </el-form-item>
    </el-form>


  </el-col>
</el-row>

</div>

<script>
$(document).ready(function(){
    function ucfirst(s) {
        s = s.toLowerCase();
        return s.substring(0,1).toUpperCase()+s.substring(1);
    }

    function convertName(s) {
        var arr = s.split('_');
        return arr.map(function(item){
            return ucfirst(item)
        }).join("");
    }

    new Vue({
        el:"#ell",
        data() {
            return {
                form: {
                    name: '',
                    model: '',
                    controller: '',
                    base_controller:"AdminController",
                    description:"",
                    path:'',
                    trim_prex:true
                },
                options: [{
                    value: 'AdminController',
                    label: 'AdminController'
                }, {
                    value: 'ZadminController',
                    label: '多语言基础资料'
                }, {
                    value: 'CadminController',
                    label: '用户录入的表'
                }],
                value: ''
            }
        },
        methods: {
            onSubmit() {
                var arr = this.form.name.split('_');
                this.form.model = convertName(this.form.name)
                
                var tmp;
                if(this.form.trim_prex) {
                    tmp = convertName(this.form.name.replace(/^[a-z]+_/,"").replace(/_/g,""))
                }
                else {
                    tmp = convertName(this.form.name.replace(/_/g,""))
                }
                this.form.controller = tmp + "Controller"
                this.form.path = '/'+ tmp.substring(0,1).toLowerCase()+tmp.substring(1);
            },
            onSave() {
                var form = this.form; 
                var self = this; 
                $ASA.submit.call(self, "/index/save", {model:$("#model").val(), controller:$("#controller").val(), modelName:form.model, controllerName:form.controller}, function(){
                    self.$alert(self.form.path, '标题名称', {
                        confirmButtonText: '确定'
                    });
                })
            }
        }
    })
})
</script>
  </body>
</html>
