
<div id="ell">
  <multiple-admin-page v-bind="props" ref="page"></multiple-admin-page>
</div>

<script>
$(document).ready(function(){
    var base = {
        brandid:"",
        lang_code:""
    }
    var aliases = {
        columns:[
            {name:"name", label:"<?=$system_language['biemingmingcheng']?>", is_create:true, is_update:true, is_show:true, width:150},
            {name:"code", label:"<?=$system_language['biemingbianma']?>", is_create:true, is_update:true, is_show:true, width:150},
            {name:"brandid", label:"品牌", is_create:false, is_update:false, is_show:false, is_hidden:true}
        ],
        options:{
            dialogWidth:"35%"
        },
        controller:"aliases",
        base:base
    }
        
    var props = {
        columns:[
            {name:"name", label:"<?=$system_language["pinpaimingcheng"]?>", is_multiple:true, is_focus:true},
            {name:"code", label:"<?=$system_language["pinpaibianhao"]?>"},
            {name:"countryid", label:"<?=$system_language["guishuguojia"]?>", type:"select", source:"country"},
            {name:"brandgroupid", label:"<?=$system_language["pinpaifenlei"]?>", type:"select", source:"brandgroup"},
            {name:"memo", label:"<?=$system_language["memo"]?>", type:"textarea"},
            {name:"officialwebsite", label:"<?=$system_language["guanwangdizhi"]?>"}            
        ],
        options:{
            dialogWidth:'30%',
            formSize:'small',
            inline:false
        },
        controller:"brand",
        key_column:"name"
        
    }

    new Vue({
        el:"#ell",
        data() {
            return {
                props:props  
            }
        }
    })
})
</script>

