
<div id="ell">
  <el-row>
      <el-col :span="24">
        <el-button type="primary" @click="showFormToCreate()"><?=$system_language['xinjian']?></el-button>
      </el-col>
    </el-row>

    <el-row :gutter="20">
      <el-col :span="24">
        <simple-admin-tablelist ref="tablelist" v-bind="props" :onclickupdate="showFormToEdit"></simple-admin-tablelist>
      </el-col>
    </el-row>
  

  <asa-order-dialog :visible.sync="visibleDialog" :data="info" @change="onChange"></asa-order-dialog>
</div>

<script>
$(document).ready(function(){
var log = function(name) {

    return function() {
        var arr = Array.prototype.slice.call(arguments)
        arr.unshift("<"+name+">")
        console.log.apply(console, arr);
    }
}

var mylog = log("changwei")
mylog(1,2,3)
    var props = {
        columns:[
            {name:"orderno", label:"<?=$system_language['dingdanbianhao']?>"},
            {name:"bussinesstype", label:"<?=$system_language['yewuleixing']?>", type:'select', source:"bussinesstype"},
            //{name:"city", label:"<?=$system_language['chengshi']?>"},
            //{name:"address", label:"<?=$system_language['dizhi']?>"},
            //{name:"zipcode", label:"<?=$system_language['youbian']?>"}, 
            
            //{name:"contact", label:"<?=$system_language['lianxiren']?>"}, 
            //{name:"mobile", label:"<?=$system_language['yidongdianhua']?>"},
           // {name:"fax", label:"<?=$system_language['chuanzhen']?>"},
            //{name:"code", label:"<?=$system_language['bianhao']?>"},
            //{name:"othercontact", label:"<?=$system_language['qitalianxifangshi']?>"},
            //{name:"is_real", label:"<?=$system_language['shifoukeyong']?>", type:"switch"}
        ],
        controller:"order"
    }
            
    new Vue({
        el:"#ell",
        data() {
            return {
                props:props,
                visibleDialog:false,
                pro:false,
                info:{},
                rowIndex:""
                
            }
        },
        methods:{
            showForm() {
                this.visibleDialog = true;   
            },
            showFormToCreate() {
                this.info = {}
                this.rowIndex = ""
                this.showForm()
            },
            showFormToEdit(rowIndex, row) {
                this.info = row;
                this.rowIndex = rowIndex
                console.log(row)
                this.showForm()
            },
            onChange(form) {
                let self = this
                if(!self.rowIndex) {
                    self.$refs.tablelist.appendRow($ASA.clone(form))
                }
                else {
                    var row = self.$refs.tablelist.getRow(self.rowIndex)
                    $ASA.copyTo(form, row)
                }
            }
        }
    })
})
</script>
<style>
</style>

