<div id="ell">
<multiple-admin-page v-bind="props" ref="page"></multiple-admin-page>
</div>

<div id="ell2">
  <el-dialog class="user-form" :title="''" :visible.sync="dialogVisible" :center="true" width="80%">
    <multiple-admin-page v-bind="props" ref="page2"></multiple-admin-page>
  </el-dialog>
</div>
<script>
$(document).ready(function(){
    var props = {
        columns:[            
            {name:"name", label:"<?=$system_language["mingcheng"]?>",is_multiple:true,is_focus:true},
            //{name:"color_name", label:"<?=$system_language["mingcheng"]?>"},
            {name:"code", label:"<?=$system_language["asabianhao"]?>"},
            //{name:"colortype", label:"<?=$system_language["yansefenlei"]?>"},
            {name:"picture", label:"<?=$system_language["yanseseban"]?>", type:"upload",multiple:false,limit:1,is_image:true, image_width:60,image_height:60}
        ],
        controller:"colortemplate",
        key_column:"name"
    }
    /*
    var props2 = {
        columns:[            
            {name:"templatename", label:"<?=$system_language["biaoti"]?>", is_create:true, is_update:true, is_show:true, width:200, is_focus:true},
            {name:"sortnum", label:"<?=$system_language["xuhao"]?>", is_create:true, is_update:true, is_show:true, width:200, disable_change:true, is_focus:true}
        ],
        options:{
            dialogWidth:"35%"
        },
        default_language:'<?=$system_language["code"]?>',
        controller:"templatemanage",
        base:{
            tempid:""    
        }
    }
    
    var options = {
        props:props2,
        dialogVisible:false
    }*/
    
    var brandgroup = new Vue({
        el:"#ell",
        data() {
            return {
                props:props   
            }
        }
    })
    /*
    var childgroup = new Vue({
        el:"#ell2",
        data() {
            return options
        }
    })*/
})
</script>
<style>
</style>

