
<div id="ell">
<multiple-admin-page v-bind="props" ref="page"></multiple-admin-page>
</div>

<script>
$(document).ready(function(){
    var props = {
        data: <?=json_encode($result)?>,
        columns:[{
            name:"name", 
            label:"洗涤名称", 
            is_create:true, 
            is_update:true, 
            is_show:true, 
            width:200, 
            is_focus:true                
        },{
            name:"image", 
            label:"图片", 
            is_create:true, 
            is_update:true, 
            is_show:true, 
            width:200, 
            disable_change:true,
            type:"upload", 
            multiple:false, 
            limit:1,
            is_image:true,
            image_width:60,
            image_height:60
        },{
            name:"remark", 
            label:"备注", 
            is_create:true, 
            is_update:true, 
            is_show:true, 
            width:200, 
            type:"textarea"
        }],
        buttons:{
            "create":{
                label:"创建"    
            },
            "save":{
                label:"保存"    
            },
            "remove":{
                label:"删除"    
            },
            "edit":{
                label:"编辑"    
            } 
        },
        labels:{
            formTitleCreate:"添加信息",
            formTitleUpdate:"编辑信息",
            action:"操作",
            yes:"是",
            no:"否",
            language:"语言",
            upload:'点击上传'
        },
        options:{
            dialogWidth:"35%"
        },
        default_language:'<?=$__default_language?>',
        upload_action:'', //上传地址
        image_url_prex:'<?=$__config["file_prex"]?>',
        controller:"washinginstructions"
    }
    
    new Vue({
        el:"#ell",
        data() {
            return {
                props:props   
            }
        }
    })
})
</script>
<style>
</style>

