<div id="ell">
  <multiple-admin-page v-bind="props" ref="page"></multiple-admin-page>
</div>

<script>
$(document).ready(function(){
    var props = {
        columns:[
            {name:"name", label:"<?=$system_language['bihefangshimingcheng']?>", is_multiple:true, is_focus:true},
            {name:"memo", label:"<?=$system_language['bihefangshishuoming']?>", is_multiple:true, type:"textarea"}
        ],
        controller:"closedway",
        key_column:"name"
    }
    
    new Vue({
        el:"#ell",
        data() {
            return {
                props:props   
            }
        }
    })
})
</script>
<style>
</style>

