<div id="ell">
  <multiple-admin-page v-bind="props" ref="page"></multiple-admin-page>
</div>

<script>
$(document).ready(function(){
    var props = {
        columns:[
            {name:"name", label:"<?=$system_language['leibiemingcheng']?>", is_multiple:true, is_focus:true},
            {name:"matter", label:"<?=$system_language['zhuyishixiang']?>", is_multiple:true, type:"textarea"},
            {name:"description", label:"<?=$system_language['beizhu']?>", is_multiple:true, type:"textarea"}
        ],
        controller:"securitycategory",
        key_column:"name"
    }
    
    new Vue({
        el:"#ell",
        data() {
            return {
                props:props   
            }
        }
    })
})
</script>
<style>
</style>

