<div id="ell">
  <multiple-admin-page v-bind="props" ref="page"></multiple-admin-page>
</div>

<div id="ell2">
  <el-dialog class="user-form" :title="''" :visible.sync="dialogVisible" :center="true" width="80%">
    <multiple-admin-page v-bind="props" ref="page2"></multiple-admin-page>
  </el-dialog>
</div>
<script>
$(document).ready(function(){
    var props = {
        columns:[            
            {name:"name", label:"<?=$system_language["mingcheng"]?>", is_multiple:true, is_focus:true},
            {name:"code", label:"<?=$system_language["bianhao"]?>"}
        ],
        buttons:[
            {name:"code", label:"<?=$system_language["chakanziji"]?>", width:200, disable_change:true, handler:function(rowIndex, row){
                //console.log(rowIndex, row)   
                props2.base.topid = row.id;
                options.dialogVisible = true; 
            }}
        ],
        controller:"sizetop",
        key_column:"name"
    }
    
    var props2 = {
        columns:[            
            {name:"content", label:"<?=$system_language["neirong"]?>", is_multiple:true, is_focus:true},
            {name:"sortnum", label:"<?=$system_language["xuhao"]?>"},
        ],
        controller:"sizecontent",
        key_column:"content",
        base:{
            topid:""    
        }
    }
    
    var options = {
        props:props2,
        dialogVisible:false
    }
    
    var brandgroup = new Vue({
        el:"#ell",
        data() {
            return {
                props:props   
            }
        }
    })
    
    var childgroup = new Vue({
        el:"#ell2",
        data() {
            return options
        }
    })
})
</script>