<div id="ell" style="width:100%">
<el-row :gutter="20">
  <el-col :span="8">
    <el-tree :data="data" :props="defaultProps" default-expand-all :expand-on-click-node="false" @node-click="onNodeClick"></el-tree>
  </el-col>
  <el-col :span="7" v-if="form.id>0">
    <el-button type="info" @click="showDepartCreate" style="margin-bottom:30px;"><?=$system_language["depart-create"]?></el-button>

    <el-form ref="form" :model="form" label-width="80px">
      <el-form-item label="<?=$system_language["depart-name"]?>">
        <el-input v-model="form.Name"></el-input>
      </el-form-item>

      <el-form-item label="<?=$system_language["description"]?>">
        <el-input type="textarea" v-model="form.Remark"></el-input>
      </el-form-item>
      <el-form-item>
        <el-button type="primary" @click="onSubmit" :disabled="is_save_disabled"><?=$system_language["button-save"]?></el-button>
        <el-button><?=$system_language["button-cancel"]?></el-button>
      </el-form-item>
    </el-form>s
  </el-col>
</el-row>

<el-dialog title="<?=$system_language["depart-create"]?>" :visible.sync="dialogTableVisible" :center="true" width="35%">
  <el-form :model="form_create" label-width="80px">
    <el-form-item label="<?=$system_language["depart-name"]?>">
      <el-input v-model="form_create.Name"></el-input>
    </el-form-item>

    <el-form-item label="<?=$system_language["description"]?>">
      <el-input type="textarea" v-model="form_create.Remark"></el-input>
    </el-form-item>

    <el-form-item label="<?=$system_language["depart-parent"]?>">
      <el-input v-model="form_create.parent_name" disabled></el-input>
    </el-form-item>
  </el-form>
  <div slot="footer" class="dialog-footer" style="text-align:center">
    <el-button type="primary" @click="onDepartCreate"><?=$system_language["button-ok"]?></el-button>
    <el-button @click="dialogTableVisible = false"><?=$system_language["button-cancel"]?></el-button>
  </div>
</el-dialog>
</div>

<script>
$(document).ready(function(){
    $.post("/department/departments", {}, function(departments){
        //console.log(departments)

        new Vue({
            el:"#ell",
            data() {
                return {
                    form: {
                        Name: '',
                        Remark: '',
                        id: ''
                    },
                    form_create: {
                        Name: '',
                        Remark: '',
                        up_dp_id:'',
                        parent_name:''
                    },
                    data: departments,
                    defaultProps: {
                        children: 'children',
                        label: 'label'
                    },
                    nodeData:'',
                    is_save_disabled:true,
                    dialogTableVisible:false
                }
            },
            methods: {
                onNodeClick(data, node) {
                    console.log(data , node)
                    this.nodeData = data;
                    this.form.Name = data.label
                    this.form.Remark = data.Remark
                    this.form.id = data.id
                    this.form_create.parent_name = data.label
                    this.form_create.up_dp_id = data.id

                    this.is_save_disabled = node.parent.id<=0
                },
                onSubmit() {
                    var self = this
                    $ASA.submit.call(this, "/department/edit", this.form, function(res) {
                        //$ASA.copyTo(self.form, self.node.data)
                        console.log(self.nodeData.data, self.form)
                        self.nodeData.label = self.form.Name;
                    })
                },
                showDepartCreate() {
                    this.form_create.Name = ""
                    this.form_create.Remark = ""
                    this.form_create.id = ""
                    this.dialogTableVisible = true;
                },
                onDepartCreate() {
                    var self = this
                    $ASA.submit.call(this, "/department/add", this.form_create, function(){
                        var newNode = {}
                        newNode.label = self.form_create.Name;
                        newNode.id = self.form_create.id;
                        newNode.children = []
                        self.nodeData.children.push(newNode)    
                    })
                }
            }
        })
    },'json');
})
</script>

