<div id="ell">
  <simple-admin-page v-bind="props" ref="page"></simple-admin-page>
</div>

<div id="ell2">
  <el-dialog class="user-form" :title="title" :visible.sync="dialogVisible" :center="true" width="80%">
    <multiple-admin-page v-bind="props" ref="page2"></multiple-admin-page>
  </el-dialog>
</div>
<script>
$(document).ready(function(){
    var props = {
        columns:[
            {name:"suppliercode", label:"<?=$system_language['gonghuoshangbianma']?>"},
            {name:"countrycity", label:"<?=$system_language['guojiachengshi']?>", class:"width2"},
            {name:"suppliername", label:"<?=$system_language['gonghuoshangmingcheng']?>", class:"width1"},
            {name:"address", label:"<?=$system_language['dizhi']?>", class:"width1", is_hide:true},
            {name:"englishname", label:"<?=$system_language['yingwenmingcheng']?>", class:"width1", is_hide:true},
            {name:"english_address", label:"<?=$system_language['gonghuoshangbianma']?>", class:"width1", is_hide:true},
            {name:"website", label:"<?=$system_language['wangzhi']?>", class:"width2", is_hide:true},
            {name:"fax", label:"<?=$system_language['chuanzhen']?>", class:"width2", is_hide:true},
            {name:"legal", label:"<?=$system_language['faren']?>", class:"width2", is_hide:true},
            {name:"registeredcapital", label:"<?=$system_language['zhuceziben']?>", class:"width2", is_hide:true},
            {name:"businesslicense", label:"<?=$system_language['yingyezhizhaohao']?>", class:"width2", is_hide:true},
            {name:"heading", label:"<?=$system_language['shuihao']?>", class:"width2", is_hide:true},
            {name:"registered", label:"<?=$system_language['zhuceshijian']?>", class:"width2", is_hide:true},
            {name:"endtime", label:"<?=$system_language['zhongzhishijian']?>", class:"width2", is_hide:true},
            {name:"type", label:"<?=$system_language['leixing']?>"},
            {name:"phone", label:"<?=$system_language['dianhua']?>"},
            {name:"memo", label:"<?=$system_language['beizhu']?>", class:"width1", is_hide:true, type:"textarea"}
        ],
        buttons:[
            {name:"code", label:"<?=$system_language["lianxiren"]?>", width:200, handler:function(rowIndex, row){
                //console.log(rowIndex, row)   
                options.props.base.productgroupid = row.relateid;
                options.dialogVisible = true; 
                //options.title = row.brandgroupname
            }}
        ],
        options:{
            dialogWidth:'700px',
            formSize:'small',
            inline:true
        },
        controller:"supplier"
    }
        
    var options = {
        props:{
            columns:[            
                {name:"name", label:"<?=$system_language["zileimingcheng"]?>", is_multiple:true, is_focus:true},
                {name:"childcode", label:"<?=$system_language["zileibianma"]?>"},
                {name:"producttemplateid", label:"<?=$system_language["chimamoban"]?>", type:'select', source:"sizetop"},
                {name:"weight", label:"<?=$system_language["maozhong"]?>"},
            ],
            controller:"childproductgroup",
            key_column:"name",
            base:{
                productgroupid:""    
            }
        },
        dialogVisible:false,
        title:""
    }
    
    new Vue({
        el:"#ell",
        data() {
            return {
                props:props,
                props2:options.props
            }
        }
    })
    
    var childgroup = new Vue({
        el:"#ell2",
        data() {
            return options
        }
    })
})
</script>

<style>
    .user-form .width2 .el-input__inner {
        width:200px;
    }
    
    .user-form .width1 .el-input__inner {
        width:510px;
    }
    
    .user-form .width1 .el-textarea__inner {
        width:510px;
    }
    
    .user-form .el-date-editor.el-input, .el-date-editor.el-input__inner {
        width:200px
    }
</style>