<!DOCTYPE html>
<!--[if IE 8]>
<html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]>
<html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->

<!-- Head BEGIN -->
<head>
    <meta charset="utf-8">
    <title><?php echo $this->obj->getValidateMessage('address-list'); ?></title>

    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <meta content="Metronic Shop UI description" name="description">
    <meta content="Metronic Shop UI keywords" name="keywords">
    <meta content="keenthemes" name="author">

    <link rel="shortcut icon" href="favicon.ico">

    <!-- Global styles START -->
    <link href="/shop/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="/shop/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Global styles END -->

    <!-- Page level plugin styles START -->
    <link href="/shop/assets/pages/css/animate.css" rel="stylesheet">
    <link href="/shop/assets/plugins/fancybox/source/jquery.fancybox.css" rel="stylesheet">
    <link href="/shop/assets/plugins/owl.carousel/assets/owl.carousel.css" rel="stylesheet">
    <!-- Page level plugin styles END -->

    <!-- Theme styles START -->
    <link href="/shop/assets/pages/css/components.css" rel="stylesheet">
    <link href="/shop/assets/pages/css/slider.css" rel="stylesheet">
    <link href="/shop/assets/pages/css/style-shop.css" rel="stylesheet" type="text/css">
    <link href="/shop/assets/corporate/css/style.css" rel="stylesheet">
    <link href="/shop/assets/corporate/css/style-responsive.css" rel="stylesheet">
    <link href="/shop/assets/corporate/css/themes/red.css" rel="stylesheet" id="style-color">
    <link href="/shop/assets/corporate/css/custom.css" rel="stylesheet">
    <!-- Theme styles END -->
</head>
<!-- Head END -->

<!-- Body BEGIN -->
<body class="corporate">

<?php echo $this->view->getPartial('layouts/_header') ?>

<div class="main">
    <div class="container">
        <ul class="breadcrumb">
            <li><a href="/"><?php echo $this->obj->getValidateMessage('shouye'); ?></a></li>
            <li class="active"><?php echo $this->obj->getValidateMessage('address-list'); ?></li>
        </ul>
        <!-- BEGIN SIDEBAR & CONTENT -->
        <div class="row margin-bottom-40">

            <?php echo $this->view->getPartial('layouts/_member_sidebar') ?>

            <!-- BEGIN CONTENT -->
            <div class="col-md-9 col-sm-9">
                <h1 class="h1-title"><span class="pull-right"><a
                                href="/memberaddress/add"><?php echo $this->obj->getValidateMessage('add-new-address'); ?></a></span><?php echo $this->obj->getValidateMessage('address-list'); ?>
                </h1>
                <div class="content-form-page">
                    <div class="row">
                        <div class="col-md-12">
                            <table id="table-address" class="table table-bordered table-hover" style="width:100%">
                                <tr>
                                    <th><?php echo $this->obj->getValidateMessage('shouhuoren'); ?></th>
                                    <th><?php echo $this->obj->getValidateMessage('address'); ?></th>
                                    <th><?php echo $this->obj->getValidateMessage('mobile'); ?></th>
                                    <th><?php echo $this->obj->getValidateMessage('caozuo'); ?></th>
                                    <th><?php echo $this->obj->getValidateMessage('set-default'); ?></th>
                                </tr>
                                <?php
                                if (count($result) > 0) {
                                    foreach ($result as $address) {
                                        ?>
                                        <tr>
                                            <td><?php echo $address['name']; ?></td>
                                            <td><?php echo $address['address']; ?></td>
                                            <td><?php echo $address['tel']; ?></td>
                                            <td>
                                                <a class="t-change"
                                                   href="/memberaddress/edit/<?php echo $address['id']; ?>"
                                                   target="_self"><?php echo $this->obj->getValidateMessage('button-modify'); ?></a>
                                                <span class="t-line">|</span>
                                                <a onclick="address_del(<?php echo $address['id']; ?>);return false;"><span
                                                            class="t-delete"><?php echo $this->obj->getValidateMessage('button-delete'); ?></span></a>
                                            </td>
                                            <td>
                                                <?php if ($address['is_default']) { ?>
                                                    <span class="t-default"><?php echo $this->obj->getValidateMessage('default-address'); ?></span>
                                                <?php } else { ?>
                                                    <a onclick="address_set_default(<?php echo $address['id']; ?>);return false;"><?php echo $this->obj->getValidateMessage('set-default'); ?></a>
                                                <?php } ?>

                                            </td>
                                        </tr>
                                    <?php } ?>
                                <?php } else { ?>
                                    <tr>
                                        <td colspan="5"><?php echo $this->obj->getValidateMessage('no-saving-addresses'); ?></td>
                                    </tr>
                                <?php } ?>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END CONTENT -->
        </div>
        <!-- END SIDEBAR & CONTENT -->
    </div>
</div>

<?php echo $this->view->getPartial('layouts/_footer'); ?>

<script>
    /**
     * 地址设置为默认
     * @returns {boolean}
     */
    function address_set_default(id) {
        // 询问框
        layer.open({
            content: "<?php echo $this->obj->getValidateMessage('confirm-default-adress'); ?>",
            btn: ["<?php echo $this->obj->getValidateMessage('yes'); ?>", "<?php echo $this->obj->getValidateMessage('no'); ?>"],
            yes: function (index) {
                // ajax提交
                $.post('/memberaddress/setdefault/' + id, {}, function (response) {
                    // 判断是否有错误
                    if (response.messages.length > 0) {
                        layer.open({
                            content: response.messages[0],
                            btn: "<?php echo $this->obj->getValidateMessage('iknow'); ?>"
                        });
                    } else {
                        //提示
                        layer.open({
                            content: "<?php echo $this->obj->getValidateMessage('success'); ?>",
                            btn: "<?php echo $this->obj->getValidateMessage('please-wait'); ?>",
                            time: 3, // 3秒后自动跳转
                        });
                        // 3秒后跳转
                        setTimeout(function () {
                            window.location.reload();
                        }, 1000);
                    }
                }, 'json');
                // 关闭弹出层
                layer.close(index);
            }
        });
    }


    /**
     * 删除地址
     * @returns {boolean}
     */
    function address_del(id) {
        // 询问框
        layer.open({
            content: "<?php echo $this->obj->getValidateMessage('confirm-delete-adress'); ?>",
            btn: ["<?php echo $this->obj->getValidateMessage('yes'); ?>", "<?php echo $this->obj->getValidateMessage('no'); ?>"],
            yes: function (index) {
                // ajax提交
                $.post('/memberaddress/del/' + id, {}, function (response) {
                    // 判断是否有错误
                    if (response.messages.length > 0) {
                        layer.open({
                            content: response.messages[0],
                            btn: "<?php echo $this->obj->getValidateMessage('iknow'); ?>"
                        });
                    } else {
                        //提示
                        layer.open({
                            content: "<?php echo $this->obj->getValidateMessage('success'); ?>",
                            btn: "<?php echo $this->obj->getValidateMessage('please-wait'); ?>",
                            time: 3, // 3秒后自动跳转
                        });
                        // 3秒后跳转
                        setTimeout(function () {
                            window.location.reload();
                        }, 1000);
                    }
                }, 'json');
                // 关闭弹出层
                layer.close(index);
            }
        });
    }
</script>

</body>
<!-- END BODY -->
</html>