<!DOCTYPE html>
<!--[if IE 8]>
<html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]>
<html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->

<!-- Head BEGIN -->
<head>
    <meta charset="utf-8">
    <title><?php echo $this->obj->getValidateMessage('address-list'); ?></title>
    <?php echo $this->view->getPartial('layouts/_meta') ?>
</head>
<!-- Head END -->

<!-- Body BEGIN -->
<body class="corporate">

<?php echo $this->view->getPartial('layouts/_header') ?>

<div class="main">
    <div class="container">
        <ul class="breadcrumb">
            <li><a href="/"><?php echo $this->obj->getValidateMessage('shouye'); ?></a></li>
            <li class="active"><?php echo $this->obj->getValidateMessage('address-list'); ?></li>
        </ul>
        <!-- BEGIN SIDEBAR & CONTENT -->
        <div class="row margin-bottom-40">

            <?php echo $this->view->getPartial('layouts/_member_sidebar') ?>

            <!-- BEGIN CONTENT -->
            <div class="col-md-9 col-sm-9">
                <h1 class="h1-title"><span class="pull-right"><a
                                href="/memberaddress/add"><?php echo $this->obj->getValidateMessage('add-new-address'); ?></a></span><?php echo $this->obj->getValidateMessage('address-list'); ?>
                </h1>
                <div class="content-form-page">
                    <div class="row">
                        <div class="col-md-12">
                            <table id="table-address" class="table table-bordered table-hover" style="width:100%">
                                <tr>
                                    <th><?php echo $this->obj->getValidateMessage('shouhuoren'); ?></th>
                                    <th><?php echo $this->obj->getValidateMessage('address'); ?></th>
                                    <th><?php echo $this->obj->getValidateMessage('mobile'); ?></th>
                                    <th><?php echo $this->obj->getValidateMessage('caozuo'); ?></th>
                                    <th><?php echo $this->obj->getValidateMessage('set-default'); ?></th>
                                </tr>
                                <?php
                                if (count($result) > 0) {
                                    foreach ($result as $address) {
                                        ?>
                                        <tr>
                                            <td><?php echo $address['name']; ?></td>
                                            <td><?php echo $address['address']; ?></td>
                                            <td><?php echo $address['tel']; ?></td>
                                            <td>
                                                <a class="t-change"
                                                   href="/memberaddress/edit/<?php echo $address['id']; ?>"
                                                   target="_self"><?php echo $this->obj->getValidateMessage('button-modify'); ?></a>
                                                <span class="t-line">|</span>
                                                <a onclick="address_del(<?php echo $address['id']; ?>);return false;"><span
                                                            class="t-delete"><?php echo $this->obj->getValidateMessage('button-delete'); ?></span></a>
                                            </td>
                                            <td>
                                                <?php if ($address['is_default']) { ?>
                                                    <span class="t-default"><?php echo $this->obj->getValidateMessage('default-address'); ?></span>
                                                <?php } else { ?>
                                                    <a onclick="address_set_default(<?php echo $address['id']; ?>);return false;"><?php echo $this->obj->getValidateMessage('set-default'); ?></a>
                                                <?php } ?>

                                            </td>
                                        </tr>
                                    <?php } ?>
                                <?php } else { ?>
                                    <tr>
                                        <td colspan="5"><?php echo $this->obj->getValidateMessage('no-saving-addresses'); ?></td>
                                    </tr>
                                <?php } ?>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END CONTENT -->
        </div>
        <!-- END SIDEBAR & CONTENT -->
    </div>
</div>

<?php echo $this->view->getPartial('layouts/_footer'); ?>

</body>
<!-- END BODY -->
</html>