<!DOCTYPE html>

<!--[if IE 8]>
<html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]>
<html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->

<!-- Head BEGIN -->
<head>
    <meta charset="utf-8">
    <title id="product_name"><?php echo $product->productname; ?> - <?php echo $this->host['webtitle']; ?></title>
    <?php echo $this->view->getPartial('layouts/_meta') ?>
</head>
<!-- Head END -->

<!-- Body BEGIN -->
<body class="ecommerce">

<?php echo $this->view->getPartial('layouts/_header') ?>

<div class="main">
    <div class="container">
        <ul class="breadcrumb">
            <?php echo $breadcrumb; ?>
        </ul>

        <!-- BEGIN SIDEBAR & CONTENT -->
        <div class="row margin-bottom-40">

            <?php echo $this->view->getPartial('layouts/_sidebar'); ?>

            <!-- BEGIN CONTENT -->
            <div class="col-md-9 col-sm-7">
                <div class="product-page" id="product_id" attr-id="<?php echo $product->id; ?>">
                    <div class="row">
                        <div class="col-md-6 col-sm-6">
                            <div class="product-main-image">
                                <img src="<?php echo \Asa\Erp\Util::getCorrentImgUrl($this->file_prex . $product->picture); ?>"
                                     alt="<?php echo $product->productname; ?>" class="img-responsive"
                                     data-BigImgsrc="<?php echo \Asa\Erp\Util::getCorrentImgUrl($this->file_prex . $product->picture); ?>">
                            </div>
                            <div class="product-other-images">
                                <a href="<?php echo $this->file_prex . $product->picture; ?>" class="fancybox-button"
                                   rel="photos-lib"><img alt="<?php echo $product->productname; ?>"
                                                         src="<?php echo \Asa\Erp\Util::getCorrentImgUrl($this->file_prex . $product->picture); ?>"></a>
                                <a href="<?php echo $this->file_prex . $product->picture2; ?>" class="fancybox-button"
                                   rel="photos-lib"><img alt="<?php echo $product->productname; ?>"
                                                         src="<?php echo \Asa\Erp\Util::getCorrentImgUrl($this->file_prex . $product->picture2); ?>"></a>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6">
                            <h1><?php echo $product->productname; ?></h1>
                            <div class="price-availability-block clearfix">
                                <div class="price">
                                    <strong><span><?php echo $this->currency; ?></span><span
                                                id="price"><?php echo $realprice; ?></span></strong>
                                </div>
                                <div class="availability">
                                    <?php echo $this->obj->getValidateMessage('in-stock'); ?>:
                                    <strong><?php echo $number; ?></strong>
                                </div>
                            </div>
                        </div>

                        <div class="product-page-content">
                            <ul id="myTab" class="nav nav-tabs">
                                <li class="active"><a href="#Description"
                                                      data-toggle="tab"><?php echo $this->obj->getValidateMessage('product-description'); ?></a>
                                </li>
                            </ul>
                            <div id="myTabContent" class="tab-content">
                                <div class="tab-pane fade in active" id="Description">

                                </div>
                            </div>
                        </div>

                        <div class="sticker sticker-sale"></div>

                    </div>
                </div>
            </div>
            <!-- END CONTENT -->
        </div>
        <!-- END SIDEBAR & CONTENT -->
    </div>
</div>

<?php echo $this->view->getPartial('layouts/_footer'); ?>

</body>
<!-- END BODY -->
</html>