<!DOCTYPE html>

<!--[if IE 8]>
<html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]>
<html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->

<!-- Head BEGIN -->
<head>
    <meta charset="utf-8">
    <title id="product_name"><?php echo $product->productname; ?> - <?php echo $this->host['webtitle']; ?></title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <meta content="Metronic Shop UI description" name="description">
    <meta content="Metronic Shop UI keywords" name="keywords">
    <meta content="keenthemes" name="author">

    <!-- Global styles START -->
    <link href="/shop/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="/shop/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Global styles END -->

    <!-- Page level plugin styles START -->
    <link href="/shop/assets/plugins/fancybox/source/jquery.fancybox.css" rel="stylesheet">
    <link href="/shop/assets/plugins/owl.carousel/assets/owl.carousel.css" rel="stylesheet">
    <link href="/shop/assets/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css">
    <link href="/shop/assets/plugins/jquery-ui/jquery-ui.css" rel="stylesheet" type="text/css"><!-- for slider-range -->
    <link href="/shop/assets/plugins/rateit/src/rateit.css" rel="stylesheet" type="text/css">
    <!-- Page level plugin styles END -->

    <!-- Theme styles START -->
    <link href="/shop/assets/pages/css/components.css" rel="stylesheet">
    <link href="/shop/assets/corporate/css/style.css" rel="stylesheet">
    <link href="/shop/assets/pages/css/style-shop.css" rel="stylesheet" type="text/css">
    <link href="/shop/assets/corporate/css/style-responsive.css" rel="stylesheet">
    <link href="/shop/assets/corporate/css/themes/red.css" rel="stylesheet" id="style-color">
    <link rel="stylesheet" href="/shop/assets/static/css/bootstrap-submenu.css">
    <link href="/shop/assets/corporate/css/custom.css" rel="stylesheet">
    <!-- Theme styles END -->
</head>
<!-- Head END -->

<!-- Body BEGIN -->
<body class="ecommerce">

<?php echo $this->view->getPartial('layouts/_header') ?>

<div class="main">
    <div class="container">
        <ul class="breadcrumb">
            <?php echo $breadcrumb; ?>
        </ul>

        <!-- BEGIN SIDEBAR & CONTENT -->
        <div class="row margin-bottom-40">

            <?php echo $this->view->getPartial('layouts/_sidebar'); ?>

            <!-- BEGIN CONTENT -->
            <div class="col-md-9 col-sm-7">
                <div class="product-page" id="product_id" attr-id="<?php echo $product->id; ?>">
                    <div class="row">
                        <div class="col-md-6 col-sm-6">
                            <div class="product-main-image">
                                <img src="<?php echo $this->file_prex . $product->picture; ?>"
                                     alt="<?php echo $product->productname; ?>" class="img-responsive"
                                     data-BigImgsrc="<?php echo $this->file_prex . $product->picture; ?>">
                            </div>
                            <div class="product-other-images">
                                <a href="<?php echo $this->file_prex . $product->picture; ?>" class="fancybox-button"
                                   rel="photos-lib"><img alt="<?php echo $product->productname; ?>"
                                                         src="<?php echo $this->file_prex . $product->picture; ?>"></a>
                                <a href="<?php echo $this->file_prex . $product->picture2; ?>" class="fancybox-button"
                                   rel="photos-lib"><img alt="<?php echo $product->productname; ?>"
                                                         src="<?php echo $this->file_prex . $product->picture2; ?>"></a>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6">
                            <h1><?php echo $product->productname; ?></h1>
                            <div class="price-availability-block clearfix">
                                <div class="price">
                                    <strong><span><?php echo $this->currency; ?></span><span
                                                id="price"><?php echo $realprice; ?></span></strong>
                                    <!--                                    <em>-->
                                    <?php //echo $this->currency; ?><!--<span>-->
                                    <?php //echo $price; ?><!--</span></em>-->
                                </div>
                                <div class="availability">
                                    <?php echo $this->obj->getValidateMessage('in-stock'); ?>:
                                    <strong><?php echo $number; ?></strong>
                                </div>
                            </div>
                        </div>

                        <div class="product-page-content">
                            <ul id="myTab" class="nav nav-tabs">
                                <li class="active"><a href="#Description"
                                                      data-toggle="tab"><?php echo $this->obj->getValidateMessage('product-description'); ?></a>
                                </li>
                            </ul>
                            <div id="myTabContent" class="tab-content">
                                <div class="tab-pane fade in active" id="Description">

                                </div>
                            </div>
                        </div>

                        <div class="sticker sticker-sale"></div>

                    </div>
                </div>
            </div>
            <!-- END CONTENT -->
        </div>
        <!-- END SIDEBAR & CONTENT -->
    </div>
</div>

<?php echo $this->view->getPartial('layouts/_footer'); ?>

</body>
<!-- END BODY -->
</html>