<div id="ell">
<multiple-admin-page v-bind="props" ref="page"></multiple-admin-page>
</div>

<script>
$(document).ready(function(){
    var props = {
        columns:[            
            {name:"name", label:"<?=$system_language['peijianmingcheng']?>", is_multiple:true, is_focus:true},
            {name:"partscode", label:"<?=$system_language['peijiandaima']?>"},
            {name:"packflag", label:"<?=$system_language['shifoubaozhuang']?>", type:"switch"}
        ],
        controller:"productparts",
        key_column:"name"
    }
    
    new Vue({
        el:"#ell",
        data() {
            return {
                props:props   
            }
        }
    })
})
</script>
<style>
</style>

