<div id="ell">
<multiple-admin-page v-bind="props" ref="page"></multiple-admin-page>
</div>

<script>
$(document).ready(function(){
    var props = {
        columns:[
            {name:"partscode", label:"<?=$system_language['peijiandaima']?>", is_create:true, is_update:true, is_show:true, width:200, disable_change:true, is_focus:true},
            {name:"partsname", label:"<?=$system_language['peijianmingcheng']?>", is_create:true, is_update:true, is_show:true, width:200, is_focus:true},
            {name:"packflag", label:"<?=$system_language['shifoubaozhuang']?>", is_create:true, is_update:true, is_show:true, width:200, type:"switch", disable_change:true}
        ],
        options:{
            dialogWidth:"35%"
        },
        default_language:'zh-cn',
        controller:"productparts"
    }
    
    new Vue({
        el:"#ell",
        data() {
            return {
                props:props   
            }
        }
    })
})
</script>
<style>
</style>

