<?php

namespace Multiple\Home\Controllers;

use Phalcon\Mvc\Controller;
use Phalcon\Mvc\View;
use Asa\Erp\DdOrderdetails;

/**
 * 订单明细表
 */
class OrderdetailsController extends CadminController {
    public function initialize() {
	    parent::initialize();

	    $this->setModelName('Asa\\Erp\\DdOrderdetails');
    }

    /**
     * 重写，添加订单号以及其他必要的参数
     */
    // public function doAdd()
    // {
    //     parent::doAdd();
    // }

    public function doAdd()
    {
        parent::doAdd(); // TODO: Change the autogenerated stub
    }
}
