<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>超级管理员登录</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="/manager/static/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/manager/static/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="/manager/static/css/material-design-iconic-font.min.css">
    <link rel="stylesheet" type="text/css" href="/manager/static/css/util.css">
    <link rel="stylesheet" type="text/css" href="/manager/static/css/adminmain.css">
</head>

<body>

<div class="limiter">
    <div class="container-login100" style="background-image: url('/manager/static/images/bg-01.jpg')">
        <div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54">
            <form class="login100-form validate-form" method="post" name="login_form">

                <span class="login100-form-title p-b-49">超级管理员登录</span>

                <div class="wrap-input100 validate-input m-b-23" data-validate="请输入用户名">
                    <span class="label-input100">用户名</span>
                    <input class="input100" type="text" id="login_name" name="login_name" placeholder="请输入用户名"
                           autocomplete="off">
                    <span class="focus-input100" data-symbol="&#xf206;"></span>
                </div>

                <div class="wrap-input100 validate-input" data-validate="请输入密码">
                    <span class="label-input100">密码</span>
                    <input class="input100" type="password" id="password" name="password" placeholder="请输入密码">
                    <span class="focus-input100" data-symbol="&#xf190;"></span>
                </div>

                <div class="text-right p-t-8 p-b-31">
                    <!-- <a href="javascript:">忘记密码？</a> -->
                </div>

                <div class="container-login100-form-btn">
                    <div class="wrap-login100-form-btn">
                        <div class="login100-form-bgbtn"></div>
                        <button class="login100-form-btn" id="btn-login">登 录</button>
                    </div>
                </div>

            </form>
        </div>
    </div>
</div>

<!-- BEGIN PRE-FOOTER -->
<script src="/manager/static/js/jquery.min.js" type="text/javascript"></script>
<script src="/manager/static/js/layer_mobile/layer.js"></script>
<script src="/adminlte/dist/js/ajax.js"></script>
<!-- END PRE-FOOTER -->

<script>
    // 登录逻辑
    let button = $('#btn-login');
    button.click(function () {
        ajax(button, '/manager/login', {
            'login_name': $("#login_name").val(),
            'password': $("#password").val(),
        }, '/manager/welcome');
    });
</script>

</body>
</html>