<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>一键初始化</title>
    <?php echo $this->mview->getPartial('layouts/_meta') ?>
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
    <?php echo $this->mview->getPartial('layouts/_header') ?>

    <?php echo $this->mview->getPartial('layouts/_sidebar') ?>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header"></section>
        <!-- Main content -->
        <section class="content container-fluid">
            <div class="rt">
                <p>只需填写一个公司名称，即可自动完成以下功能：</p>
                <p>1、建立1个新公司</p>
                <p>2、给新公司建立4个部门，分别是：人力资源部, 财务部, 销售部, 技术部。</p>
                <p>3、给新公司建立2个权限组，分别是：管理员组，普通用户组，并给管理员组分配所有权限。</p>
                <p>4、给新公司建立1个管理员，默认用户名为公司名称的拼音首字母小写，密码是拼音首字母小写后面加123，隶属部门是技术部，隶属组是管理员组。</p>

                <form id="set">
                    <div class="form-group">
                        <label for="company">公司名称：</label>
                        <input type="text" class="form-control" id="company" placeholder="公司名称">
                    </div>
                    <button type="submit" class="btn btn-primary" id="btn-submit">提交</button>
                </form>
            </div>
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <?php echo $this->mview->getPartial('layouts/_footer') ?>
    <div class="control-sidebar-bg"></div>
</div>

<script>
    // 初始化逻辑
    let button = $('#btn-submit');
    button.click(function () {
        let company = $('#company').val();
        ajax(button, '/manager/set', {
            'company': company,
            'admin': getPinYinFirstCharacter(company)
        }, '/manager/set');
    });
</script>

</body>
</html>
