<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>默认登录页</title>
    <?php echo $this->mview->getPartial('layouts/_meta') ?>
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
    <?php echo $this->mview->getPartial('layouts/_header') ?>

    <?php echo $this->mview->getPartial('layouts/_sidebar') ?>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header"></section>
        <!-- Main content -->
        <section class="content container-fluid">
            <div class="rt">
                <p>欢迎进入超级管理员后台管理系统，这是登录后的默认页面，具体功能请点击左侧的菜单项进行操作。</p>
            </div>
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <?php echo $this->mview->getPartial('layouts/_footer') ?>
    <div class="control-sidebar-bg"></div>
</div>

</body>
</html>
