<div id="ell">
<el-form ref="form" :model="form" label-width="80px">
  <el-form-item label="姓名">
    <el-input v-model="form.name"></el-input>
  </el-form-item>
    
  <el-form-item label="年龄">
    <el-input-number v-model="form.age" :min="10" :max="60" label="年龄大于18小于60"></el-input-number>
  </el-form-item>
  
  
  <el-form-item>
    <el-button type="primary" @click="onSubmit">添加</el-button>
    <el-button @click="onCancel">取消</el-button>
  </el-form-item>
</el-form>
</div>

<script>
$(document).ready(function(){
    console.log($ASA)
    new Vue({
        el:"#ell",
        data() {
      return {
        form: {
          name: '<?=$info->name?>',
          age:'<?=$info->age?>',
          id:'<?=$info->id?>'
        }
      }
    },
    methods: {
        onCancel() {
            window.location = "/user/index";    
        },
        onSubmit() {
            $ASA.post.call(this, "/user/edit", this.form)
        }
    }  
    })
})
</script>

<style>
.line {text-align: center}
</style>

