<div id="ell" style="margin:auto;margin-top:20px;">
<el-form status-icon label-width="100px">
  <el-form-item label="旧密码" prop="pass">
    <el-input type="password" v-model="form.old_password" autocomplete="off"></el-input>
  </el-form-item>
  <el-form-item label="新密码" prop="pass">
    <el-input type="password" v-model="form.new_password" autocomplete="off"></el-input>
  </el-form-item>
  <el-form-item label="确认密码" prop="checkPass">
    <el-input type="password" v-model="form.confirm_password" autocomplete="off"></el-input>
  </el-form-item>
  <el-form-item>
    <el-button type="primary" @click="submitForm()">提交</el-button>
    <el-button @click="resetForm()">重置</el-button>
  </el-form-item>
</el-form>
</div>

<script>
$(document).ready(function(){
    new Vue({
        el:"#ell",
        data() {
      return {
        form: {
          old_password: '',
          new_password:'',
          confirm_password:''
        }
      }
    },
    methods: {
        resetForm() {
            this.form.old_password = '';
            this.form.new_password = '';
            this.form.confirm_password = '';
        },
        submitForm() {
            $ASA.post.call(this, "/user/modifypassword", this.form, {success:"密码修改成功"})
        }
    }  
    })
})
</script>

<style>
.line {text-align: center}
</style>

