<div id="ell">
<el-form status-icon label-width="100px">
  <el-form-item label="旧密码" prop="pass">
    <el-input type="password" v-model="form.old_password" autocomplete="off"></el-input>
  </el-form-item>
  <el-form-item label="新密码" prop="pass">
    <el-input type="password" v-model="form.new_password" autocomplete="off"></el-input>
  </el-form-item>
  <el-form-item label="确认密码" prop="checkPass">
    <el-input type="password" v-model="form.confirm_password" autocomplete="off"></el-input>
  </el-form-item>
  <el-form-item>
    <el-button type="primary" @click="submitForm()">提交</el-button>
    <el-button @click="resetForm()">重置</el-button>
  </el-form-item>
</el-form>
</div>

<script>
$(document).ready(function(){
    new Vue({
        el:"#ell",
        data() {
      return {
        form: {
          old_password: '',
          new_password:'',
          confirm_password:''
        }
      }
    },
    methods: {
        resetForm() {
            this.form.old_password = '';
            this.form.new_password = '';
            this.form.confirm_password = '';
        },
        submitForm() {
            var self = this;
            $.post("/user/edit",this.form, function(res){
                //console.log(res)
                if(res.messages.length>0) {
                    const h = self.$createElement;
                    var message = h("ul", null, res.messages.map(function(v){
                        return h("li",null,v)    
                    }))
                    
                    self.$alert(message, '错误提示', {
                        confirmButtonText: '确定'
                    });   
                }    
                else {
                    self.$message({
                        message: '恭喜你，保存成功',
                        type: 'success'
                    });
                }
            },"json")
        }
    }  
    })
})
</script>

<style>
.line {text-align: center}
</style>

