<div id="ell">
  <simple-admin-page v-bind="props" ref="page"></simple-admin-page>
</div>

<script>
$(document).ready(function(){
    var props = {
        columns:[
            {name:"sessionmark", label:"<?=$system_language['fabuji']?>", is_hide:true, type:'select', source:"sessionmark"},
            {name:"name", label:"<?=$system_language['nianfen']?>",is_focus:true, 
                convert:function(row, rowIndex, column){
                    return row.sessionmark+ row.name
                }
            }
        ],
        controller:"ageseason"
    }
    
    new Vue({
        el:"#ell",
        data() {
            return {
                props:props   
            }
        }
    })
})
</script>
