<div id="ell">
<multiple-admin-page v-bind="props" ref="page"></multiple-admin-page>
</div>

<script>
$(document).ready(function(){
    var props = {
        columns:[            
            {name:"name", label:"<?=$system_language['zhongwenmingcheng']?>", is_multiple:true, is_focus:true},
            {name:"code", label:"<?=$system_language['bianhao']?>"}
        ],
        controller:"materialstatus",
        key_column:"name"
    }
    
    new Vue({
        el:"#ell",
        data() {
            return {
                props:props   
            }
        }
    })
})
</script>
<style>
</style>

