<div id="ell" style="width:100%">
<el-row>
      <el-col :span="24">
        <el-button type="primary" @click="showForm('create')"><?=$system_language["button-create"]?></el-button>
      </el-col>
    </el-row>

<el-row>
  <el-col :span="8">
    <el-table :data="tableData" stripe border style="width: 100%;">
      <el-table-column prop="name" label="<?=$system_language["group-name"]?>" align="center" width="180">
      </el-table-column>

      <el-table-column label="<?=$system_language["action"]?>" width="250" align="center">
        <template v-slot="scope">
          <el-button size="mini" @click="showUserList(scope.row)"><?=$system_language["user-list"]?></el-button>
          <el-button size="mini" @click="handleEdit('update', scope.row)"><?=$system_language["button-modify"]?></el-button>
          <el-button size="mini" @click="handleDelete(scope.$index, scope.row)"><?=$system_language["button-delete"]?></el-button>
        </template>
      </el-table-column>
    </el-table>
  </el-col>

  <el-col :span="16">
    <el-tree :data="data2" show-checkbox node-key="id" :default-expanded-keys="[2, 3]" :default-checked-keys="[5]"></el-tree>
  </el-col>
</el-row>


<el-dialog class="user-form" :title="labels[action_type][0]" :visible.sync="dialogVisible" :center="true" width="35%">
  <el-form :model="form" label-width="80px">
    <el-form-item label="<?=$system_language["group-name"]?>">
      <el-input v-model="form.name"></el-input>
    </el-form-item>

    <el-form-item label="<?=$system_language["description"]?>">
      <el-input type="textarea" v-model="form.description"></el-input>
    </el-form-item>
  </el-form>

  <span slot="footer" class="dialog-footer">
    <el-button type="primary" @click="saveGroup">{{labels[action_type][1]}}</el-button>
  </span>
</el-dialog>

<el-dialog class="user-form" title="<?=$system_language["user-list"]?>" :visible.sync="dialogListVisible" :center="true" width="35%">
  <el-table :data="user_list" stripe border>
    <el-table-column prop="name" label="<?=$system_language["user-realname"]?>" align="center" width="180">
    </el-table-column>

    <el-table-column prop="depart" label="<?=$system_language["depart"]?>" align="center" width="180">
    </el-table-column>
  </el-table>
</el-dialog>
</div>

<script>
$(document).ready(function(){
    new Vue({
        el:"#ell",
        data() {
            return {
                tableData: <?=json_encode($result)?>,
                dialogVisible:false,
                dialogListVisible:false,
                form: {
                    name: '',
                    description: '',
                    id:''
                },
                action_type:"create",
                labels:{
                    create:['<?=$system_language["group-add"]?>','<?=$system_language["button-save"]?>'],
                    update:['<?=$system_language["group-modify"]?>','<?=$system_language["button-save"]?>']
                },
                user_list:[{name:'测试用户1',depart:"销售部"},{name:'测试用户2',depart:"销售部"},{name:'测试用户5',depart:"技术部"}],//用户列表
                data2: [{
          id: 1,
          label: '一级 1',
          children: [{
            id: 4,
            label: '二级 1-1',
            children: [{
              id: 9,
              label: '三级 1-1-1'
            }, {
              id: 10,
              label: '三级 1-1-2'
            }]
          }]
        }, {
          id: 2,
          label: '一级 2',
          children: [{
            id: 5,
            label: '二级 2-1'
          }, {
            id: 6,
            label: '二级 2-2'
          }]
        }, {
          id: 3,
          label: '一级 3',
          children: [{
            id: 7,
            label: '二级 3-1'
          }, {
            id: 8,
            label: '二级 3-2'
          }]
        }]
            }
        },
        methods: {
            showForm(action) {
                this.form.name = '';
                this.form.id = ''
                this.form.description = ''
                this.dialogVisible = true;
                this.action_type = action;
            },
            handleEdit(action, row){
                this.form.name = row.name;
                this.form.id = row.id;
                this.form.description = row.description;
                this.action_type = action;
                this.dialogVisible = true;
            },
            showUserList(row) {
                this.dialogListVisible = true;
            },
            saveGroup() {
                var self = this
                var form = this.form
                if(form.id!="") {
                    $ASA.submit.call(self, "/role/edit", form, function(res){
                        var list = self.tableData;
                        for(var i=0;i<list.length;i++) {
                            if(list[i].id==form.id) {
                                list[i].name = form.name;
                                list[i].description = form.description;
                                break;   
                            }   
                        }
                        self.dialogVisible = false;
                    }) 
                }
                else {
                    $ASA.submit.call(self, "/role/add", form, function(res){
                        self.tableData.push({
                            name:self.form.name,
                            description:self.form.description,
                            id:res.id    
                        })
                        
                        form.id = res.id;
                        
                        self.dialogVisible = false;
                    }) 
                }  
            },
            handleDelete(rowIndex, row) {
                var self = this;

                $ASA.remove.call(self, "/role/delete?id=" + row.id, function(res){                        
                        self.$delete(self.tableData,rowIndex)
                        
                        //self.dialogVisible = false;
                }) 
            }
        }
    })
})
</script>
