<div id="ell">
  <multiple-admin-page v-bind="props" ref="page"></multiple-admin-page>
</div>

<div id="ell2">
  <el-dialog class="user-form" :title="title" :visible.sync="dialogVisible" :center="true" width="80%">
    <multiple-admin-page v-bind="props" ref="page2"></multiple-admin-page>
  </el-dialog>
</div>
<script>
$(document).ready(function(){
    var props = {
        columns:[            
            {name:"name", label:"<?=$system_language["pinleimingcheng"]?>", is_multiple:true, is_focus:true},
            {name:"code", label:"<?=$system_language["pinleibianma"]?>"}
        ],
        buttons:[
            {name:"code", label:"<?=$system_language["chakanziji"]?>", width:200, disable_change:true, handler:function(rowIndex, row){
                //console.log(rowIndex, row)   
                props2.base.productgroupid = row.relateid;
                options.dialogVisible = true; 
                //options.title = row.brandgroupname
            }}
        ],
        controller:"brandgroup",
        key_column:"name"
    }
    
    var props2 = {
        columns:[            
            {name:"name", label:"<?=$system_language["zileimingcheng"]?>", is_multiple:true, is_focus:true},
            {name:"childcode", label:"<?=$system_language["zileibianma"]?>"},
            {name:"producttemplateid", label:"<?=$system_language["chimamoban"]?>", type:'select', data_source:{url:"/sizetop/list", oplabel:'name', opvalue:'id'}},
            {name:"weight", label:"<?=$system_language["maozhong"]?>"},
        ],
        controller:"childproductgroup",
        key_column:"name",
        base:{
            productgroupid:""    
        }
    }
    
    var options = {
        props:props2,
        dialogVisible:false,
        title:""
    }
    
    var brandgroup = new Vue({
        el:"#ell",
        data() {
            return {
                props:props   
            }
        }
    })
    
    var childgroup = new Vue({
        el:"#ell2",
        data() {
            return options
        }
    })
})
</script>
<style>
</style>

