<div id="ell">
<multiple-admin-page v-bind="props" ref="page"></multiple-admin-page>
</div>

<script>
$(document).ready(function(){
    var props = {
        columns:[
            {name:"partsname", label:"<?=$system_language['jiegoumingcheng']?>", is_create:true, is_update:true, is_show:true, width:200, is_focus:true}
        ],
        options:{
            dialogWidth:"35%"
        },
        default_language:'zh-cn',
        controller:"productinnards"
    }
    
    new Vue({
        el:"#ell",
        data() {
            return {
                props:props   
            }
        }
    })
})
</script>
<style>
</style>

