<div id="ell">
<multiple-admin-page v-bind="props" ref="page"></multiple-admin-page>
</div>

<div id="ell2">
  <el-dialog class="user-form" :title="title" :visible.sync="dialogVisible" :center="true" width="80%">
    <multiple-admin-page v-bind="props" ref="page2"></multiple-admin-page>
  </el-dialog>
</div>
<script>
$(document).ready(function(){
    var props = {
        columns:[            
            {name:"name", label:"<?=$system_language["mobanmingcheng"]?>", is_multiple:true, is_focus:true},
            {name:"picture", label:"<?=$system_language["tupian"]?>", type:"upload", multiple:false, limit:1,is_image:true,image_width:60,image_height:60}
        ],
        buttons:[
            {name:"code", label:"<?=$system_language["chakanziji"]?>", width:200, disable_change:true, handler:function(rowIndex, row){
                //console.log(rowIndex, row)   
                props2.base.tempid = row.id;
                options.dialogVisible = true; 
                options.title = row.templatename
            }}
        ],
        controller:"producttemplate",
        key_column:"name"
    }
    
    var props2 = {
        columns:[            
            {name:"name", label:"<?=$system_language["biaoti"]?>", is_multiple:true, is_focus:true},
            {name:"sortnum", label:"<?=$system_language["xuhao"]?>"}
        ],
        controller:"templatemanage",
        key_column:"name",
        base:{
            tempid:""    
        }
    }
    
    var options = {
        props:props2,
        dialogVisible:false,
        title:""
    }
    
    var brandgroup = new Vue({
        el:"#ell",
        data() {
            return {
                props:props   
            }
        }
    })
    
    var childgroup = new Vue({
        el:"#ell2",
        data() {
            return options
        }
    })
})
</script>
<style>
</style>

